### ISSUE TITLE
(Data) Homeless Camps: Add Attributes

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1]
Add Notes Attribute

**Comment by jhudsonWA** [comment]
Attributes are now setup in Dev/QA/Prod

**Comment by joeschmit** [comment]
Incorrect attributes added, looks like you used Hydrant...
![screen shot 2015-07-29 at 10 19 57 am](https://cloud.githubusercontent.com/assets/884943/8964598/51f22a58-35db-11e5-8ca3-1b68f2407082.png)

**Comment by jhudsonWA** [comment]
Fixed
