### ISSUE TITLE
Fix Feature Number Column Sorting

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1005]
Feature numbers are not sorting ascending/descending on click.

![40beb834-8338-4295-b329-cbe4d6b1c613](https://user-images.githubusercontent.com/16247034/39774506-e428aa16-52af-11e8-890f-7b6f1bc60d94.jpeg)

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Please look at this when you get a chance.

**Comment by lundyc-wsdot** [comment]
Will do.  Are you here, and do you have a moment?


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
Yep. I’m here. Need me to come over?

Sent from my iPhone

On Jun 6, 2018, at 5:49 PM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:

Will do. Are you here, and do you have a moment?


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
@kechinn Can you revisit. It was working for us when we tried today.

**Comment by kechinn** [comment]
@jhudsonWA It seems to work fine when searching Inventory. It's when I'm doing Activities searches, both feature and other, that it seems to sort strangely. Few examples:
![sortexample1](https://user-images.githubusercontent.com/16247034/41114063-29f28ac2-6a38-11e8-87d6-82c06e2dc646.PNG)
![sortexample2](https://user-images.githubusercontent.com/16247034/41114075-32731cca-6a38-11e8-84b2-71b6f47d873a.PNG)
![sortexample5](https://user-images.githubusercontent.com/16247034/41114098-49e5df50-6a38-11e8-8ca6-62c5f967f04d.PNG)

**Comment by jhudsonWA** [comment]
Got it. Thanks! We will work on that :)

On Jun 7, 2018, at 9:52 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonWA> It seems to work fine when searching Inventory. It's when I'm doing Activities searches, both feature and other, that it seems to sort strangely. Few examples:
[sortexample1]<https://user-images.githubusercontent.com/16247034/41114063-29f28ac2-6a38-11e8-87d6-82c06e2dc646.PNG>
[sortexample2]<https://user-images.githubusercontent.com/16247034/41114075-32731cca-6a38-11e8-84b2-71b6f47d873a.PNG>
[sortexample5]<https://user-images.githubusercontent.com/16247034/41114098-49e5df50-6a38-11e8-8ca6-62c5f967f04d.PNG>

**Comment by jhudsonWA** [comment]
@lundyc-wsdot ping here as well.

**Comment by jhudsonWA** [comment]
Fixed in dev/qa. Will go out to prod on 9/11

**Comment by kechinn** [comment]
Looks all good:) Closing.
