### ISSUE TITLE
Bug: Downloaded files are not removed when deleted until you switch to All Files and Back.

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1006]
Possible discussion for 4.0. Not really an issue, but if you do delete something while on the Downloaded Files tab, it won’t automatically remove from list, and you can choose to redownload. If you clear filters or move around in the File Library, it will re-sort. If you stay on that tab though and go to map or other main tab, it’ll stay.

![7923f029-cda7-4579-860f-8a97ae02d14a](https://user-images.githubusercontent.com/16247034/39775488-e32f58f0-52b2-11e8-9e64-9d8dc5e60817.jpeg)

**Comment by jhudsonWA** [comment]
Fixed the bug. It now longer shows after deleting a downloaded file.
