### ISSUE TITLE
AVL: Add Run Total to EquipmentSensor Table

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1015]
Please add the following columns to the table and update the service call, sometime this summer:
- RunTotalSolidMaterialName
- RunTotalSolidValue
- RunTotalLiquidMaterialName
- RunTotalLiquidValue
- RunTotalPrewetMaterialName
- RunTotalPrewetValue

**Comment by jhudsonWA** [comment]
These were in there as Solid, LIuqied and Prewet Material which we captured before and new Solid, Liquid and Prewet RunTotal.

The run totals aren ow in production and captured. Also added to Raw Data and Latest data exports.
