### ISSUE TITLE
Beta 4.0.0B1 After force quitting then relaunching app. The app blanks out for a few seconds before fully launching

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1016]
Database Version: 67
Map Version: 5

**Comment by ReedHunter-Wsdot** [comment]
It this where the map is showing up without any data and just a grid for about 15 seconds or so?

**Comment by jhudsonWA** [comment]
No, open the app, force quit it and then reopen and it will be all black, it’s like no window is assigned for a second or two.

**Comment by ReedHunter-Wsdot** [comment]
I'll see if my changes interfered with loading the splash screen.

**Comment by ReedHunter-Wsdot** [comment]
The launch screen worked synchronously, expecting the next UI to be there when it exited.  The new Sdk though works asynchronously, running in the background and eventually returning to display the map.  This left a time gap where no UI was available, so the screen went blank.  I fixed this by adding a 2nd view of the launch screen right before it goes black.  That 2nd copy of the launch screen is overwritten once the map loads.
