### ISSUE TITLE
Beta 4.0 B1 Map not loading after sync

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1017]
After sync, map is grey and not loading. Tried to do a hard reset and now it is a red screen with thinking loop.
![img_0108](https://user-images.githubusercontent.com/16247034/41116885-6833ac46-6a40-11e8-91bd-8805ffb31617.PNG)
![img_0109](https://user-images.githubusercontent.com/16247034/41116887-697e6dca-6a40-11e8-8115-e7fe585ec504.PNG)

**Comment by kechinn** [comment]
Update: Downloads after 2-3 minutes of thinking.

**Comment by ReedHunter-Wsdot** [comment]
When you say downloads after thinking 2-3 minutes, do you mean that the map displays properly after that time?

**Comment by kechinn** [comment]
Yes, it will load fine after that time. But that only seems to be the case after the hard reset.. If I just did a sync and let it sit on the grey screen, it doesn't ever seem to load. Eventually it stops thinking (i.e. the spinning loops disappear). but the map still won't load, even if you hit the GPS button or pan around. I have one extra iPad that's been sitting with the grey screen for a long time now and it still hasn't loaded successfully.

**Comment by ReedHunter-Wsdot** [comment]
Steps to reproduce: 
1) open Hats
2) identify a culvert then the attributes button for that culvert
3) In the attributes window, tap on "Edit" in the upper left
4) Change some attribute.  I added some text to Access Instructions.
5) tap "Save Attributes", then tap [ok] on the window that appears.
6) start a map sync

on 2nd test pass, the result was:
06-07-2018 03:04:22 PM:
Attribute (material type) on Feature (Culvert - WSDOT0001261491) Could Not be Updated: Plain Steel. URL: http://hatsqa.wsdot.loc/Maintenance/Management/Activities/api/ios/UpdateRoadsideFeatureAttribute, Error Message: Response status code was unacceptable: 500.

on 1st test pass, the sync was successful.  Upon closing the sync UI, the map load would sit for minutes with a grey background.

**Comment by ReedHunter-Wsdot** [comment]
Two problems of mine I'm seeing here:
1) When you tap away from the map UI and then come back we're treating it just like a new startup of Hats, reloading a new map UI.  I'll look at keeping the original map so we don't have to keep reloading it.  

2) A release/reload is sometimes the right move like when you redownload a new basemap or features map, but there too I'm not properly unloading the old map.  Links to it aren't being released, so it's still sitting there in memory.  The new Sdk is touchy, not allowing a map layer to be loaded in more than one map (the old Sdk didn't care), so I can't add layers to the new map.  That makes it blank.

**Comment by ReedHunter-Wsdot** [comment]
This is now fixed.  The new Sdk forbids several coding patterns we had from before such as creating a layer more than once ever from a data source, keeping more than one reference to the database if you want to sync, and some others.  All Hats modules now play nice with one another, reusing a single database instance, reusing layers between syncs, and deleting all references when we redownload a file, so syncs and redownloads are working again.
