### ISSUE TITLE
HATS 4.0 B1 Update Map Location and GPS Crash

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1018]
Cannot tell what vertex you are deleting or which vertex is first/last because the vertex points are all in red. There is a very light blue halo behind the red dot when you select on the different vertices, but not super noticeable unless you are really looking for it.

Also, hitting Collect GPS button doesn't do anything from this screen. If you hit the Collect GPS button when adding a new feature, it makes HATS crash.

![img_0112](https://user-images.githubusercontent.com/16247034/41118507-05f42b32-6a45-11e8-9afc-5b4e48d3efcb.jpg)

**Comment by ReedHunter-Wsdot** [comment]
There are two bugs here
1- the colors are the same for highlighting the selected feature and for the currently selected vertex.  I'll see if I can highlight the currently selected vertex with yellow.  If not then I know I can change the highlight for the currently selected feature to yellow.
2- crash on collect GPS.  I'll look at this after I fix issue #1065.

**Comment by ReedHunter-Wsdot** [comment]
Crash on collect GPS bug is now fixed and will be part of the next beta.  I saw some options along the way for controlling the highlighted vertex.  I'll look into that tomorrow.

**Comment by ReedHunter-Wsdot** [comment]
Selected vertex is now highlighted in yellow to distinguish from when the whole feature is highlighted.
There is also now a default selected vertex when you start editing.
