### ISSUE TITLE
HATS 4.0 B1 Zoom extent

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1019]
Not really a big deal, but can the zoom extent be fixed so it matches what the old version did and stop at statewide level?
![image-1](https://user-images.githubusercontent.com/16247034/41119733-6749ddb6-6a48-11e8-9077-df1a09a370bb.jpg)

**Comment by ReedHunter-Wsdot** [comment]
Can do.  The old code to zoom to state-wide extent is actually still there, but it's being interfered with by the Esri bug that delays the data load by about 15-30 seconds.  I'll shift the code around that sets the initial map extent.

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot is this still a bug in latest 4.0 betas? If no please close.

**Comment by ReedHunter-Wsdot** [comment]
It's on the screen for about 1 second now on the older devices, and newer devices don't have this problem, but yes it's still there on the first startup.

**Comment by ReedHunter-Wsdot** [comment]
The fix for this will be in the next beta.
