### ISSUE TITLE
(HATS IOS) Adding "ESA Fish Stick"

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#102]
Reed can you add the Roadside Maintenance Sensitive Areas layer to the basemap. Saved a copy here W:\Public\DOT\ReedHunter.

**Comment by ReedHunter-Wsdot** [comment]
Got it.  I see this is a line feature type.  Did you want the symbol to be the light green you have in the layer file?

**Comment by tangoai** [comment]
@ReedHunter-Wsdot - yes the light green looked ok

**Comment by ReedHunter-Wsdot** [comment]
I'll close this once the basemap is ready for download.

**Comment by joeschmit** [comment]
status update? @ReedHunter-Wsdot

**Comment by ReedHunter-Wsdot** [comment]
Added to standard basemap (not from AVL basemap).  I've made this only visible when zooming in tight, just like when the Wsdot features are visible.  I'll ask that Oai take a look at a copy of this basemap I've placed at \wsdot.loc\hq\Public\30Day\GRDO\HunterR\HATSiOS\basemapWithSensitiveAreas.  This basemap doesn't have everything I should put in before we next deploy to our users, but it does have the ESA data, rivers clipped around the roads to make the file smaller, and mileposts every 1/10th of a mile.

**Comment by ReedHunter-Wsdot** [comment]
Oai, can you load up the basemap file I put on the 30day folder and let me know if you'd like its visible extent adjusted?  I made it only show up when you're zoomed in close. Green lines will be distracting if you leave them visibly mixed in with state routes further zoomed out.  Assign back to me when you're done.

**Comment by ReedHunter-Wsdot** [comment]
Available in current beta basemap for download.  Oai looked at this earlier, and said it looked good.
