### ISSUE TITLE
Grate Inlet Cleaning

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1025]
@jhudsonWA  Got another PDR and ran into that issue from last time, blank exports with a Cleaning activity. Current Records search shows me 14 Grate Inlet Cleaning activities, but zero of them export from Activity Record Report page.

![image](https://user-images.githubusercontent.com/16247034/41735442-8ecc0c0a-753e-11e8-858b-6fe91a4d591e.png)

**Comment by jhudsonWA** [comment]
Working on it.

**Comment by kechinn** [comment]
~~Seeing same thing with Other Activities Report for Shoulder Maintenance - Maintenance/Repair/Slide Cleanup.~~

**Comment by jhudsonWA** [comment]
Working on it. Trying to figure out what changed and remember what was fixed last time.

On Jun 21, 2018, at 11:17 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Seeing same thing with Other Activities Report for Shoulder Maintenance - Maintenance/Repair/Slide Cleanup.

**Comment by jhudsonWA** [comment]
Found it. Fixing now. :)

On Jun 21, 2018, at 11:17 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Seeing same thing with Other Activities Report for Shoulder Maintenance - Maintenance/Repair/Slide Cleanup.

**Comment by jhudsonWA** [comment]
Great cleaning fixed

On Jun 21, 2018, at 11:20 AM, Joshua Hudson <hudsonj@wsdot.wa.gov<mailto:hudsonj@wsdot.wa.gov>> wrote:

Found it. Fixing now. :)

On Jun 21, 2018, at 11:17 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Seeing same thing with Other Activities Report for Shoulder Maintenance - Maintenance/Repair/Slide Cleanup.

**Comment by jhudsonWA** [comment]
I’ll fix the others after lunch. Looks like different issue than before (same result, but different cause). Some of the older forms from 2016 no longer have a way to match event form version ids, all form the same couple of months. I fixed the cleaning for you but still need to write a script to fix the 600 other forms versions

On Jun 21, 2018, at 11:17 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Seeing same thing with Other Activities Report for Shoulder Maintenance - Maintenance/Repair/Slide Cleanup.

**Comment by jhudsonWA** [comment]
Fixed
