### ISSUE TITLE
BURP Enhancement: Save Work Prompt

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1028]
Would like to have a "You have unsaved changes, please save your work before leaving page" or similar prompt upon leaving a 'page' (including changing sub programs, like from M1 to M2 on same page) with unsaved changes. Or a way to auto-save changes made within sub programs to prevent that data loss. Apparently, it is easy to forget to hit the Save button after entering numbers and leaving page or changing sub program, resulting in lost work.

**Comment by brianblood** [comment]
Good idea!
Done.
