### ISSUE TITLE
Budget Tool: Budget Allotments Year Change

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1030]
I didn't change any numbers, just hit the unlock button, and after saving and switching the year to 2015-2017, the page says "A problem occurred while fetching allotment data. Check the server error log for details." Also affects when switching to a region tab, says that "the control totals have not been created for..."

![image](https://user-images.githubusercontent.com/16247034/41857855-472ba8a8-784d-11e8-8c7b-1044b821de18.png)

**Comment by jhudsonWA** [comment]
Hold off testing until we can confirm server issue fixed. Lots of issues like this reported this morning.

Sent from my iPhone

On Jun 25, 2018, at 8:00 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1030<https://github.com/WSDOT/HATS/issues/1030> to @jhudsonWA<https://github.com/jhudsonWA>.

**Comment by kechinn** [comment]
Okay.

**Comment by brianblood** [comment]
Fixed!
