### ISSUE TITLE
Budget Tool: Budget Allotments Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1031]
If you change the biennium and then the sub-program, the page does not appear to be refreshing and pulling data correctly. Once in the new biennium (2015-2017), on M1 it appears to refresh page and show same page as in previous biennium (2018-2019). But once you switch the sub-program, say to M2, it will give the statement "The control totals have not been created for Sub-Program M2. The they will be generated automatically when visiting the Control Totals form Sub-Program M2 for biennium 2015." At this point, if you then go back to M1 it will show the same statement now. If this statement is true, it should show immediately for the M1 upon switching biennium, but it doesn't. Then, the problem persists even when returning to current year (until you change the sub-program), not refreshing correctly.

![image](https://user-images.githubusercontent.com/16247034/41858765-805777d6-784f-11e8-9356-ce82940eb2b7.png)
![image](https://user-images.githubusercontent.com/16247034/41858821-9f1338f4-784f-11e8-894d-23582a3447a5.png)
Back to previous year, same statement:
![image](https://user-images.githubusercontent.com/16247034/41859107-466c88ee-7850-11e8-8c4d-7b0d9892a05d.png)

**Comment by brianblood** [comment]
This was caused by a bug that prevented org codes from being associated to multiple bienniums.  When trying to load data for 2015, it didn't see any org codes and threw and index out of range exception.
I updated the offending stored proc and will rerun it for all of the org codes when pushing the next build.

**Comment by brianblood** [comment]
Pushed to QA
