### ISSUE TITLE
Budget Tool: Budget Allotments Descriptions

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1038]
Noticed a spelling mistake on the budget allotment page (and the associated excel sheets) with 4A3 Bridge Cleaning and Painting where the word Cleaning has an 'i' in it. 
![image](https://user-images.githubusercontent.com/16247034/42231068-651ad5a2-7e9f-11e8-8775-7e296bd202f5.png)

Also, Brian, where are did you get the title/descriptions from? Some of them are different from the MAP Activity documents and the Cognos and the SharePoint excel sheets that I've pulled. One example being 6B3 which says "Surveillance Control & Driver" in HATS, but everywhere else I look 6B3 says "INTELLIGENT TRANSPORTATION SYS." Another example being 6A5, which is "Advisory Sign Maintenance" in HATS and "Guide Sign Maintenance" elsewhere.

**Comment by brianblood** [comment]
The titles / descriptions all come from the WSDOT data library.  I'm not sure where Cognos and SharePoint are getting their descriptions from, but I would have no objection to pulling from the same source if it was feasible and the end users wanted it.  
I have submitted a request for the misspelling to be corrected in the WSDOT datalibrary.  As soon as I hear that it's been fixed, I will close this one out.

**Comment by brianblood** [comment]
Fixed
