### ISSUE TITLE
Budget Tool: Excel Spreadsheets Formatting

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1039]
At some point will want to work with Andrea and Nicole to reformat these Excel spreadsheets and make the titles and formatting a bit more uniform, if not HATSy:) I know that they're probably just formatted after the originals, but there is some scrolling weirdness going on, like some columns are frozen by default and varies between regions.

**Comment by kechinn** [comment]
Andrea mentioned that the Region Dollar and Work Completion by MAP should be free of any frozen columns/rows in the Excel spreadsheets.

**Comment by brianblood** [comment]
Unfroze all columns in Region Dollar and Work Completion by MAP.  We can revisit the reformatting at a later date.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
