### ISSUE TITLE
Budget Tool: Budget Allotment Control Totals for Previous Year Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1044]
Cannot view Control Totals page for previous biennium, throws a server error.

![image](https://user-images.githubusercontent.com/16247034/42245087-5aac75c6-7ecc-11e8-8a49-300b8d40425e.png)

![image](https://user-images.githubusercontent.com/16247034/42245115-6c794a54-7ecc-11e8-929a-372197b2a822.png)

**Comment by brianblood** [comment]
Fixed with #1031
