### ISSUE TITLE
Budget Tool: Budget Allotments 4 Digit Orgcode Allotment Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1045]
If you enter an dollar allotment amount for a four digit Orgcode, it does not cross over to other 4 digit Orgs as it should. If you enter a dollar allotment in one 4 digit org, that same amount should be subtracted from the total amount remaining for the other 4 digit orgs. 

![burp_budgetallotments_4digitorgdollarallotment](https://user-images.githubusercontent.com/16247034/42246078-204893f2-7ed0-11e8-8f19-a93f3f32294d.PNG)

![burp_budgetallotments_4digitorgdollarallotmentbug](https://user-images.githubusercontent.com/16247034/42246210-a4e15c84-7ed0-11e8-8199-c3a7484904db.PNG)

**Comment by brianblood** [comment]
Fixed in QA
