### ISSUE TITLE
Budget Tool: Appropriation Remaining Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1047]
Unless there is a already an appropriation amount set under the Control Totals tab, any amount that you enter into the Allotment box for Appropriations equals a negative remaining number.

![image](https://user-images.githubusercontent.com/16247034/42247950-152df1ee-7ed8-11e8-8955-c18cb19a6e01.png)

![image](https://user-images.githubusercontent.com/16247034/42248388-0f2f33f0-7eda-11e8-957c-2b0a957f9fc1.png)

**Comment by brianblood** [comment]
I believe this is working as designed.  If the parent has been allotted zero dollars for a given allotment (as is the default), then any amount entered into the current org code allotment is going to appear as a deficit.  
I'm working my way through the other bugs, and will likely have more questions as I go on, but will give you a call and we can discuss to make sure I understand the issue properly before closing this one.

**Comment by kechinn** [comment]
You're correct, sorry, we got confused on this one.
