### ISSUE TITLE
Budget Tool: Add Appropriation Button

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1050]
Is it possible to add a button to allow admin to create a new appropriation? Also, anyway to allow for an admin to add/edit any or all titles, descriptions, etc.? I'm assuming the descriptions and items will change or get updated in the future, so it would be nice to have the ability to do that from our side rather than ask continuously asking you to.

**Comment by brianblood** [comment]
We don't have access to create new appropriation codes from within the MBT - just use those that already exist within the WSDOT Data Library.  Titles, descriptions et all are also being pulled from there, so we cannot change them either.
