### ISSUE TITLE
Budget Tool: Control Totals Sub-Program M5

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1052]
If you click from a Region to the Control Totals tab and then switch the Sub-Program to M5, the M5 screen gets a little weird formatting. 

![image](https://user-images.githubusercontent.com/16247034/42541835-f1778734-8458-11e8-844b-b2ea2ac187eb.png)

**Comment by brianblood** [comment]
Fixed in QA.  You may have refresh the cache in order for the javascript changes to take effect.
