### ISSUE TITLE
Budget Tool: Future Enhancement 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1053]
For Budget Reporting Program - Version 1.5 maybe, after everything else is completed. Andrea would like to create a report page that models the [http://nwweb/M/ ](url) web page for the Regional Reports. 

![image](https://user-images.githubusercontent.com/16247034/42542152-5d2614a4-845a-11e8-97a8-6799c9186e1d.png)

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
