### ISSUE TITLE
Budget Tool: Incomplete M3 Regional Report Export

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1054]
The Regional Report Excel export of M3 Inventory And Stores Administration Plan vs. Actual by Month is incomplete, with no rows or column names/values.

![image](https://user-images.githubusercontent.com/16247034/42578232-004cda16-84db-11e8-8052-315a5df32885.png)

**Comment by brianblood** [comment]
The stored procedure was returning zero entries if a budget had not yet been saved for the selected region.
Fixed in dev.

**Comment by brianblood** [comment]
Pushed to QA
