### ISSUE TITLE
Budget Tool: Budget Allotments Timeout Error On 6 Digit Orgcode

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1055]
Getting a timeout error from the Region tabs when changing the orgcode to 6 digit from any sub-program. Sometimes when attempting to switch to a different 6 digit Org, it loaded the page, but for the most part failed to load.

![image](https://user-images.githubusercontent.com/16247034/42580645-dca355ae-84df-11e8-83fc-c8acef0b2462.png)

**Comment by brianblood** [comment]
Fixed and pushed to QA
