### ISSUE TITLE
Budget Tool: Budget Allotments Page Control Totals Note Grammar

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1057]
"The control totals have not been created for Sub-Program M2. **The they** will be **genererated** automatically when visiting the Control Totals **form** (for?) Sub-Program M2 for biennium 2015."

**Comment by brianblood** [comment]
Fixed in dev.

**Comment by kechinn** [comment]
Still need to fix the "for" part. Please and thank you:)

**Comment by brianblood** [comment]
Fixed
