### ISSUE TITLE
Budget Tool: Incomplete Year Reports

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1059]
Although there are no numbers planned for 2015-2017, the Excel reports for Program M Budget, LEMO and FTE, and Regional Reports are incomplete, not showing rows, columns, and/or tabs of data. 

The Region Dollar and Work Completion report is shown as complete for 2015-2017, just with $0 numbers (as it should be).

**Comment by brianblood** [comment]
Fixed!

**Comment by kechinn** [comment]
Looks like one was missed under Regional Reports: M2 Plan vs Actual by Month. The rest look all good!
