### ISSUE TITLE
[HATS iOS] Check/Request camera authorization on App Startup

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#106]
Users are saying no when prompted then getting weird attachment behavior.

**Comment by joeschmit** [comment]
@jhudsonWA should we move this to 1.4?

**Comment by jhudsonWA** [comment]
Good question. How long do you want to wait. I have a 1.3.1 that we can push next week for the attachment description bug. Depends on how long the change from reed would take.

**Comment by joeschmit** [comment]
.3.1 is good with me!

Sent from my iPhone

On Jan 13, 2016, at 9:27 AM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Good question. How long do you want to wait. I have a 1.3.1 that we can push next week for the attachment description bug. Depends on how long the change from reed would take.

**Comment by jhudsonWA** [comment]
Added to 1.4Beta 3. App now requires camera access and will prompt and give instructions if user turned it off on app start.
