### ISSUE TITLE
Budget Tool: Regional Reports Export Issues

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1067]
Few things, let me know if you'd like me to split this into different issues:

1) If there is no Dollar Expenditure Authority set for an Orgcode and you attempt to export a Regional Report, it throws a server error. Which is expected considering there is no budget set in Control Total, but maybe just show another message like "Budget must be set in Control Totals first".
![image](https://user-images.githubusercontent.com/16247034/43099599-84e5ce86-8e77-11e8-9e2c-5ed5edd014fd.png)

2) When exporting a regional report, I entered a test number into the LEMO section for L and another number in the appropriation 030 for FM1. When exporting, the "Planned to Date column" in the excel sheet is showing the same number from FM1 across all months. If you enter another number in another FM, everything past that date then adopts the sum of  that number and the numbers before it.
![image](https://user-images.githubusercontent.com/16247034/43106243-b5bb5502-8e8c-11e8-99cf-8f66684c98d7.png)

![image](https://user-images.githubusercontent.com/16247034/43103826-3501ed84-8e84-11e8-86cd-bcbed9a5257a.png)

3) This issue also appears to persist across different regions, because I just ran the report for sub-program M1 in OR, and it is showing the same numbers as SCR sub-program M3/M5, and if you add values, they add to the sum of each other. For example, the M5 report is pulling the same numbers as the M3 report. There is $0 FMs in M5 for SCR.
![image](https://user-images.githubusercontent.com/16247034/43106334-16a06ec0-8e8d-11e8-819a-bac65e738bc4.png)

**Comment by brianblood** [comment]
1.  Fixed!
2.  This is by design.  Planned to date is just a running total the budget to the given month, so it should increase for each month that there is money allotted, and remain flat for those months where the value is zero.
3.  Fixed
