### ISSUE TITLE
Ability to send a message to display on an individual iPad

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#107]
There have been iPads deployed such as the ones called "iPad" and "NWC6432168" for which we don't have a point of contact to notify for instructions to support problems on the device.  Do we have tools to remotely administer those devices?  

If not, then as we get notifications from iPads that they have problems it would be good to be able to display instructions to the user such as "Please redownload map features and let us know if you can sync after that.", or "This iPad needs to be updated to a more recent release of  iOS.  Please deliver this to Josh Hudson so he can do it personally on his free time at home."  I'm thinking that if we could tailor messages based on the ID of the device, we could queue up messages to display such as after when they sync with the server.

**Comment by jhudsonWA** [comment]
Traditionality this is done through Push Notifications, but we could do it as part of the sync process as well since these devices are not always online. 

However, as part of policy, no device should be called iPad. I'll look at Meraki and see where this iPad is located and can use that to track it down. 

I'll do the same for NWC6432168, but anything with an asset tag like this is supposed to be in remedy (our service desk software and asset tracking system)

**Comment by ReedHunter-Wsdot** [comment]
We can add to that list:
NCC6348003 – NC - Wenatchee PE Complex (Euclid) – Remedy does not have an assigned person
NCC6348006 – NC - Wenatchee PE Complex (Euclid) – Remedy does not have an assigned person
NCC6348005 – NC - Wenatchee PE Complex (Euclid) – Remedy does not have an assigned person
NCC6348021 – NC - Wenatchee PE Complex (Euclid) – Remedy does not have an assigned person

**Comment by jhudsonWA** [comment]
Got it, we do have some weirdness because in some regions, especially NCC they are not assigned to a person as they are shared, but maybe they can assign them to a lead tech nor a maint supervisor so we have at least a single point of contact.

**Comment by jhudsonWA** [comment]
The bad news is we have 32 devices named iPad in the state. 6 of which are reporting into Meraki right now:

They are located in:

Port Orchard
Kingston, WA
Seattle
Moses Lake, WA
Olympia (Reported off Yelm Hwy)

I do have serial numbers for these, but not asset tags as those are not stored in Meraki

**Comment by jhudsonWA** [comment]
@joeschmit Can we send out a mass email to have folks verify that their device names match their asset tags. Otherwise it is really hard for us to support them.,

**Comment by jhudsonWA** [comment]
Going to support this one using #442
