### ISSUE TITLE
New Add Feature/Update Map Location Vertex

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1072]
Any way to make the new mapping SDK match the vertex colors/shapes of the old map style? So, all the vertexes are blue except the leading vertex. With the new SDK it is harder to tell which end you are starting from (some people have trouble seeing blue halos). Especially with editing the map location of polygons and lines as none of the points are haloed to begin with, so you have to create a dummy point just to figure out which direction it leads from.

**Comment by ReedHunter-Wsdot** [comment]
I'm going to look at whether I can change the color of the halo highlighting the currently selected vertex.  When I dive into that I'll have the change to see what else if anything can be customized about the editing UI.

**Comment by ReedHunter-Wsdot** [comment]
Please take a look at the new yellow halo around the selected vertex.  I can change that to any color.  I may also be able to expand the highlighting around the feature.

**Comment by jhudsonWA** [comment]
In next beta of course..

Sent from my iPhone

On Aug 2, 2018, at 5:19 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Please take a look at the new yellow halo around the selected vertex. I can change that to any color. I may also be able to expand the highlighting around the feature.

**Comment by ReedHunter-Wsdot** [comment]
The 100.3 edit sketch could be customized.  Aside from now highlighting the selected vertex with a yellow halo, it now looks like it did at the 10.2.5 Sdk.
