### ISSUE TITLE
New Mapping Tool

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1073]
Not really an issue, thought this was interesting....for points and polygons, if you tap on the first point you create then the point will disappear, and then if you tap on the line/polygon or any vertex with a blue halo, then it will bring up a Photoshop-like box with a rotating option and drag handles on the corners that allows you to resize and rotate the feature.

Is there a way to turn this feature off if we decide we don't want to use it, since it might cause some confusion with end users? Or is it there to stay? We'd just have to edit How-To videos accordingly.

![image](https://user-images.githubusercontent.com/16247034/43208846-28cb640c-8fe0-11e8-8e91-f14f3aaea315.png)

**Comment by ReedHunter-Wsdot** [comment]
This is now disabled in the next beta.
