### ISSUE TITLE
Drawing Error Between Search Tool and Identify

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1076]
If you search for a feature using the Select Search Tool, edit that feature and save, go back to the Identify tool and edit the feature there, then go back to the Search tool again and attempt to edit a third time within the search tool then the sketch will revert to past edits and cause the drawing save/cancel sketch screen to disappear. At this point, without the ability to cancel sketch, the only way to stop the drawing process is to close HATS (otherwise it causes some UI weirdness). It doesn't appear to cause any issues with syncing. 

Also (similar in Prod) there is nothing stopping anyone from closing the Search Tool in the middle of an editing sketch session and clicking other buttons (like add feature or Identify). Which, after doing something else that requires saving, causes weirdness in the UI.

I figure users won't happen upon this often, if at all, but I suppose it could in the event that someone doing a bunch of editing to the same feature from field and office without syncing in between, or was just randomly hitting buttons like me. Let me know if you want me to do any screen recordings of my iPad for better explanation.

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot is this still a bug in latest 4.0 betas? If no please close.

**Comment by ReedHunter-Wsdot** [comment]
This will still be a bug.

**Comment by ReedHunter-Wsdot** [comment]
This is fixed and checked in for the next build.

I made two changes:
1. The map search toggle button now becomes disabled when editing features on the map, just like we already do with the map identify button.
2. Whenever you reopen the map search panel, any previous search result is cleared.  If they entered a number before though, that's still there so they can just tap the search button to get their result.
