### ISSUE TITLE
Beta 4.0 Map Rotation

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1077]
As cool as it is, I don't think we need the new SDK two finger rotation, any way to remove that part and leave just the two finger zoom?

Might cause some orientation confusion if user rotates their screen while attempting to zoom only, which is very easy to do. The rotation can only be reset by switching map modes or by quitting and reopening the app, but is not reset by tapping the GPS button.

**Comment by ReedHunter-Wsdot** [comment]
There should be a way to disable that.  I'll take a look.

**Comment by ReedHunter-Wsdot** [comment]
fixed.  I also disabled panning the map with the magnifier window.  It was frustrating when trying to magnify on a feature at the edge of the map to have the map suddenly start scrolling.
