### ISSUE TITLE
(HATS iOS) (HATS Web) Admin tools for creating/editing/updating feature attributes

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#108]
Would like the ability to create/edit attributes (setup predefinted/multiples/text/number/date time) just like HATS forms from an Admin tool

**Comment by jhudsonWA** [comment]
Lets look into this for 5.0 in July. It's "complicated". A lot depends on this and to setup a attribute it currently takes 4 different tables to be updated.

**Comment by jhudsonWA** [comment]
In QA
