### ISSUE TITLE
Load updated cable barrier data

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1084]
I'm adding this task so it can be tracked.

There is updated higher precision cable barrier data that needs to be loaded, but it first may need to be merged with the older data.

**Comment by jhudsonWA** [comment]
We can easily update the spatial of the exiting features as long as I know the id's of the current ones. Is that in the dataset?

**Comment by ReedHunter-Wsdot** [comment]
I have some data merge/qa questions with Keisha before we can move forward with loading the cable barriers.  If we just append the new without removing some of the old, then we'll have duplicates.  If we remove all the old before loading the new then it looks like we'll be throwing out some good data without replacing it.  Some of the new lines also only partially overlap some of the old lines.

**Comment by kechinn** [comment]
The cable barrier features that need to be loaded are new features from new construction. In some cases, there was some older cable or guardrail in those areas, but it was a different manufacture type. I went through and hid most, if not all, of the barrier in those areas that no longer exists.

**Comment by jhudsonWA** [comment]
Ok, so a simple add then. That is easy. Reed, please load up in a new database in Staging named something like CableBarrier2018 and I’ll load them as new.

On Aug 6, 2018, at 2:04 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


The cable barrier features that need to be loaded are new features from new construction. In some cases, there was some older cable or guardrail in those areas, but it was a different manufacture type. I went through and hid most, if not all, of the barrier in those areas that no longer exists.

**Comment by ReedHunter-Wsdot** [comment]
The data is in staging, and the name is CBUpdates2018.

**Comment by jhudsonWA** [comment]
Can you reload with SRID projected into 2927 like all the other staging tables in HatsGeodataStaging.

Thanks!

Josh

On Aug 7, 2018, at 7:13 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


The data is in staging, and the name is CBUpdates2018.

**Comment by ReedHunter-Wsdot** [comment]
Done.  The dataset name is CBUpdates2018_WaStPlnSouth.

**Comment by jhudsonWA** [comment]
Thanks!

Keisha, These have been loaded into QA and Snapshots. Give it a look and I can run it in prod.

On Aug 9, 2018, at 1:37 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Done. The dataset name is CBUpdates2018_WaStPlnSouth.

**Comment by kechinn** [comment]
@jhudsonWA I'm not seeing them in QA.

**Comment by jhudsonWA** [comment]
You won’t see them on the iPad without a true up. Did you check web?

Sent from my iPhone

On Aug 9, 2018, at 2:59 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonWA> I'm not seeing them in QA.

**Comment by kechinn** [comment]
Yup, that's where I looked. I'm not seeing them on web.

**Comment by jhudsonWA** [comment]
Weird. Checking

Sent from my iPhone

On Aug 9, 2018, at 3:28 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Yup, that's where I looked. I'm not seeing them on web.

**Comment by jhudsonWA** [comment]
I may have loaded them into Dev twice. :) Running script again.

On Aug 9, 2018, at 3:28 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Yup, that's where I looked. I'm not seeing them on web.

**Comment by jhudsonWA** [comment]
Ok, NOW they should be in QA :)

On Aug 9, 2018, at 3:34 PM, Joshua Hudson <hudsonj@wsdot.wa.gov<mailto:hudsonj@wsdot.wa.gov>> wrote:

I may have loaded them into Dev twice. :) Running script again.

On Aug 9, 2018, at 3:28 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Yup, that's where I looked. I'm not seeing them on web.

**Comment by kechinn** [comment]
Alrighty, now I see them! For some reason though, the attribute search by manufacturer type is not working. I see the new Brifen features if I click on individual features, but if I search by that attribute it says no features found.

**Comment by jhudsonWA** [comment]
Weird. Did you just add that variable after I did the load?

On Aug 9, 2018, at 3:58 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Alrighty, now I see them! For some reason though, the attribute search by manufacturer type is not working. I see the new Brifen features if I click on individual features, but if I search by that attribute it says no features found.

**Comment by kechinn** [comment]
No, that attribute variable already existed.

**Comment by jhudsonWA** [comment]
K, checking the attribute variable ids.

On Aug 9, 2018, at 3:58 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Alrighty, now I see them! For some reason though, the attribute search by manufacturer type is not working. I see the new Brifen features if I click on individual features, but if I search by that attribute it says no features found.

**Comment by jhudsonWA** [comment]
Hmm so the variable ids where not set for any of the attributes, fixing that.

On Aug 9, 2018, at 3:58 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Alrighty, now I see them! For some reason though, the attribute search by manufacturer type is not working. I see the new Brifen features if I click on individual features, but if I search by that attribute it says no features found.

**Comment by kechinn** [comment]
I should mention, the same issue is with the other features with existing attribute types, like Gibraltar and Trinity Cass TL-4. The search will bring up old features though, so it only has to do with just searching for the 47 new ones.

**Comment by kechinn** [comment]
Oh whoops, just saw your comment. Didn't refresh:) Sounds good. Other than that, I think everything looks okay.

**Comment by jhudsonWA** [comment]
Yep, non of the variables were set like they should have been. I think last time I loaded cable barriers we still had the old attribute table schemas.

Try now.

On Aug 9, 2018, at 4:08 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


I should mention, the same issue is with the other features with existing attribute types, like Gibraltar and Trinity Cass TL-4. The search will bring up old features though, so it only has to do with just searching for the 47 new ones.

**Comment by kechinn** [comment]
Yup, I see them now:)

**Comment by jhudsonWA** [comment]
Good to load in prod?

On Aug 9, 2018, at 4:08 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


I should mention, the same issue is with the other features with existing attribute types, like Gibraltar and Trinity Cass TL-4. The search will bring up old features though, so it only has to do with just searching for the 47 new ones.

**Comment by kechinn** [comment]
Yes, good to go. Thanks!

**Comment by jhudsonWA** [comment]
Prod is loaded and snapshots refreshed.

On Aug 9, 2018, at 4:08 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


I should mention, the same issue is with the other features with existing attribute types, like Gibraltar and Trinity Cass TL-4. The search will bring up old features though, so it only has to do with just searching for the 47 new ones.

**Comment by kechinn** [comment]
Looks good in prod, thanks!

**Comment by jhudsonWA** [comment]
So a true up will be needed to see the new features on the iPad. But I think it’s safe to close this “issue"

On Aug 9, 2018, at 4:40 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good in prod, thanks!
