### ISSUE TITLE
Budget Tool: LEMO and FTE 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1085]
Feedback from end user. They would like to see the LEMO and FTE Report show subprograms in normal numerical order rather than as it is currently (M2, M3, M1, M5).

Also, with the excel report (i.e. ObjectTypeName) as well as with the Budget Allotments pages, would like to rename LEMO as Labor, Equipment, Material and Other.

**Comment by brianblood** [comment]
Done!
