### ISSUE TITLE
Budget Tool: M1, M3 and M5 Regional Report

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1088]
The M1, M3 and M5 Planned-To-Date column is pulling numbers from the wrong place. Not sure where the numbers are coming from, they are the same across all of these regions and Sub-Programs. 

![image](https://user-images.githubusercontent.com/16247034/44039044-0b4d3d50-9ecd-11e8-96a9-28393d7fb9a6.png)

**Comment by brianblood** [comment]
Fixed.
