### ISSUE TITLE
(HATS iOS) (HATS Web) Admin tool to build a table and link in other areas

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#109]
This might be a stretch, but we have a need for this.

Ability for an admin to build a table that can be updated/maintained and then later referenced within the app.  For operators, work ops and MAP criteria.  Also the ESA program possibly, we can talk a little more about this.

**Comment by jhudsonWA** [comment]
@joeschmit was not mentioned in your updates? Still something interested in or close it up?
