### ISSUE TITLE
Budget Tool: Control Totals Orgcodes

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1090]
Not sure where this one came from, can orgcode 11 be removed?

![orgcode11](https://user-images.githubusercontent.com/16247034/44160021-f3628680-a06d-11e8-8e6d-7c04d91fef7a.png)

**Comment by jhudsonWA** [comment]
“It goes to 11!"

On Aug 15, 2018, at 9:33 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure where this one came from, can orgcode 11 be removed?

[orgcode11]<https://user-images.githubusercontent.com/16247034/44160021-f3628680-a06d-11e8-8e6d-7c04d91fef7a.png>

**Comment by brianblood** [comment]
Lol…sorry, that was my own testing.
