### ISSUE TITLE
Budget Tool: Viewing Enhancements

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1095]
So, after some discussion, users want to try having a horizontal scroll bar to view all of the boxes on the Budget Allotments pages rather than try and squish them all into one page view. Users would like to be able to see all the numbers in length, not cut off by the size of the box or wrapped into next line down. Similar enhancements for the web page table when pulling Regional report  4 digit-the font is too small too read.

Also, a user wanted to know if it would be possible to change the font color of the page drop downs from grey to black or darker grey because she has trouble reading the text. I realize it just matches the rest of HATS, but I think most of the users who will use the budget tool will not actually be in the rest of HATS.

**Comment by brianblood** [comment]
Done in Dev.
