### ISSUE TITLE
Budget Tool: LEMO and FTE Report BTD Expend FTEs Error

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1097]
BTD Expend FTEs should be an average from FIRS, not a sum. 

For example, in the HATS report, it is showing a sum of FIRS FTE expenditures (~20.30) over the 4 months that I pulled the report for:
![image](https://user-images.githubusercontent.com/16247034/44431885-a7737e00-a554-11e8-8156-c08dd2124f23.png)

**Comment by brianblood** [comment]
Fixed!
