### ISSUE TITLE
Budget Tool: Region Dollar and Work Completion by MAP Report Error

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1099]
Looks like the Southwest Region tab has an extra two rows at bottom of MAP Activity and Biennial Dollars Planned, "Checksum:" and "Difference."  Not sure where the $118,540,431 number is coming from, but maybe something from the template because the same thing is on the spreadsheet for 2015-17.

I don't think it's necessary, so could you please just remove those two?

**Comment by brianblood** [comment]
Yep, they were part of the template.  Fixed in dev.

**Comment by brianblood** [comment]
This is now in qa.
