### ISSUE TITLE
(HATS iOS) Basemap HATS features viewable at a higher extent

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#110]
Users are having trouble driving at highway speeds to features, extent needs to be increased to a higher level.

**Comment by joeschmit** [comment]
Status update? @ReedHunter-Wsdot

**Comment by ReedHunter-Wsdot** [comment]
I have doubled the scale at which collectable features can be viewed and selected: 1:10,000 => 1:20,000.  I've also made the Location button more forgiving if they tap it while out to as far as 1:20,000.  If they're out further it will put them to 1:10,000.  The basemap will still swap out what kind of road they see when they're beyond 1:10,000.  Let me know if (1) you want the zoom level relaxed even further, say to 1:30,000 or 1:40,000, and (2) if you want the basemap to keep showing the more detailed roads out to that level too.

**Comment by ReedHunter-Wsdot** [comment]
If they want it viewable from higher up, we can reopen this.
