### ISSUE TITLE
Budget Tool: Appropriation Allotment User Rights Issue

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1101]
Looks like general users cannot edit the text boxes under Appropriation Allotment under region tabs (not using monthly budget) even when the Control Totals tab is locked down. General users should have the ability to edit their region appropriation allotments, like Admins, when Control Totals budget is not locked.

**Comment by brianblood** [comment]
We’re talking about this section, right?

![appropriations](https://user-images.githubusercontent.com/15752548/44495947-ed007b80-a626-11e8-8bca-57b6b8c845ef.PNG)

**Comment by kechinn** [comment]
Yup, that section.

**Comment by brianblood** [comment]
Fixed!
