### ISSUE TITLE
Workaround slow map load of 100th milepost layer

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1103]
Adding this issue to track progress on what we talked about August 20 - that the new Sdk is slow at loading the 100th milepost layer.  This makes Hats startup take up to 30 seconds.

So some updates on this:
 - This is a thing on older 2015 iPads only.  Startup is quick on the 2017 iPads.  
 - I have updated the next beta code so that the 100th mileposts layer is added 5 seconds after the map finishes loading.  

Please test in the next beta, and let me know if you see the lag in any devices other than the Air 1 iPads.

Once the milepost layer starts to load, there are 13 seconds on the Air 1 where you can still smoothly pan/zoom, but the map isn't responding to queries, so it just shows you the cache of what was in the map before.  New locations only slowly fill in because it's busy.  

The other big symptom is if you use the identify button during those 13 seconds, the right panel doesn't open until the milepost layer finishes.

There is no workaround to that on the old devices - when the milepost layer is being loaded, the map will be busy with that task and won't respond to queries until it's done.

**Comment by jhudsonWA** [comment]
@kechinn @tangoai @joeschmit @PeterBurkhard FYI

**Comment by jhudsonWA** [comment]
@kechinn @tangoai @joeschmit @PeterBurkhard When you all were getting slow downs were those on Air 1s by chance or latest deployed devices?

**Comment by jhudsonWA** [comment]
I should also add "There is no workaround to that on the old devices". We have not tried splitting up the layers or vector based. Really comes down to if the only devices we have seen this slow down on is truly only the Air 1s.

**Comment by ReedHunter-Wsdot** [comment]
The latest update appears to resolve the problem on the 37 air 1s and somewhere between 50 and 100 air2s.
