### ISSUE TITLE
Budget Tool: 4/6 Digit Org Regional Report Viewing Enhancements

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1105]
~~Can you blow this page up a bit, make the font larger, please? I think scrolling is fine. Just want to get it to the point that squinting and zooming page view is not necessary:) An export option would be awesome too (this might be more like version 2 since we're low on time).~~

![image](https://user-images.githubusercontent.com/16247034/45045933-6fc30680-b029-11e8-8323-74d06df42af3.png)

~~Also, is it possible to add a back button from this page?~~

**Comment by kechinn** [comment]
Actually, disregard above. So, I spoke with Andrea on this and she said we don't need to see this page at all? She said that you mentioned this page only shows if there is no budget set for a 4 or 6 digit org. If that's the case, rather than load these pages at all, can you set it so it just says something like "No report available for this Org" from the main regional report page?

**Comment by brianblood** [comment]
This page has been discarded in favor of an excel spreadsheet of the same data.  If a budget has not been created, it will return zeros for all budget fields.
I also added a bit of formatting to the other regional reports for readability.
