### ISSUE TITLE
Budget Tool: Report Enhancement

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1116]
Request by user for reports: Would it also be possible to include month on the report selection. Put yellow high-light text next to the Month box, or add text with number?

![image](https://user-images.githubusercontent.com/16247034/46292786-9f8cfd80-c546-11e8-901e-237b6b84b0b6.png)x
![image](https://user-images.githubusercontent.com/16247034/46293269-d7e10b80-c547-11e8-8055-c8b4563df6cf.png)

**Comment by brianblood** [comment]
Done.
