### ISSUE TITLE
AVL Web Map Enhancement

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1119]
For trucks applying and dropping liquids and material, remove the popup box language "per lane mile" like Gal/lane mile, and just show the amount and the unit (e.g. lbs, gal). This is to clear confusion for cases where different types of trucks apply material to multi-lanes or for cases where the same trucks switch from winter season materials to spring/summer herbicide, which uses different units than lane mile (e.g. acres).
![image](https://user-images.githubusercontent.com/16247034/46745674-61888b80-cc62-11e8-8628-9dea341d6e39.png)

**Comment by jhudsonWA** [comment]
Deployed with HATS Web 6.9
