### ISSUE TITLE
Delete all Org = 333333 Records in Prod

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1129]
Please nuke all the records in prod where org = 333333

**Comment by jhudsonWA** [comment]
Done

**Comment by joeschmit** [comment]
Thanks

- Joe

On Oct 18, 2018, at 16:00, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1129<https://github.com/WSDOT/HATS/issues/1129>.
