### ISSUE TITLE
AVL Report: Input Time Report

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1130]
Report request for AVL, export to excel only, based on the query developed last winter:

Filter by: Region - Area - Truck ID
Pick input (front plow, wing plow, belly plow, broom etc)
Pick date/time start - end
Go

**Comment by jhudsonWA** [comment]
@joeschmit Can you send this query back and we can make a report out of it? Might be easier than having me search through emails to find it.

**Comment by joeschmit** [comment]
`USE MaintenanceAVL
GO

Declare @StartDate datetime2
Declare @EndDate datetime2
Declare @MaintenanceVehicleNumber varchar(16)

Set @StartDate = '12/1/2017'
Set @EndDate = '3/14/2018 11:59:59 PM'

Set @MaintenanceVehicleNumber = '06E1076' -- Set to NULL For ALL

Create Table #StagingData (
RowId int identity(1,1),
MaintenanceVehicleNumber varchar(16),
LogDate datetime2(7),
BitValue bit
)

Create Table #Results (
MaintenanceVehicleNumber varchar(16),
TotalHoursWithPlowDown decimal(10,2)
)


-- To Calculate Time For A Different Value Change The 3rd Column 
-- And Make Same Change To The Where Statement where it verifies at least one positive record to ignore cases where it was off the whole time

-- Possible Values:

-- LeftWingPlowState, UnderbellyPlowState, RightWingPlowState, FrontPlowState
-- MainBroomState, LeftBroomState,RightBroomState, SprayerState, FlusherState

insert into #StagingData ( MaintenanceVehicleNumber, LogDate, BitValue)
select MaintenanceVehicleNumber, LogDate, FrontPlowState  -- Change Column Name Here To Calculate Different Column 
from EquipmentSensorRecord 
where StateRoutePointFound = 1
and (MaintenanceVehicleNumber = @MaintenanceVehicleNumber OR @MaintenanceVehicleNumber IS NULL)
and LogDate between @StartDate and @EndDate
and MaintenanceVehicleNumber in   
      (select distinct MaintenanceVehicleNumber
       from EquipmentSensorRecord
       Where StateRoutePointFound = 1
        and LogDate between @StartDate and @EndDate
        and FrontPlowState = 1) -- Change Column Name Here To Calculate Different Column 
order by MaintenanceVehicleNumber, LogDate

CREATE NONCLUSTERED INDEX idx_StagingDataRowId ON #StagingData (RowId);

--select * from #StagingData order by RowId

Declare @CurrentRow int = 1
Declare @MaxRow int 

select @MaxRow = max(RowId)
From #StagingData

Declare @CurrentMaintenanceVehicleNumber varchar(15)
Declare @PreviousMaintenanceVehicleNumber varchar(15)
Declare @CurrentBitValue bit
Declare @PreviousBitValue bit = 0
Declare @CurrentLogDate datetime2(7)
Declare @PreviousLogDate dateTime2(7) = NULL
Declare @TotalSecondsWithPlowDown int = 0

While @CurrentRow <= @MaxRow 
BEGIN

select @CurrentMaintenanceVehicleNumber = MaintenanceVehicleNumber, @CurrentBitValue = BitValue, @CurrentLogDate = LogDate
from #StagingData
where RowId = @CurrentRow

if @CurrentMaintenanceVehicleNumber IS NOT NULL 
BEGIN

    -- NEW Vehicle Found
    IF @CurrentMaintenanceVehicleNumber <> @PreviousMaintenanceVehicleNumber OR @PreviousMaintenanceVehicleNumber IS NULL
    BEGIN

        IF @TotalSecondsWithPlowDown <> 0
        BEGIN

        INSERT INTO #Results (MaintenanceVehicleNumber,TotalHoursWithPlowDown)
        SELECT @PreviousMaintenanceVehicleNumber, (convert(decimal(10,2),@TotalSecondsWithPlowDown)/60)/24
        
        END

        Set @PreviousLogDate = NULL
        Set @PreviousBitValue = 0
        Set @TotalSecondsWithPlowDown = 0

    END
    ELSE 
    BEGIN

        -- Calculate time since last value

        Declare @CalculatedDateDiffInSeconds int

        IF (
            (@CurrentBitValue = 1 AND @PreviousBitValue = 0) OR -- Going from off to on 
            (@CurrentBitValue = 0 AND @PreviousBitValue = 1) OR -- Going from on to off
            (@CurrentBitValue = 1 AND @PreviousBitValue = 1)    -- Going from on to on
           )
           And @CurrentLogDate is not null and @PreviousLogDate IS NOT NULL
        BEGIN

            Set @CalculatedDateDiffInSeconds  = DATEDIFF(SECOND, @PreviousLogDate, @CurrentLogDate)

            IF @CalculatedDateDiffInSeconds <= 1800 -- 30 minutses 
            BEGIN
                Set @TotalSecondsWithPlowDown = @TotalSecondsWithPlowDown + @CalculatedDateDiffInSeconds
            END

        END

    END

    SET @PreviousMaintenanceVehicleNumber = @CurrentMaintenanceVehicleNumber
    SET @PreviousBitValue = @CurrentBitValue
    SET @PreviousLogDate = @CurrentLogDate
END

SET @CurrentRow = @CurrentRow + 1

END

-- Insert final vehicle 

    IF @TotalSecondsWithPlowDown <> 0
        BEGIN

        INSERT INTO #Results (MaintenanceVehicleNumber,TotalHoursWithPlowDown)
        SELECT @CurrentMaintenanceVehicleNumber, (convert(decimal(10,2),@TotalSecondsWithPlowDown)/60)/24
        
        END

select * from #Results

drop table #Results
drop table #StagingData`

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
