### ISSUE TITLE
AVL Report: Materials Usage Report

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1131]
AVL Report: Materials Usage Report, export to web is fine, no Excel.

Based on the Seasonal/run totals columns for each material type
Filter by Region - Area - Truck ID
Material Type (SolidMaterialName, LiquidMaterialName, PrewetMaterialName)
Start Date/Time - End Date/Time
Go!

**Comment by PeterBurkhard** [comment]
@jhudsonWA  any chance you can bump this now that 4.0 is out?

**Comment by jhudsonWA** [comment]
Let me look back into it. Ran into some missing/weird data last time I looked at it, but I know the vendor made some changes.

**Comment by joeschmit** [comment]
bump? Just doing the prewinter housekeeping, if its a bugger we can hold off for now...

**Comment by jhudsonWA** [comment]
Let’s hold off until we get the team filled out. I thank that will help. My position posts tomorrow or Thursday so soon.

Joshua Hudson
Applications Modernization Manager, Enterprise Applications
[cid:image001.png@01D496DE.F3223B40]
hudsonj@wsdot.wa.gov<mailto:hudsonj@wsdot.wa.gov> | 360.705.7778

**Comment by jhudsonWA** [comment]
All positions filled, so lets get this done. Assigning to @VinceRanger

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
