### ISSUE TITLE
HATS Web: Move to https://remoteaccess.wsdot.wa.gov/

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1152]
Lets plan for a web move to the www sometime in 2019, please.

**Comment by jhudsonWA** [comment]
You hate me. :) Alright, let's do this. Would be http://remoteapps.wsdot.wa.gov but yes. We can discuss.

**Comment by joeschmit** [comment]
You’re cool so “sometime” in 2019. Technically you planted this idea bub…

**Comment by jhudsonWA** [comment]
You are not wrong. It was my idea. But I didn't know you all listened to me ;P

**Comment by jhudsonWA** [comment]
This is a work in progress. If the Azure beta progresses to production this be implemented. Something like hats.wsdot.wa.gov probably.

**Comment by jhudsonWA** [comment]
Complete.
