### ISSUE TITLE
HATS Web Activities Report Bug

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1155]
Example: Feature Activities Report > Guardrail > Activity Type Assessment > Quick Dates Current Month, export all with attributes, on export any of the questions that have more than one answer selected such as "What components are damaged?" are showing blank in the Excel output.

**Comment by joeschmit** [comment]
Bump, I kinda need this fixed ASAP

**Comment by jhudsonWA** [comment]
Sorry this one slipped past us somehow. I’m on it. It will be fixed this morning

Sent from my iPhone

On Nov 1, 2018, at 7:38 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


Bump, I kinda need this fixed ASAP

**Comment by jhudsonWA** [comment]
Fixed. This report seems slow if there is large amounts of data, so I'll work next week on optimizing it some more.
