### ISSUE TITLE
HATS Beta 4.0 B10: Symbology

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1158]
Remove text from Other types: Salt, Liquid and Sand Storage Facility. Seems like new SDK doesn’t accept that text right now, so might as well remove it so it looks okay. 
[
![1354a6d4-39da-4581-a775-90d94d91273c](https://user-images.githubusercontent.com/16247034/47530831-90a51c80-d860-11e8-92eb-664595979879.jpeg)
](url)

**Comment by ReedHunter-Wsdot** [comment]
Esri has a bug tracking number on this, so a future Sdk will have this fixed.

Josh, I’ve pushed out an updated feature service for this.  Can you generate a new offline geodatabase?  Sync should still work for the existing offline features map everyone has, but they’ll need a new file to redownload before the new symbols show up.

-Reed

**Comment by jhudsonWA** [comment]
Yep, on it.

On Oct 25, 2018, at 3:10 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Esri has a bug tracking number on this, so a future Sdk will have this fixed.

Josh, I’ve pushed out an updated feature service for this. Can you generate a new offline geodatabase? Sync should still work for the existing offline features map everyone has, but they’ll need a new file to redownload before the new symbols show up.

-Reed

**Comment by jhudsonWA** [comment]
This is done by the way

On Oct 25, 2018, at 3:10 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Esri has a bug tracking number on this, so a future Sdk will have this fixed.

Josh, I’ve pushed out an updated feature service for this. Can you generate a new offline geodatabase? Sync should still work for the existing offline features map everyone has, but they’ll need a new file to redownload before the new symbols show up.

-Reed

**Comment by jhudsonWA** [comment]
This finished last night by the way ☺

**Comment by ReedHunter-Wsdot** [comment]
The text is confirmed removed.
