### ISSUE TITLE
HATS Beta 4.0 B10: TOC Other Category

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1159]
Is showing multiple Avalanche Path layers.
![c87f34df-e239-4772-b010-07f466bbcfdb](https://user-images.githubusercontent.com/16247034/47531025-35bff500-d861-11e8-9f3f-ee81e8fbc105.png)

**Comment by ReedHunter-Wsdot** [comment]
I’m seeing that too.  I’ll dig into what’s up.

-Reed

**Comment by ReedHunter-Wsdot** [comment]
It was a side effect from when I fixed the layer ordering between operational layers and basemap layers.  A fix is now checked in.
