### ISSUE TITLE
HATS Beta 4.0 B10: Shields

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1161]
@ReedHunter-Wsdot I can’t remember if this was discussed. Is there a way to fit text inside the new SDK route shields? 
![98bbccd6-9b94-42d2-8cf6-b4dfd2c16301](https://user-images.githubusercontent.com/16247034/47531620-fc888480-d862-11e8-88b5-9638f5ed1b73.jpeg)

**Comment by ReedHunter-Wsdot** [comment]
It's worth a try since the Sdk is all new.  It will take me all of an hour or two to find out.

**Comment by ReedHunter-Wsdot** [comment]
The new Sdk allows stretching of the shield symbols.  I had to change the ovals for the state route shields to be less pointed for some route names that are longer.  
![pointed1](https://user-images.githubusercontent.com/2709194/49044457-ae78e080-f182-11e8-8b72-9b821611e472.png)
![rounded](https://user-images.githubusercontent.com/2709194/49044462-b042a400-f182-11e8-8a00-6fdff0bd783b.png)
