### ISSUE TITLE
Budget Tool: Monthly Budget Page UI

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1164]
Another user request. Wondering if it would be possible to "freeze" beginning columns (Object, Description, Staff Months/FTEs, etc.) for when you are scrolling across screen? Didn't think about this earlier, but makes sense, easy to lose track of what row you are on.

**Comment by brianblood** [comment]
Good idea.  I had to rework the way the headers work to get it functioning, but it is in QA now.  You will need to refresh your cache.
