### ISSUE TITLE
HATS Beta 4.0 B10: GPS Issues

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1165]
When adding a new feature, I had to tap and add a feature to the map before it would let me use the Collect GPS button (it should allow that from the start). In addition to that, once you hit the Collect GPS button, you can't use it again. So, you wouldn't be able to collect a vertices in a line and walk some and collect another vertices.

**Comment by ReedHunter-Wsdot** [comment]
Hmm.  That's an old bug that I fixed a while back.  I suspect a merge failure.
I'll look at that.

Thanks @kechinn

**Comment by ReedHunter-Wsdot** [comment]
I see what I'm doing.  I need to use some "replaceGeometry" calls instead of the "insertVertexAfterSelectedVertexWithPoint" calls I'm making now.  The first call to collect the Gps is working, but it's not accepting the 2nd collected Gps point.  

I should be able to fix this on Monday.

**Comment by ReedHunter-Wsdot** [comment]
The fix for this is checked in and will be part of the next beta.
