### ISSUE TITLE
Resize and Rotate Landscape Maintenance Option is Back

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1169]
![img_0529](https://user-images.githubusercontent.com/15268732/47799577-cd9d6300-dce7-11e8-8e7c-6166b1c7a53c.PNG)

**Comment by ReedHunter-Wsdot** [comment]
Just to document this, Pete, Keisha and I have so far been unsuccessful in making this trigger again.  In case someone comes across steps to reproduce this bug, please keep an eye out.

**Comment by PeterBurkhard** [comment]
While adding a landscape maintenance feature single tap part of the line. Still doing it for Oai and I.
![rotate](https://user-images.githubusercontent.com/15268732/48099573-e4a2f000-e1d4-11e8-8bca-d87478366f9a.gif)

**Comment by ReedHunter-Wsdot** [comment]
Pete you are awesome.  The step I was missing was to tap on the line instead of a vertex or mid point.  I was able to reproduce the problem.

**Comment by ReedHunter-Wsdot** [comment]
found and fixed this.

**Comment by ReedHunter-Wsdot** [comment]
No, I just checked in the fix this morning.  It will be part of the next beta.

**Comment by jhudsonWA** [comment]
I'll create a beta 13 this afternoon in case other things make the cut.
