### ISSUE TITLE
HATS 4.0 B11: Dashed Lines With Update Location

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1172]
Trace dashed lines for moving vertices only shows when you directly tap and hold on feature. If you tap and hold elsewhere, it will still move selected vertex but without guide lines. I like the dashed lines, useful tool to help guide placement if this is possible enhancement.

**Comment by ReedHunter-Wsdot** [comment]
I'll see if that's an option. If not then I'll file an enhancement request with Esri.

**Comment by ReedHunter-Wsdot** [comment]
This sadly is something behind the curtain of the Sdk.  I have posted an enhancement request with Esri.
