### ISSUE TITLE
HATS 4.0 B11: Bug With Adding Polygon Features

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1176]
When adding a new polygon feature, you cannot tap with finger on map to place vertices, but you can hit collect GPS (although you can’t see anything being drawn). Once you get to the prerequisite three vertices, you can hit save feature. Once you saved attributes, the polygon shows up on map.

**Comment by ReedHunter-Wsdot** [comment]
This sounds like the manifestation of a bug I just fixed that will be part of the next build.

My steps to trigger the problem were to go back and forth between adding new features and editing existing features.
1) Add a new feature.  I doesn't matter whether it's a point, line, or polygon.
2) identify and then edit an existing feature.  Cancel out of the editor.
3) Try to add a new feature.

  When doing this I quickly saw results like you described above: 
- vertices were not visible
- tapping on the map produced no visible result.
- the undo/redo environment seemed to respond when I used [+collect GPS].

Please test again and if you don't see the bug any longer, please close.
Thanks

**Comment by jhudsonWA** [comment]
I'll create beta 12 today. Just want to make sure there aren't any big ones we missed from the testing last week.

**Comment by jhudsonWA** [comment]
Beta 12 created!
