### ISSUE TITLE
Auto Center map mode no longer works

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1180]
When you select Auto Center, Hats pops right back into Manual Pan map mode.

I traced the code, and it does switch to Auto Center correctly.   That code is still fine.  It stays that way for a fraction of a second, and then something is immediately reverting it back to manual pan.  

I have an event handler that triggers every fraction of a second -- I use it at startup.  Watching this right after I switch to auto center, only once is auto center preserved during that event.  The next time it triggers something has switched that back to manual pan.  

I'll keep rolling back to older versions of Hats until this is shown to stop, then I'll find out what changes elsewhere in Hats are triggering this.

**Comment by jhudsonWA** [comment]
IOS 11 vs 12 differences?

Sent from my iPhone

On Nov 2, 2018, at 3:07 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


When you select Auto Center, Hats pops right back into Manual Pan map mode.

I traced the code, and it does switch to Auto Center correctly. That code is still fine. It stays that way for a fraction of a second, and then something is immediately reverting it back to manual pan.

I have an event handler that triggers every fraction of a second -- I use it at startup. Watching this right after I switch to auto center, only once is auto center preserved during that event. The next time it triggers something has switched that back to manual pan.

I'll keep rolling back to older versions of Hats until this is shown to stop, then I'll find out what changes elsewhere in Hats are triggering this.

**Comment by ReedHunter-Wsdot** [comment]
Possible iOS 11 v 12, but would have to be in conjunction with the new Esri sdk.  Prod Hats with the old Oct 2015 sdk still auto centers using the same iPad on iOS 12.

**Comment by ReedHunter-Wsdot** [comment]
I'm leaning now to an iOS 11 v 12 cause for this one - this code was working fine until last week.  When you pick Auto Center, one of the pieces of that is to rotate the map to face north in case you were just using Navigation or Compass modes.  It's that rotation code that suddenly was pushing the map from Auto Center to manual pan.  That meant the map was in auto center for just a fraction of a second.

I resolved this by switching right back to auto center in the rotation's completion block.  This is checked in and will be part of the next build.

**Comment by jhudsonWA** [comment]
nice. @kechinn If you can test this fix when released on both iOS 11 and iOS 12 that would be great.

**Comment by kechinn** [comment]
Tested on both iOS versions and works:)
