### ISSUE TITLE
HATS 4.0: Identify Culvert Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1183]
Would it be possible to automatically update contents of the Identify tool after updating a culvert point to a culvert line feature, or turn it off at least?

Right now, after updating to a line, it still shows a culvert point in Identify and you can tap but not highlight. It allows you to hide, edit, do an activity, etc. If you try to update feature, it thinks it is still a point and when you tap save it crashes the app.

![52a2cffe-485c-4364-81f3-366cac9a227b](https://user-images.githubusercontent.com/16247034/48144750-49f2f180-e266-11e8-9efe-dc0f4aad5ae3.png)

**Comment by ReedHunter-Wsdot** [comment]
This is another symptom of #1076.  The identify results are cached, and the cache entries are not updated when you edit them.  Once I update the editing code to not just update on the map but also in the identify results cache, this will be fixed.
