### ISSUE TITLE
HATS 4.0 B12: iOS 12 Add/Update Spatial Issues

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1185]
Updated to iOS 12 and when I attempt to add a new feature of update existing feature, I cannot see any vertices. Tried same thing with iOS 11 on B12 and had no issues so far.

Steps for existing feature: 
1. Identify feature
2. Tap Edit Feature Location
3. Tap Edit Map Location
4. Tap on screen and get response (not collecting Lat/Long UNLESS you had Added a new feature beforehand)

Steps from adding a new feature:
1. Add new feature
2. Start sketch
3. Tap on screen to set vertices (not visible, but you can see the Lat/Long changing)
4. Save and then you can see changes made.
5. Now that you've added a feature, if you go back to update existing feature, you can now see Lat/Long changing but without seeing vertices until after saving changes.

**Comment by ReedHunter-Wsdot** [comment]
I followed these steps on my iPad and unfortunately did not encounter this problem.
Following these steps, are you able to reproduce the problem on another iPad?
If you restart Hats on your current iPad, do these steps still trigger the problem?

**Comment by kechinn** [comment]
I closed and reopened app and was able to see vertices, but once I did a sync, the issue came back.

**Comment by ReedHunter-Wsdot** [comment]
Strangely this is only if you edit existing features, not if you add new features.
Also if you sync right away before opening the editor, that's not enough to reproduce this.  You have to open the editor, sync, and then edit again before the bug shows.

Steps ...
1) identify and then map edit a feature
2) don't bother making edit changes, just cancel the edit.
3) sync
4) map edit the feature

result: the sketch editor won't appear.

**Comment by ReedHunter-Wsdot** [comment]
I wasn't clear in my steps above about this, but you don't have to edit the same feature both times to trigger this, and it doesn't matter the geometry type of the features.

**Comment by kechinn** [comment]
So, I thought I had closed and reopened HATS beta on my other two iPads still on iOS 11 today, but maybe it slipped my mind...Because now I'm seeing the same issue on those ones as well, so I guess it is totally unrelated to iOS versions.

**Comment by jhudsonWA** [comment]
Thanks @kechinn. That helps. I was starting to go crazy thinking we had a ton of iOS 12 issues. Not much changed with that release from a development area so it shouldn't be causing many differences.

**Comment by ReedHunter-Wsdot** [comment]
I've checked in a fix for this that will be in the next beta.  When you have a chance to test the next build, please confirm this is fixed for you too.
