### ISSUE TITLE
(iOS) (HATS Web) Ability to have files as attributes

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#119]
Ability to have files as attributes, photos/pdf's.  May require breaking this down by region/area due to size limitations.

**Comment by jhudsonWA** [comment]
We talked about pictures as attributes in our last meeting. One idea was create on iPad and view on web. Pictures would not sync down to the device (size constraints) @joeschmit something for iOS 3.0?

**Comment by sheppamwsdot** [comment]
Duplicate
