### ISSUE TITLE
HATS AVL Raw Data Report SRMP Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1192]
AVL Raw Data Report is not exporting State Route and Milepost info. Here's an example of active truck now:

![image](https://user-images.githubusercontent.com/16247034/48730711-0bf3b700-ebf0-11e8-8958-c5365ac944ce.png)
![image](https://user-images.githubusercontent.com/16247034/48730742-1ca42d00-ebf0-11e8-8275-9d985ee1e8ea.png)

**Comment by jhudsonWA** [comment]
Thanks!

Sent from my iPhone

On Nov 19, 2018, at 11:43 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


AVL Raw Data Report is not exporting State Route and Milepost info. Here's an example of active truck now:

[image]<https://user-images.githubusercontent.com/16247034/48730711-0bf3b700-ebf0-11e8-8958-c5365ac944ce.png>
[image]<https://user-images.githubusercontent.com/16247034/48730742-1ca42d00-ebf0-11e8-8275-9d985ee1e8ea.png>

**Comment by jhudsonWA** [comment]
Leif, Can you check that the MaintenanceAVL Broker is all good?

Sent from my iPhone

On Nov 19, 2018, at 11:43 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


AVL Raw Data Report is not exporting State Route and Milepost info. Here's an example of active truck now:

[image]<https://user-images.githubusercontent.com/16247034/48730711-0bf3b700-ebf0-11e8-8958-c5365ac944ce.png>
[image]<https://user-images.githubusercontent.com/16247034/48730742-1ca42d00-ebf0-11e8-8275-9d985ee1e8ea.png>

**Comment by jhudsonWA** [comment]
I believe this was resolved and the task was never closed.
