### ISSUE TITLE
Collect GPS Stops working if you delete the GPS Collected Vertex then try and Collect GPS Again.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1195]
![collectgpsstopsworking480](https://user-images.githubusercontent.com/15268732/49114496-32979a80-f24d-11e8-8531-2d10763ab5bc.gif)

**Comment by ReedHunter-Wsdot** [comment]
The +Collect GPS will work again if you wait a moment and/or walk a few feet over.  It's blocking you from using the *exactly* identical (down to sub centimeter) point twice, guarding against duplicate vertices ever being entered for lines or polygons.

A fix is checked in for 4.0 to exempt point features from this protection.  

A more sophisticated check against duplicates will be to sift through all vertices of your sketch when you tap the +Collect GPS, confirming that vertex isn't already there somewhere.

**Comment by jhudsonWA** [comment]
Created new task to track the "sophisticated check"

**Comment by jhudsonWA** [comment]
@kechinn "Actually, one more GPS thing...I thought the collect gps thing was solved, but it looks like if you edit an existing point feature, collect gps, hit delete vertex, then it won’t let you hit collect gps again (unless you tap restart)"

**Comment by kechinn** [comment]
Edited existing point feature and experienced this even though I moved. I hit collect GPS, tapped delete vertex button, then couldn't collect GPS anymore. Ah...Josh is too fast, beat me to it.

**Comment by PeterBurkhard** [comment]
See I'm not crazy...

**Comment by jhudsonWA** [comment]
I don't see why this proves THAT either way...

**Comment by ReedHunter-Wsdot** [comment]
The fix for this is checked in, and will be part of the next beta.
