### ISSUE TITLE
LastUsedDate for Top 5 Used Other Activies

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1197]
It is currently Alphabetical.
<img width="1024" alt="top 5 most used" src="https://user-images.githubusercontent.com/15268732/49167431-2f9eb780-f2ea-11e8-94fc-9e0ca12f2a8c.png">

**Comment by jhudsonWA** [comment]
Checked into dev. Will be in beta/rc for 4.1. Still uses total count (it is a top list after all), but if several have the same count, then they use LastUsedDate. So in your example after this change it would be 1,2,3,4,5 as it should be.

Dates will be empty on upgrade, but as you use it the dates get set from launch on out.
