### ISSUE TITLE
Highlight table cell in identify results table as grey when auto selected. Related to #816

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1198]
See #816 for details.

**Comment by PeterBurkhard** [comment]
![tapfrustration320](https://user-images.githubusercontent.com/15268732/49170378-d5edbb80-f2f0-11e8-8475-c155d91c39ce.gif)

**Comment by ReedHunter-Wsdot** [comment]
Default highlighted cell will show up as selected/highlighted in the identify results tableview in the next beta release.
