### ISSUE TITLE
Switch from Fabric to Firebase for Analytics

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1199]
Fabric is getting sunsetted by Google in 2019. Migrate over to their supported Firebase platform. Crashlytics support is getting moved there.

**Comment by jhudsonWA** [comment]
Support has landed in branch 'firebase'

**Comment by jhudsonWA** [comment]
Merged into master for 4.1. All screens have been given a screen name and all "Fabric Events" are now Firebase Events.

**Comment by PeterBurkhard** [comment]
Bye Fabric...
![image](https://user-images.githubusercontent.com/15268732/49398364-ee941200-f6f2-11e8-9002-5d97aebfac81.png)

**Comment by jhudsonWA** [comment]
It will still work for a while longer :) The "events" tracking like Sync complete will be gone and moved over but the other analytics will live for a while longer.
