### ISSUE TITLE
Enhancement duplicate point detection on lines and polygon collection. 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1200]
See #1195 for details. 

"A more sophisticated check against duplicates will be to sift through all vertices of your sketch when you tap the +Collect GPS, confirming that vertex isn't already there somewhere."

**Comment by ReedHunter-Wsdot** [comment]
This now checks the edit sketch geometry for duplicates rather than looking at what was last collected and just assuming it's still part of the edit sketch.
