### ISSUE TITLE
Search Filter, Feature Activity Records by Attributes 

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1201]
Example; Bridge guys are trying to search asbestos records for a bridge number which is located in attributes for that HATS feature. 

<img width="2045" alt="search attributes" src="https://user-images.githubusercontent.com/15268732/49172508-20256b80-f2f6-11e8-8a67-23f7b521f295.png">

**Comment by sheppamwsdot** [comment]
Duplicate
