### ISSUE TITLE
Creating New Landscape Maintenance Reference Feature Error converting data type nvchar to geometry.  

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1203]
![image](https://user-images.githubusercontent.com/15268732/49177149-52889600-f301-11e8-9f96-e2fba8620db8.png)

![image](https://user-images.githubusercontent.com/15268732/49177082-2bca5f80-f301-11e8-9906-35dc33825bbb.png)

**Comment by ReedHunter-Wsdot** [comment]
I'll be looking for a way to check for self intersecting polygon rings before allowing an edit to be saved.  :)

**Comment by ReedHunter-Wsdot** [comment]
This is now fixed.  If you make a new polygon like this or modify an existing one to become like this, the save button becomes greyed out.
