### ISSUE TITLE
Delete Feature blocks map feature download from registering without app restart

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1204]
Current workaround: "1. Delete Feature. 2. Redownload (Register fails). 3. Force Quit App. 4. Prompted to redownload and do so."

**Comment by ReedHunter-Wsdot** [comment]
Status update on this...

Registration of a redownload Hats features database is no longer blocked when you ...
- identify a Hats feature.  
- add a new Hats feature
- modify a Hats feature
- delete a Hats feature
- map sync
- search for a feature

I have rewired the Map Search, Map Identify, feature update, feature delete, and feature creation code to all store their data references in one place so it can all be released when it's time to redownload a new features map.  

I'm retrofitting how basemap identifies work to be compatible with the new structure for Hats features. I get back from vacation on Thursday, January 3.  I expect the basemap retrofit to be quick, so I'm thinking this will be checked in and ready to test by the beginning of the week after, January 7.

**Comment by ReedHunter-Wsdot** [comment]
basemap identifies are working again.
I have found another problem where if I search for a feature, start editing, and then cancel the edit, the edit buttons UI still remains.  It should instead go back to the listing for the found feature.  I should be able to fix this tomorrow (Friday, January 4).

**Comment by ReedHunter-Wsdot** [comment]
Problem is fixed.  I'll finish merging on Monday, and then will check this in for confirmation testing.

**Comment by ReedHunter-Wsdot** [comment]
The fix for this is now checked in.  new features, modified features, deleted features, searches, and syncs all tested out ok for no longer blocking map features database redownloads/registration.
