### ISSUE TITLE
Ortho Photo not Showing up in Table of Contents

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1206]
As a result Orthos can not be toggled off.
![orthophotosdonotshowupintableofcontents](https://user-images.githubusercontent.com/15268732/49188858-09e0d500-f321-11e8-9ee2-4e17dd800452.gif)

**Comment by ReedHunter-Wsdot** [comment]
Fixed this.  Orthos will be listed in the Toc once again in the next beta release.
