### ISSUE TITLE
(HATS Web) (iOS) Is there a way to get mile post on the map that the pics are associated with?

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#121]
Device Name: NWC0858028 
Device Model: iPad Air 
Device System Version: 8.4.1 
Application Version: HATS-iOS 1.1.1 
Name: Dominick Zimmerman 
Location: 47.63973617553711,-122.1943969726562
Has Attachments: False 

Feedback: Is there a way to get mile post on the map that the pics are associated with? Please feel free to contact me if you have any questions. Thank you. 

Details: View Details

**Comment by jhudsonWA** [comment]
Need more details.

**Comment by jhudsonWA** [comment]
I still don't understand this one. Close down?

**Comment by joeschmit** [comment]
Think they wanted to know which SRMP the photo was taken at…close.
