### ISSUE TITLE
Line Feature Spatial Geometry Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1216]
We got a call this morning about a spatial geometry sync error. I played around with the line feature and re created the error. If you edit the spatial location of a line feature and attempt to tap and hold and drag a blue vertex without tapping to choose it, and the red vertex is off the visible screen, the line won’t directly draw from the direction of the red vertex, but wrap around the map from the opposite direction.

![6d90195d-98c1-477c-b90b-ae835261de8e](https://user-images.githubusercontent.com/16247034/49746648-7b405200-fc56-11e8-9e8b-7399c07c691c.png)
![82e6e9bc-ff74-494c-abd3-e8ff3a6d2336](https://user-images.githubusercontent.com/16247034/49746649-7b405200-fc56-11e8-89b1-391d88c20d52.png)
![3493f560-de6c-4c66-95d8-35b6e746e1d5](https://user-images.githubusercontent.com/16247034/49746650-7bd8e880-fc56-11e8-94ea-4cda78e5a273.png)
![f26e87e5-16c0-483b-a33f-7cf98c52ce71](https://user-images.githubusercontent.com/16247034/49746736-ac208700-fc56-11e8-99db-880a8085f718.gif)

**Comment by jhudsonWA** [comment]
24901 miles. Amazing. :)

On Dec 10, 2018, at 8:38 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


We got a call this morning about a spatial geometry sync error. I played around with the line feature and re created the error. If you edit the spatial location of a line feature and attempt to tap and hold and drag a blue vertex without tapping to choose it, and the red vertex is off the visible screen, the line won’t directly draw from the direction of the red vertex, but wrap around the map from the opposite direction.

[6d90195d-98c1-477c-b90b-ae835261de8e]<https://user-images.githubusercontent.com/16247034/49746648-7b405200-fc56-11e8-9e8b-7399c07c691c.png>
[82e6e9bc-ff74-494c-abd3-e8ff3a6d2336]<https://user-images.githubusercontent.com/16247034/49746649-7b405200-fc56-11e8-89b1-391d88c20d52.png>
[3493f560-de6c-4c66-95d8-35b6e746e1d5]<https://user-images.githubusercontent.com/16247034/49746650-7bd8e880-fc56-11e8-94ea-4cda78e5a273.png>
[f26e87e5-16c0-483b-a33f-7cf98c52ce71]<https://user-images.githubusercontent.com/16247034/49746736-ac208700-fc56-11e8-99db-880a8085f718.gif>

**Comment by ReedHunter-Wsdot** [comment]
That's the distance of Earth's circumference.  This isn't in Esri's list of known bugs, so I'll be passing this along.

I have an idea for a code workaround for now, but it's a little intrusive because step 2 moves the map around outside the user's control:
1. detect a super long line, 
2. force the map extent to center on the vertices and zoom out until they'll all in view, 
3. undo the latest new vertex that made the super long line around the world, and then 
4. redo the latest vertex, hopefully with a line that doesn't go all that distance.
5. If it makes another world spanning line, ignore it at that point to avoid an infinite loop back to step 1.

I'll look at whether a zoomed out undo/redo avoids the world circumference line vs whether you have to re-add the last vertex.

**Comment by jhudsonWA** [comment]
Can we just do 1. Detect a super long line and not let them save it?

**Comment by ReedHunter-Wsdot** [comment]
That we can do easily.

**Comment by jhudsonWA** [comment]
I'm just thinking detect a long line (@kechinn could define what long means) and then throw up a message that a single line can not be over x miles with some language for them to revert the vertexes until the line is not that long. 

I agree this an ESRI bug. We would have to check logs to see how common it is, but we should add code to avoid it if we can.

**Comment by kechinn** [comment]
Uh...long line. I know some features, like Zone 1 or 2 Spraying/Mowing lines can go long distances (the longest I've seen so far about 30 miles in length). Maybe 100 miles? Probably shouldn't see anything over that.

**Comment by ReedHunter-Wsdot** [comment]
A fix for this is now checked in.  The save button is now disabled for both new lines or edited existing lines if the length is 100 miles or more.  I will submit a bug report to Esri after 4.1 is out the door notifying them that this happens.
