### ISSUE TITLE
HATS admins and editors....

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1226]
We seemingly have a growing list of admins again which has caused a couple minor recent issues.

Instead of “if admin” for statewide searches/reporting can we simply change to “if editor”? I believe this will solve our problem.

Basically admins should only be my team and dev’s. Anything else I’d like sorted out via the Editors list.

**Comment by jhudsonWA** [comment]
So right now editors can be set for an org.

Should we just remove that and make all editors statewide or should we just add a statewide editor role (may be easier).

Sent from my iPhone

On Dec 27, 2018, at 9:19 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1226<https://github.com/WSDOT/HATS/issues/1226> to @jhudsonWA<https://github.com/jhudsonWA>.

**Comment by joeschmit** [comment]
The latter, can edit/view statewide as a true/false flag.

Sent from my iPad

On Dec 27, 2018, at 9:26 AM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

So right now editors can be set for an org.

Should we just remove that and make all editors statewide or should we just add a statewide editor role (may be easier).

Sent from my iPhone

On Dec 27, 2018, at 9:19 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Assigned #1226<https://github.com/WSDOT/HATS/issues/1226> to @jhudsonWA<https://github.com/jhudsonWA>.

**Comment by jhudsonWA** [comment]
I’ll make it so.

Sent from my iPhone

On Dec 27, 2018, at 9:33 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:

The latter, can edit/view statewide as a true/false flag.

Sent from my iPad

On Dec 27, 2018, at 9:26 AM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

So right now editors can be set for an org.

Should we just remove that and make all editors statewide or should we just add a statewide editor role (may be easier).

Sent from my iPhone

On Dec 27, 2018, at 9:19 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Assigned #1226<https://github.com/WSDOT/HATS/issues/1226> to @jhudsonWA<https://github.com/jhudsonWA>.

**Comment by jhudsonWA** [comment]
Deployed. New menu item. Admin -> HATS User Rights -> Statewide Editors. 

Statewide Editors can edit any Feature, Other, Pesticide Record.

**Comment by joeschmit** [comment]
Confirming this will also allow statewide searches for things like inventory and features etc.? That was the original intent.

**Comment by jhudsonWA** [comment]
It will tomorrow :) I read this as a fix to kicking admins out for record edits. We can have both easily.

Sent from my iPhone

On Jan 2, 2019, at 7:05 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:

Confirming this will also allow statewide searches for things like inventory and features etc.? That was the original intent.

**Comment by joeschmit** [comment]
Ha no worries yea we have people that need to “admins” So they can run reports it’s a relatively small group. But could expand a bit.

- Joe

On Jan 2, 2019, at 19:28, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

It will tomorrow :) I read this as a fix to kicking admins out for record edits. We can have both easily.

Sent from my iPhone

On Jan 2, 2019, at 7:05 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Confirming this will also allow statewide searches for things like inventory and features etc.? That was the original intent.

**Comment by jhudsonWA** [comment]
6.13 deployed. Statewide Editors also can do statewide inventory searches. I don't think there are any other reporting restrictions that are admin only. But if one comes up let me know.

**Comment by joeschmit** [comment]
Gracias.

- Joe

On Jan 3, 2019, at 09:47, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:


6.13 deployed. Statewide Editors also can do statewide inventory searches. I don't think there are any other reporting restrictions that are admin only. But if one comes up let me know.
