### ISSUE TITLE
Some number fields are not showing correct keyboard by default

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1229]
In AssignFeatureAttributesViewController: If type is number. Can you set keyboard type to numbersAndPunctuation, this one is easier since there is already a line setting a keyboard. It's just the default one.

ActivityRecordGroupUIView:

Currently if type is Number or Percentage no keyboard type is set (so it goes to default) can you do the first part of this task then use that as an example for these two types.

**Comment by brianblood** [comment]
Done.
