### ISSUE TITLE
Domain Username: @ should not be allowed. Same with \ symbol. Users are sending up email addresses which can mess up permission checks. 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1231]
I started this one right before I left for the break, but it's actually a pretty good one for you since it deals with string validation and touches several different view controllers.

Oai sent a report that some records on the web were not editable by users, even in the regular 14 day window. When I looked into it I noticed that some users are putting their full email address or a random email address in the wsdot domain field of records. This messes up some of the permission checks on the web. 

I have an example on **AddUserViewController** checking for a @ on save and throwing up a message. 

```
else if usernameTextField.text?.contains("@") == true {
            
            let alert = UIAlertController(title: "Invalid WSDOT Username",
                                          message: "Please enter the user's WSDOT username only. '@' is not allowed.\r\nEnter username instead of username@wsdot.wa.gov",
                                          preferredStyle: .alert)
            
            alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
            
            present(alert, animated: true, completion: nil)
            
            return
        }
```

Can you also add a check that checks for a \ and/or / in the name to help check for wsdot\ based usernames.

Once that is done those same checks can be added to **EditUserViewController**.

Also in the. validateRecordValues methods of **ActivityRecordViewController** and **PesticideApplicationRecordViewController** a check should be added for these same couple of checks. Note that they don't show an alert here they return a validation error. 

When you are done we should discuss how to validate current user data in the local database and records ready to send up.

**Comment by PeterBurkhard** [comment]
An if can have zero or one else's and it must come after any else if's.
An if can have zero to many else if's and they must come before the else.
Once an else if succeeds, none of the remaining else if's or else's will be tested.

**Comment by jhudsonWA** [comment]
#fact

**Comment by brianblood** [comment]
Done!
