### ISSUE TITLE
Park and Ride Symbol Inventory Feature

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1239]
Can we also add a park and Ride Symbol for a feature type and attach 1181 sweeping & cleaning pavement - pickup broom as and activity. Pretty Please?

![park-ride-sign-x-d4-2a](https://user-images.githubusercontent.com/15268732/50981402-c8128500-14af-11e9-88e7-d6a98384c900.png)

**Comment by PeterBurkhard** [comment]
<img width="1024" alt="img_ef959265704c-1" src="https://user-images.githubusercontent.com/15268732/50982318-c3e76700-14b1-11e9-8a23-b04064c10250.png">

**Comment by ReedHunter-Wsdot** [comment]
Will this be a Hats feature on which activities are performed, or a basemap feature?  Either way it can be done.

There's also a park and ride symbol available in ArcGIS: 
![image](https://user-images.githubusercontent.com/2709194/50983226-e5495280-14b3-11e9-8eb5-d90880621092.png)

**Comment by ReedHunter-Wsdot** [comment]
We can make it whatever color we want btw, including "Spruce Green"
![image](https://user-images.githubusercontent.com/2709194/50983361-2ccfde80-14b4-11e9-9e39-d19262cd2b8c.png)

or the ever popular "Peony Pink":
![image](https://user-images.githubusercontent.com/2709194/50983481-64d72180-14b4-11e9-9351-d2af76dc5367.png)

**Comment by jhudsonWA** [comment]
Poly? 

I would say it shouldn’t launch until the next version after 4.1. 4.1 is supposed to be bug fixes only and small enhancements. We can add a feature type if it is time sensitive but if it can wait until spring that fits better into our normal release schedule.

**Comment by PeterBurkhard** [comment]
This was requested in October, I just now got around to putting it in Git. Spring should be fine. Thank you. I like Spruce Green!

**Comment by jhudsonWA** [comment]
Ok. Let let us check staff availability. We always have to work with Jason when we add a new feature type and will want to make he would available. Our primary goal in this release is to fix the map bugs found. If we end up having time we will add the new feature.

On Jan 10, 2019, at 9:10 AM, Pete <notifications@github.com<mailto:notifications@github.com>> wrote:


This was requested in October, I just now got around to putting it in Git. Spring should be fine. Thank you. I like Spruce Green!

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot Layer ID is 155. If you want to request from Jason, and think this won't get in the way of our other fixes we can see if we can fit it in.

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot Type: Point

**Comment by ReedHunter-Wsdot** [comment]
I'll give it a try, but I agree that this is a 4.1 task only if the others take long enough to allow it.  I'll start this Friday.  I'm on the fence whether remaining 4.1 tasks allow enough time for this.

**Comment by ReedHunter-Wsdot** [comment]
Josh, I have scrounged around in workbench, located rest areas data, and loaded it into the staging geodatabase.  Could you load that into HighwayActivities so the points can have wsdot IDs?
Thanks

**Comment by jhudsonWA** [comment]
Rest areas are not park and rides in this request. They just want a new empty point feature called Park and Ride, id 155, with the included icon.

Sent from my iPhone

On Jan 11, 2019, at 11:02 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Josh, I have scrounged around in workbench, located rest areas data, and loaded it into the staging geodatabase. Could you load that into HighwayActivities so the points can have wsdot IDs?
Thanks

**Comment by ReedHunter-Wsdot** [comment]
:D Thanks for the reminder.  I have an empty 155 layer ready in the dev geodatabase, and I'm writing the request now to Jason.

**Comment by ReedHunter-Wsdot** [comment]
Prod and Qa service updates are now published with this new layer.
