### ISSUE TITLE
Automate detection of slow map syncs using Sql script and console app

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1245]
Right now I'm connecting about every morning and running a sql script I wrote to detect slow syncs. Automating this makes more sense.

The task is to write a console app that will access the Hats app logs, check whether today's syncs are slow, and email a notice to stakeholders if they are.  

Once built, this app will need to be setup on an app server and scheduled to run late enough in the morning for the morning rush of map syncs to be underway.  Even on slow days map syncs are usually fast before 5 am.

**Comment by jhudsonWA** [comment]
My team can handle this. We can make a page in HATS as well that runs the same script. Result is a Date, and 3 columns reporting sync time statistics.

**Comment by jhudsonWA** [comment]
Thanks for writing the script Reed! : )

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Can you handle this? I'll email you what you need.

**Comment by lundyc-wsdot** [comment]
I’ll surely give it a shot …


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by joeschmit** [comment]
This is cool. Thanks guys.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
