### ISSUE TITLE
WDFW Attribute in HATS

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#1248]
We added the attribute WDFW ID to the culvert feature. Kathy has been matching the DFW and HATS culverts and adding the WSDOT feature number to the DFW database. Can you take what she’s done and load the DFW ID to the corresponding HATS feature ID?

[HatsWdfwCrosswalk012419.xlsx](https://github.com/WSDOT/HATS/files/2793426/HatsWdfwCrosswalk012419.xlsx)

**Comment by jhudsonWA** [comment]
Thanks!

**Comment by jhudsonWA** [comment]
These have been loaded into production.
