### ISSUE TITLE
[HATS Form]  Modify Impact Attenuator Form

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#125]
![impact attenuator list](https://cloud.githubusercontent.com/assets/884943/10351891/e37ba236-6d00-11e5-90da-abbbb04157c0.PNG)

![image](https://cloud.githubusercontent.com/assets/884943/10351894/ebc9d61a-6d00-11e5-8754-6367fe4b205e.png)

**Comment by joeschmit** [comment]
@jhudsonWA this...see the "attributes" comment above

**Comment by jhudsonWA** [comment]
Done. In production. Please verify.
