### ISSUE TITLE
Lock Down Culverts

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#1267]
Can we lock down culvert features that have any of the following attributes selected: WDFW I.D., On Statewide Fish Passage List or On culvert Lawsuit Injunction Barrier List. I believe we have already locked down those features that are listed on the Statewide Fish Passage List. Thanks

**Comment by jhudsonWA** [comment]
This is done and will be included in 4.1. 
![simulator screen shot - ipad pro 9 7-inch - 2019-02-04 at 16 49 54](https://user-images.githubusercontent.com/702446/52246995-e72ce880-289c-11e9-8871-f3ff477ad50a.png)

**Comment by jhudsonWA** [comment]
I should say this change is iOS only. I'll reopen and check web as well.

**Comment by sheppamwsdot** [comment]
This has been completed.
