### ISSUE TITLE
No Blue Halo on Fuel Station Icon

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1275]
![nobluehalo](https://user-images.githubusercontent.com/15268732/52307977-f9685e80-2950-11e9-8582-c2cbe2ac495e.gif)

**Comment by ReedHunter-Wsdot** [comment]
This one is looking like more than just a one or two liner fix.  HATS in debug is telling me that the fuel station layer is "uninitialized" so it can't be selected, which is strange since it's loaded and showing in the map.  Timeline to investigate and fix this one makes it a post 4.1 bug fix.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
