### ISSUE TITLE
The offline base map toggles get stuck after repeated toggling between base maps. Offline Map Turns Gray.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1277]
The offline base map goes gray after repeated toggling between base maps. 
Even after delete and re download map features. 

![mapweirdness](https://user-images.githubusercontent.com/15268732/52309367-c7f19200-2954-11e9-9725-deba14dec181.gif)

**Comment by PeterBurkhard** [comment]
Cities, Local Roads, NPDES Areas, National Forest, National Park, National Security UAS Flight Restrictions, Roadside Maintenance Sensitive Areas, Route Segments, Tribal Lands, Water Quality, TMDL Boundaries and msftBuilingsClipped, get turned off when switching between Basemaps. iPad Pro and iPad 5th Gen.
![basemaplayerspsh](https://user-images.githubusercontent.com/15268732/52311455-d3948700-295b-11e9-9067-59cdacd78ce5.gif)

**Comment by ReedHunter-Wsdot** [comment]
This is now fixed.

**Comment by PeterBurkhard** [comment]
~~It's by design. Not a bug.~~

**Comment by jhudsonWA** [comment]
There are two issues on this one report. The first one (grey background is fixed, the second one with the layers is currently being fixed.

**Comment by ReedHunter-Wsdot** [comment]
Fix for this is checked in.

**Comment by jhudsonWA** [comment]
I’ll create a new beta!

On Feb 7, 2019, at 8:50 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1277<https://github.com/WSDOT/HATS/issues/1277>.
