### ISSUE TITLE
Bridge Debris Removal Excel Reporting Bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1280]
@jhudsonWA Looking at a mixup of values in the Excel report for Bridge Debris Removal report. The LWMRepositioned (V) should be a integer field, and is not showing that data. The text values from column V should be reporting to LWMDisposition in column W.
![image](https://user-images.githubusercontent.com/16247034/52382723-415bb400-2a2b-11e9-80aa-5af0e92edb81.png)

[Bridge Debris Removal Records 02-06-2019_04-16-17 PM.xlsx](https://github.com/WSDOT/HATS/files/2838807/Bridge.Debris.Removal.Records.02-06-2019_04-16-17.PM.xlsx)

**Comment by jhudsonWA** [comment]
Is it only this one report? The Culvert Cleaning one is now correct?

**Comment by jhudsonWA** [comment]
Should be fixed. Let me know if any others are mixed up. I went through all the other reports and made the same changes.
