### ISSUE TITLE
Close Pending Activities

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1290]
Need a mass close of pending activities where org code is 43, feature type Pavement Markings.

Thanks

Joe

**Comment by jhudsonWA** [comment]
Yep, I'll run this after 5 pm today. Here is the query with the records that will be completed.

select * from PendingActivity pa
inner join [Event] e on e.EventId = pa.TriggeringEventId
where pa.CompletedDate is null
and e.OrganizationCode like '43%'
and LocalFeatureTypeId = 26

**Comment by jhudsonWA** [comment]
Done

**Comment by joeschmit** [comment]
Thanks.

- Joe

On Feb 20, 2019, at 15:27, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:


Done
