### ISSUE TITLE
Refresh QA to mirror Prod

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1305]
Josh, would you please look into making QA mirror Prod? If this process can be automated monthly or every few months that would be great.

**Comment by jhudsonWA** [comment]
<img width="864" alt="screen shot 2019-03-05 at 12 18 01 pm" src="https://user-images.githubusercontent.com/702446/53834766-bc3bc000-3f40-11e9-9c10-861b208704f0.png">
