### ISSUE TITLE
Pending Activities -> Feature Attribute check box

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1313]
Josh can we get this check box included with Feature Pending Activities? People are asking to see feature attributes included in the export.

**Comment by jhudsonWA** [comment]
We have a consultant working on this starting now. Option will only show up if you select a type. Otherwise supporting multiple types would mix attributes and look weird.

**Comment by jhudsonWA** [comment]
In QA. Will be in next prod push. Please test
