### ISSUE TITLE
Budget: Upload Budget Data By Region from Excel document. 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1315]
"One request has been to have an upload template so the region doesn’t have to key everything in at the beginning of the biennia.  Here is any example of what was used with TRAINS. " - Andrea
[PRPL_Loading_Template.xlsx](https://github.com/WSDOT/HATS/files/2979602/PRPL_Loading_Template.xlsx)

**Comment by brianblood** [comment]
Done
