### ISSUE TITLE
RC 4.3.1  Save Grayed out when Adding Polygon Feature.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1317]
![Can't Save New Polygon Feature](https://user-images.githubusercontent.com/15268732/54930531-a92f6680-4ed4-11e9-8cde-57ce25b484ea.gif)

**Comment by ReedHunter-Wsdot** [comment]
I'll get a fix for that checked in shortly.

**Comment by ReedHunter-Wsdot** [comment]
checked in.
