### ISSUE TITLE
Feature Activities - Update Work Ops To Current Fiscal Year Button

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1321]
Work Ops for activities are assigned with a work op id at the time they are assigned. The issue is each fiscal year the work ops are resetup so the id's change. But the ids for the activity are never updated so they point to the old work ops (even though the codes are the same). 

Add a button that runs a script that will rematch the activities work op codes to the current fiscal year.

Something like this: 

Update ad
Set WorkOperationId = cfwo.MaintenanceWorkOperationId
From ActivityDefinition ad
inner join MaintenanceWorkOperation wo on wo.MaintenanceWorkOperationId = WorkOperationId
inner join MaintenanceWorkOperation cfwo on cfwo.WorkOperationCode = wo.WorkOperationCode
where cfwo.WorkOperationFiscalYear = @currentfiscalyear

**Comment by jhudsonWA** [comment]
I've run this script once in prod, so they are matched up for now, but there should a button so admins can do it once a year once the work ops are setup.

**Comment by joeschmit** [comment]
Is this still on the radar? Not sure its still needed? http://hatsprod.wsdot.loc/Maintenance/management/activities/Admin/MaintenanceWorkOperations

**Comment by jhudsonWA** [comment]
Yep, should I push the current ones up manually for now to 2020 to buy us time?

________________________________

**Comment by jhudsonWA** [comment]
Assigning to Vince so it will be ready for 2020.

**Comment by VinceRanger** [comment]
I've attached a document explaining the implementation for this issue.  It's currently in QA. Please review the document and let me know if you have any comments or recommendations. 


[MaintenanceWorkOperations.docx](https://github.com/WSDOT/HATS/files/3848179/MaintenanceWorkOperations.docx)

**Comment by VinceRanger** [comment]
Sorry about that. Didn't mean to close it. Still waiting to review with Oai.

**Comment by sheppamwsdot** [comment]
This is probably complete.
