### ISSUE TITLE
Undo/redo loses sketch vertex selection for point features created from GPS

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1322]
![image](https://user-images.githubusercontent.com/2709194/55508610-19de2d80-560f-11e9-8ff7-487e1865fba5.png)

This is a pretty niche editing bug with minor impact but it should be fixed.

Steps to reproduce:

- start to add a new point feature
- collect the point using [+Collect Gps]
- tap [Undo].  The point should disappear
- tap [Redo]

Result:
The point reappears, but is not selected.
Expected Result:
The vertex of the edit sketch should be selected when it reappears.

This affects only point features.  Lines and polygons don't have this problem.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
