### ISSUE TITLE
Deleting all sketch vertices resets the undo/redo stack

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1323]
When editing a line or polygon feature, deleting all of the sketch vertices will wipe out the undo stack.

Steps to reproduce:
1. Select and start editing either a line or polygon feature
2. Tap [Delete Vertex] until there are no more vertices

**Result:**
The undo button is greyed out once the last vertex is gone.

**Expected result:**
You should still be able to undo your way back from the edit sketch being emptied out.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
