### ISSUE TITLE
Map search doesn't work for newly made features with IDs like "NewFeature-#"

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1324]
When a new feature has been created, but hasn't been synced up to the server yet, a placeholder ID like NewFeature-0, NewFeature-1, etc. is assigned as a temporary placeholder.  The current search tool is only working for those features that have been assigned a final ID.  You can't use it to locate one of the new features that just has its placeholder.

**Steps to Reproduce:**

1. Make a new feature.  Observe what ID it initially has.  It will be something like NewFeature-# where # is some number.
2. Try to search for that "NewFeature-#" id in the map search tool.

**Result:**
The map search tool doesn't find the feature.

**Expected Result:**
It's there in the database and in the map, so the tool ought to be able to find it.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops.
