### ISSUE TITLE
+Collect GPS won't work if you delete all vertices of a line or polygon

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1325]
When editing a line or polygon feature, deleting all of the sketch vertices will make the [+Collect GPS] stop working.

**Steps to reproduce:**

1. Select and start editing either a line or polygon feature
2. Tap [Delete Vertex] until there are no more vertices
3. Make sure you have a green GPS indicator
4. Tap [+Collect GPS]

**Result:**
No vertex is added to the sketch.

**Expected result:**
A vertex should have been added to the sketch.

There are quick workarounds for now where you just restart the sketch or add a vertex using your finger on the map.  Either will let +Collect GPS work again.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops.
