### ISSUE TITLE
HATS Web: Work Ops Enhancement Request

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1326]
Josh: One thing the group now wants is the ability have a long text description added to Work Ops table. Sorry about this. They would want to be able to write a narrative of the work operation that later on down the road can be referenced like help text.

**Comment by jhudsonWA** [comment]
Groovy

**Comment by joeschmit** [comment]
@jhudsonWA can I bump so we can get this over and done with...if possible for the consultant crew if still available...

**Comment by jhudsonWA** [comment]
I’ll make it my priority today.

On May 2, 2019, at 8:14 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


bump...if possible for the consultant crew if still available.

**Comment by joeschmit** [comment]
word

**Comment by jhudsonWA** [comment]
Forgot to update. Shipped on Thursday.
