### ISSUE TITLE
Culvert Points to Lines

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#1327]
The below message is from Kathy Prosser. The feature is no longer on the iPad but is still active on the web.

With the latest deployment of HATS, the bug that caused culvert ends to disappear when you tried to convert them to lines was fixed.  It worked great all day.  Until I tried to convert WSDOT0000589172 to a line.  HATS closed up and when I re-opened it, WSDOT0000589172 was gone.

**Comment by jhudsonWA** [comment]
We will look at crash reports to see if we see anything that stands out.

**Comment by ReedHunter-Wsdot** [comment]
I'll also look at the logs and the status of that feature to see if anything jumps out about it being different.

**Comment by ReedHunter-Wsdot** [comment]
Kathy is going to temporarily drop off her old iPad with me where this took place.  It sounds like there are some startup issues now with that beta.  

She was just issued a new device she'll use in the meantime.

**Comment by ReedHunter-Wsdot** [comment]
This turned out to be an old installation of Hats beta.  The version of the features geodatabase was 2.5 and the sqlite db version was 55.
