### ISSUE TITLE
[Data]  Add Attributes to Guardrail

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#133]
Please add the following attributes to "Guardrail"
-Type (predefined) W Beam Type 31, W Beam Type 1, W Beam Other, Thrie Beam, Weathering Steel, Other
-Type of posts in run (predefined) Wood, Steel, Mixed, Other
-Radius (number)
-Post length (number)

**Comment by joeschmit** [comment]
@jhudsonWA  this....

**Comment by jhudsonWA** [comment]
In Prod, please verify.
