### ISSUE TITLE
Add an editors only edits flag to an activity

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1330]
so only editors can edit certain forms, request from region Trainers mainly for the CDL form but could be useful in the future.

**Comment by jhudsonWA** [comment]
@brianblood is this something you could tackle asap? Add a new flag to the activity table. Then update web app in both feature and other edit record screens that if this flag is set for an activity the only permissions it would check is if the user is an admin or editor. Right now for the first 14 days it lets the user who created the record edit as well. This flag would bypass that check. 

Finally update the Activity admin screen to allow this flag to be set on an activity.

**Comment by brianblood** [comment]
Sure, I'll get on it right now.

**Comment by brianblood** [comment]
This is done and deployed to QA.

**Comment by jhudsonWA** [comment]
@tangoai Deployed to prod and I set the CDL Training Record to true, so only editors and admins can edit these records once submitted.

**Comment by jhudsonWA** [comment]
Thanks Brian!
