### ISSUE TITLE
Create Ditch Feature Roadside Feature Number 9

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1332]
Reed please create/enable the Ditch Feature. 
We have folks who would like to schedule some ditch work, but first we need a feature.

SELECT *
  FROM [HighwayActivitiesTracking].[dbo].[RoadsideFeatureType]
  WHERE RoadsideFeatureTypeName = 'Ditch';

**Comment by ReedHunter-Wsdot** [comment]
To put this in the hands of our crews, we'll have to release a new version of HATS just like we'd have to for supporting wetland mitigation sites.  What's the timeline for when we need this?

Do you still want this ASAP?

**Comment by Douggow** [comment]
This came from a tech but the superintendent says he is being asked to schedule work for the coming biennium and ditching is a big part of what they do in this area. Not an emergency but I would say sooner than later.

**Comment by tangoai** [comment]
We've talked to Joe and we would like to see this release before 4.5. if we can get these two features out in a few weeks that would be great. Please let us know what else you need from us to make this happen.  Thanks Reed!

**Comment by ReedHunter-Wsdot** [comment]
Can do.

**Comment by jhudsonWA** [comment]
Hold for a bit before we do anything. I want to get requirements for this new version locked down today then we can plan a release.

**Comment by jhudsonWA** [comment]
Per Joe: This can now hold off until 4.5 in September.

**Comment by ReedHunter-Wsdot** [comment]
@jhudsonWA , when you have the time I'll need an updated Hatsdb.sqlite with the Ids enabled for ditches (9), wetland mitigation site boundaries (156), and the three new general feature types (157, 158, 159) so I can better test the new feature types in Qa.

**Comment by jhudsonWA** [comment]
Just do a sync? They should all be enabled..

________________________________

**Comment by ReedHunter-Wsdot** [comment]
Feature types 156 through 159 are present, but not showing in the Toc.  I'll investigate.  On device add, edit, and delete is not allowed for these btw.  There's also a "Ditch Maintenance" row with a null RoadsideFeatureTypeId.

**Comment by jhudsonWA** [comment]
On device edit will need to be toggled for some but some are only reference so that’s fine.
Still should show on device if in the local table

________________________________

**Comment by ReedHunter-Wsdot** [comment]
The problem of the Toc not getting the layer went away by the time I was running through debug.  It looks like the Sdk was holding onto the old geodatabase despite my replacing the file and restarting Hats.

**Comment by ReedHunter-Wsdot** [comment]
I toggled the allow create/edit/delete on my local database for testing, but you'll have to update these settings server-side since I don't have permissions.

**Comment by ReedHunter-Wsdot** [comment]
Pete, these ditches have nothing to do with stormwater, right?

**Comment by jhudsonWA** [comment]
To clarify, we used to have a ditch feature (local only) and then we added and disabled the stormwater ditch from SWIM. Which one should this request cover?

**Comment by Douggow** [comment]
The ditches do covey storm water but this request was made to able to identify and schedule ditching projects for budgeting and maintenance purposes and to be able to identify a potential backlog of ditching.  Hope this helps

**Comment by jhudsonWA** [comment]
Then the real question should be, and I'll leave this up to @joeschmit's team: Should we reuse an existing Ditch feature or is this something new like "Ditch Projects"

**Comment by ReedHunter-Wsdot** [comment]
I'll reuse the existing ditch feature for the version 4.4 map service.  Ditches are going to be line features regardless, we can always rename the layer and have the new name sync down at any time, and if the existing legacy features are unwanted we can always wholesale delete them and make the layer empty.  I think that I can even change the line symbology without breaking sync compatibility - people would just have to redownload the next day's features map to see the symbol change.
