### ISSUE TITLE
Site Name column would be beneficial

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1334]
can we have a "Site Name" column included for when searching feature activity records?

**Comment by jhudsonWA** [comment]
Is this for a particular feature type? Not all features have a Site Name attribute.

On Jun 11, 2019, at 3:59 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:


can we have a "Site Name" column included for when searching feature activity records?

**Comment by tangoai** [comment]
Yes, we've talked to Brian and he is aware. It's for the Liquid Deicer Tank feature

**Comment by jhudsonWA** [comment]
👍🏻

Sent from my iPhone

On Jun 12, 2019, at 1:41 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, we've talked to Brian and he is aware. It's for the Liquid Deicer Tank feature

**Comment by jhudsonWA** [comment]
I would think this would just be solved if we added attribute search to current records which is a common request. Let’s do that :)

Sent from my iPhone

On Jun 12, 2019, at 1:41 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, we've talked to Brian and he is aware. It's for the Liquid Deicer Tank feature

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
