### ISSUE TITLE
Generic point/line/polygon features under "Other" table of content category

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1336]
These features can be used to mark any random things/thoughts they may want to note and share with their co workers.

**Comment by jhudsonWA** [comment]
Do we have a preferred feature name for these generic layers?

**Comment by tangoai** [comment]
generic point, generic line, generic polygon please and thank u.

**Comment by jhudsonWA** [comment]
Feature types created for generic point (157), line (158) and polygon (159)

**Comment by ReedHunter-Wsdot** [comment]
This is in place in Qa.  I'll make a new prod map service on Monday with these layers.  It also looks like the server upgrades are having an effect - we can now have multi-layered map symbols.  I'm using symbols reminiscent of a yellow notepad for the generic features.

**Comment by ReedHunter-Wsdot** [comment]
Make that Tuesday when I'll make the prod map service - I'll be out on Monday.

**Comment by ReedHunter-Wsdot** [comment]
This has been in place a few weeks now.  I didn't want to close issue this until I was sure the 100.5 sdk sync bug and the rollback to 100.4 didn't mess with this.  This is checked in and will be part of the next beta.
