### ISSUE TITLE
Update basemap layers

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1337]
Please update the city layers and any other basemap layers that are outdated. Thanks guys!

**Comment by ReedHunter-Wsdot** [comment]
This includes reviewing the road layers to make sure we have the latest.

**Comment by jhudsonWA** [comment]
I’m pretty sure 2018 LRS data is now live, so we should be able to update the roads as well.

On Jun 24, 2019, at 9:35 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


This includes reviewing the road layers to make sure we have the latest.

**Comment by tangoai** [comment]
Keller Ferry rest area is missing so please update that layer as well.

**Comment by ReedHunter-Wsdot** [comment]
Got it.  Thanks for adding this to github. 

I just snagged a copy of the latest from workbench and there are 13 more rest areas in there than in last year's data, including Keller Ferry.  Once I'm done with #1359 the data updates will probably be the next task in line.

**Comment by kechinn** [comment]
There is also an update I'm working on to the TMDL layer in the Workbench, which will affect the approved subset in HATS. I can let you know when this is ready.

**Comment by ReedHunter-Wsdot** [comment]
Keisha, Is there any word on the TMDL layer?  I'm otherwise ready to generate the next offline basemap layer file.

**Comment by sheppamwsdot** [comment]
Being tracked in Dev Ops
