### ISSUE TITLE
HATS Web: Remove Highway Activities Tracking System words from anywhere on the web and replace with just HATS

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1338]

**Comment by joeschmit** [comment]
HATS is a word now - not an acronym

**Comment by jhudsonWA** [comment]
Word

________________________________

**Comment by brianblood** [comment]
Too many words.

On Jun 27, 2019, at 10:04 AM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Word

________________________________

**Comment by jhudsonWA** [comment]
Done. Will go out with next release.
