### ISSUE TITLE
HATS Web Enhancement: All Activity Record Attachments

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1339]
- [ ] Allow access to any user not just admins

- [ ] Add filtering: Date, Orgcode, Feature Type, Feature Activity, SR/MP, or no filters

- [ ] Add check box to allow for selections (one, many, select all) and download button.

- [ ] Rename to "Files and Photos" under File Library

Limit to like 25 per page or whatever performance makes sense.

* The goal would be to allow for users to browse photos and download without having to search by record.

**Comment by jhudsonWA** [comment]
Got it, will add to work list.

**Comment by jhudsonWA** [comment]
Where should this new menu item live? If it's for everyone won't make sense under Admin any more.

**Comment by joeschmit** [comment]
I think it would like to live here File Library > Record Files and Photos

**Comment by jhudsonWA** [comment]
Got it : )

**Comment by jhudsonWA** [comment]
So the current Activity Record Attachments shows all attachments, including pdfs etc. Should it be filtered to jpgs only for the new all users screen?

**Comment by jhudsonWA** [comment]
Assigning to @VinceRanger

**Comment by sheppamwsdot** [comment]
This has been migrated to a Work Item in our Dev Ops system.
