### ISSUE TITLE
Budget Tool: Bug when "Export Budget" button is clicked

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1347]
<img width="2189" alt="Screenshot 2019-07-16 16 14 05" src="https://user-images.githubusercontent.com/884943/61336092-d5a12280-a7e4-11e9-8168-be471b12dee0.png">

**Comment by joeschmit** [comment]
Under HQ tab...

**Comment by brianblood** [comment]
Fixed in Dev.

**Comment by brianblood** [comment]
Deployed to Prod
