### ISSUE TITLE
Budget Tool: Pages seem slow?

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1348]
Can you just check on this when you have a moment, the app in general seems slow between screens. I don't have anything more specific to say than that, sorry, don't hate me.

**Comment by jhudsonWA** [comment]
@brianblood please make this a priority this week. Thanks

**Comment by brianblood** [comment]
Ripped out some super-slow linq queries, converted them to boring clunky but fast for-loops.
