### ISSUE TITLE
Budget Tool: unable to establish control totals for 19/21

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1350]
Admin unable to edit or implement new budget totals

**Comment by brianblood** [comment]
Is it in a read-only state with a bunch of labels, or are there text boxes with content that is not persisting after a reload?  It's working on my machine, of course.  :)

**Comment by joeschmit** [comment]
It just magically started working. ¯＼_(ツ)_/¯

- Joe

On Jul 17, 2019, at 09:50, brianblood <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it in a read-only state with a bunch of labels, or are there text boxes with content that is not persisting after a reload? It's working on my machine, of course. :)

**Comment by brianblood** [comment]
Gah.

Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov> | 360.709.8243
