### ISSUE TITLE
End Time Missing for UAS Flight Log Activity

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1353]
UAS other activity form asks for both a start and end time on web/mobile creation, but only shows one date/time in current records and on export. 

![image](https://user-images.githubusercontent.com/16247034/61465490-055b4200-a92d-11e9-8515-d6df069e1521.png)

**Comment by jhudsonWA** [comment]
It’s a flag on activities in admin. Any admin can change it

**Comment by kechinn** [comment]
@jhudsonWA I'm no longer an admin;)

**Comment by jhudsonWA** [comment]
Lame. :) they will probably kick me out as well now. @Burkhard, Peter<mailto:BurkharP@wsdot.wa.gov> can you switch it on?

________________________________

**Comment by PeterBurkhard** [comment]
Weird. Josh I think you get even more Godlike status.

**Comment by PeterBurkhard** [comment]
I can't find anywhere on the activities form editor to change or add the date and time questions.

**Comment by jhudsonWA** [comment]
It’s not there.
Go to the feature activities admin screen, then edit the actual activity. Not the form

________________________________

**Comment by jhudsonWA** [comment]
@PeterBurkhard Need help with this one or was it changed?

**Comment by PeterBurkhard** [comment]
This is all I see for true false flags.
<img width="2025" alt="Screen Shot 2019-07-29 at 4 13 58 PM" src="https://user-images.githubusercontent.com/15268732/62088984-0a1cd180-b21c-11e9-8cfd-426015a89549.png">

**Comment by jhudsonWA** [comment]
Seems like it’s good then? “Collect Date Range” = true now

**Comment by jhudsonWA** [comment]
Is this not working on the iOS version? I see an end date on the web when doing an mission record.

**Comment by PeterBurkhard** [comment]
I don't see a drop down for Other Activities. What am I missing?
<img width="781" alt="Screen Shot 2019-07-29 at 4 17 00 PM" src="https://user-images.githubusercontent.com/15268732/62089103-929b7200-b21c-11e9-8522-cebb4c492139.png">

**Comment by jhudsonWA** [comment]
Other activities are just Feature Types that are not tied to an inventory item. If you look there they say Local = True

**Comment by PeterBurkhard** [comment]
I see it on the iPad.

**Comment by PeterBurkhard** [comment]
![Image-1](https://user-images.githubusercontent.com/15268732/62089313-51f02880-b21d-11e9-894e-4bd5bce65301.jpeg)

**Comment by jhudsonWA** [comment]
Then I think we are good with this request.  Lol

**Comment by jhudsonWA** [comment]
@kechinn ?

**Comment by kechinn** [comment]
Sorry, I should have clarified. Yes, you can see and collect both the start and end times on mobile and on web on creation. You cannot, however, view the end time when you open a submitted activity-it disappears and only shows the start (same of course if you print or export, there is only one combined column for date and time). 

The other Other Activity type that I know uses a start/end date and time is Snow and Ice Material Application - For Trucks without AVL. If you open a current record, it shows both.

**Comment by jhudsonWA** [comment]
@brianblood Also once you make your changes can you follow up on this? I'm wondering if your latest changes fixes this one as well.

**Comment by brianblood** [comment]
I'll take a look.

**Comment by brianblood** [comment]
Fixed!
