### ISSUE TITLE
Remove requirement for Orgcode

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1355]
Please remove orgcode requirement for Add/Edit Estimate Labor Items list.

**Comment by tangoai** [comment]
ASAP only because folks are screaming for updated labor cost numbers.

**Comment by jhudsonWA** [comment]
@brianblood Can you do this today or tomorrow. Oai seems willing to use one of his two, yearly "use Brian for web development" cards on this. :) 

I'm out rest of week after today and Clay isn't back until tomorrow.

This change would be for admin only. If admin, this field is no longer required.

**Comment by brianblood** [comment]
Yup.  Best he use them early before they are removed from the deck.

**Comment by brianblood** [comment]
@tangoai Is this meant to be HATS Admin only or Estimates Admin?

**Comment by joeschmit** [comment]
HATS admins (the important people only)

- Joe

On Jul 30, 2019, at 08:44, brianblood <notifications@github.com<mailto:notifications@github.com>> wrote:


@tangoai<https://github.com/tangoai> Is this meant to be HATS Admin only or Estimates Admin?

**Comment by brianblood** [comment]
Done
