### ISSUE TITLE
Can you add Weigh Station...

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1356]
Parking and Ride and Rest Areas as an option under location pick wheel.  Thanks

Yo snitch, this doesn't count!

**Comment by joeschmit** [comment]
“Weigh Station” not weight

- Joe

On Jul 29, 2019, at 12:56, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:


Parking and Ride and Rest Areas as an option under location pick wheel. Thanks

Yo snitch, this doesn't count!

**Comment by joeschmit** [comment]
List updates should read: 

- [x] Weigh Station
- [x] Park and Ride Lot
- [x] Park and Pool Lot
- [x] Rest Area

**Comment by jhudsonWA** [comment]
Should all be added after a sync

**Comment by joeschmit** [comment]
thx
