### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1357]
Getting a sync error after refreshing Meraki.
![IMG_0003](https://user-images.githubusercontent.com/16247034/62165570-a229c200-b2d3-11e9-87d4-86fea566bb42.PNG)

**Comment by brianblood** [comment]
Reed is looking into it right now.

On Jul 30, 2019, at 2:11 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Getting a sync error after refreshing Meraki.
[IMG_0003]<https://user-images.githubusercontent.com/16247034/62165570-a229c200-b2d3-11e9-87d4-86fea566bb42.PNG>

**Comment by ReedHunter-Wsdot** [comment]
Map syncs in prod have been out of commission since 10:17 this morning.  I found out ~20 min ago and am looking into it.
