### ISSUE TITLE
Create a map tab for other activities

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1359]
Figured I should document this core deliverable for the 4.5 milestone.

The use case is to just get the milepost near where the iPad happens to be, so that's the core information the map will be designed to deliver.  The rest will all be context around the mileposts.  Users entering "Other" activities will be able to tab over to the map, visually pick the nearest milepost, and then tab back to enter their milepost choice into the activity record.

This new map tab will be centered on the iPad's current location, showing both basemap and operational layers.  It will be zoomed in deeply enough to allow milepost points to be visible.  The map UI will be no frills since it's just delivering the current location's mileposts.  There will be no manual pan/zoom, no current location button (it will always show the current location), no TOC, no map mode control.

**Comment by sheppamwsdot** [comment]
Being tracked in Dev Ops
