### ISSUE TITLE
MAP Survey Report - 2019 broken

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1362]
When running calculations for the MAP Survey Report 2019 getting errors:
Reporting Services Error
An error has occurred during report processing. (rsProcessingAborted) Get Online Help
Query execution failed for dataset 'MapSurveyData'. (rsErrorExecutingCommand) Get Online Help
For more information about this error navigate to the report server on the local server machine, or enable remote errors
SQL Server Reporting Services

http://hqolymsqlrpt04p.wsdot.loc/ReportServer?%2fMaintenance%2fManagement%2fActivities%2fMapSurveyMaintenanceAccountabilityProcess&rs:Command=Render&rs:Format=PDF&rc:Parameters=Collapsed&rc:DocMap=false&rs:ClearSession=true&StartDate=1/1/2019&EndDate=12/31/2019%2011:59:59%20PM&RegionId=6&RunCalculation=True

**Comment by jhudsonWA** [comment]
Fixed. Bridge cleaning still not updated for 2019 data, but you no longer get an error and the calculations do complete without error after some time.
