### ISSUE TITLE
HATS Web: Editing Feature Location (Region/Area) Bug

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1364]
Edit Feature - Location - The target database ('WSDOTDataLibrary') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.

**Comment by brianblood** [comment]
Hey Josh - I'd assumed this was related to HATS being hosted in the cloud, but I just had a peek at this, and am seeing an error in QA as well.  The errors are different, though:
QA: "Edit Feature - Location - The EXECUTE permission was denied on the object 'usp_HATS_GetStateRoutePointGeographiesForStateRoutePoint', database 'WSDOTDataLibrary', schema 'dbo'."
Prod: "Could not find entered Start SR, RRT, RRQ, SRMP on the state route system. Save could not be completed."

**Comment by jhudsonWA** [comment]
I’ll take a look, see if I can figure it out.

Joshua Hudson
Applications Modernization Manager, Enterprise Applications
[cid:image001.png@01D496DE.F3223B40]
hudsonj@wsdot.wa.gov<mailto:hudsonj@wsdot.wa.gov> | 360.705.7778

**Comment by sheppamwsdot** [comment]
This has been migrated to a Work Item in our Dev Ops system.
