### ISSUE TITLE
HATS Web: Other > Snow and Ice > Winter Event > Edit > Requiring End Date/Time

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1368]
Other Activities without the end date/time flag set to true...

On edit requires an "End Date" to submit.

On add does not.

<img width="710" alt="Screenshot 2019-10-02 10 44 20" src="https://user-images.githubusercontent.com/884943/66068323-3dbcf600-e502-11e9-970f-2af3e40a9e93.png">

**Comment by joeschmit** [comment]
bump...

**Comment by jhudsonWA** [comment]
Brian can you check this today?

Joshua Hudson
Applications Modernization Manager, Enterprise Applications
hudsonj@wsdot.wa.gov | 360.705.7778
________________________________

**Comment by brianblood** [comment]
Yep, already on it.

Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov> | 360.709.8243

**Comment by brianblood** [comment]
Hey Josh/Joe
Any insight on this bit of code when editing an Other Activity?

//Snow and Ice Records Are "Special"
                if (vm.FeatureTypeName.ToLower() == "snow and ice")
                {
                    vm.ShowTimeRange = true;
                    vm.ShowAvlTrucks = true;
                    vm.HideLocationIndicator = true;
                }

This is not happening when creating a new record.  I can either remove this bit from Edit, or add it to Add.  Preferences?

Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov> | 360.709.8243

**Comment by joeschmit** [comment]
vm.ShowTimeRange = true; shouldn’t that be deprecated? We now have a flag in admin > feature activities > end date/time?

On Oct 9, 2019, at 11:31 AM, brianblood <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey Josh/Joe
Any insight on this bit of code when editing an Other Activity?

//Snow and Ice Records Are "Special"
if (vm.FeatureTypeName.ToLower() == "snow and ice")
{
vm.ShowTimeRange = true;
vm.ShowAvlTrucks = true;
vm.HideLocationIndicator = true;
}

This is not happening when creating a new record. I can either remove this bit from Edit, or add it to Add. Preferences?

Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov><mailto:bloodb@wsdot.wa.gov> | 360.709.8243

**Comment by joeschmit** [comment]
Not deprecated but redundant more or less, that would apply to highLocationIndicator

On Oct 9, 2019, at 11:36 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:

vm.ShowTimeRange = true; shouldn’t that be deprecated? We now have a flag in admin > feature activities > end date/time?

On Oct 9, 2019, at 11:31 AM, brianblood <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Hey Josh/Joe
Any insight on this bit of code when editing an Other Activity?

//Snow and Ice Records Are "Special"
if (vm.FeatureTypeName.ToLower() == "snow and ice")
{
vm.ShowTimeRange = true;
vm.ShowAvlTrucks = true;
vm.HideLocationIndicator = true;
}

This is not happening when creating a new record. I can either remove this bit from Edit, or add it to Add. Preferences?

Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov><mailto:bloodb@wsdot.wa.gov><mailto:bloodb@wsdot.wa.gov> | 360.709.8243

**Comment by brianblood** [comment]
So, leave HideLocationIndicator = true for snow and ice, yes?
What about ShowAvlTrucks = true?  Should that stay as well?

Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov> | 360.709.8243

**Comment by jhudsonWA** [comment]
Yes I’d say on both

Joshua Hudson
Applications Modernization Manager, Enterprise Applications
hudsonj@wsdot.wa.gov | 360.705.7778
________________________________

**Comment by joeschmit** [comment]
So the only "things" that should be on the form are the form questions themselves and anything set in the admin screen.

**Comment by jhudsonWA** [comment]
K, let me chat with Brian a bit more on this. We want to make it consistent. I think this is a case where we added flags to allow admins to disable things and there is some historical code overriding.

**Comment by joeschmit** [comment]
Ya, this one goes back for years...PDA era...

**Comment by jhudsonWA** [comment]
@brianblood did this ever get pushed out? Where do we stand on these changes (web side)

**Comment by brianblood** [comment]
Not pushed out yet.  I was rolling this fix in with the removal of vehicle selection on the iPad, since they touched the same snow and ice special case on web.
Had to re-add the changes after your work on git Friday morning, so I’m just testing it now.


Brian Blood
Mobile Application Developer
[cid:image001.png@01D496DE.F3223B40]
bloodb@wsdot.wa.gov<mailto:bloodb@wsdot.wa.gov> | 360.709.8243

**Comment by brianblood** [comment]
This is in QA, just need to test changes to the snow and ice forms to make sure they are functioning the same with my new changes.

**Comment by brianblood** [comment]
Fixed!
