### ISSUE TITLE
Police Division Admin Page - Region not Saved

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#1369]
Oai "I tried added Chehalis Tribal police to the estimates list but have no success.  After selecting a region and hitting save, Chehalis shows up on the list but the region is removed. "

**Comment by VinceRanger** [comment]
After looking into this issue, I noticed the region was going to the database using the add screen but the update screen was nulling it out. Added code to pull the region from the dropdown list box. Committed changes and releasing to QA.

**Comment by brianblood** [comment]
This has been pushed to Prod.
