### ISSUE TITLE
Can we get an Electric Charging Station Icon for the Map?

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1371]
<img width="590" alt="Screen Shot 2019-10-30 at 8 24 12 AM" src="https://user-images.githubusercontent.com/15268732/67872828-bf974380-faef-11e9-95df-38a1b70560b1.png">

**Comment by ReedHunter-Wsdot** [comment]
We can put what icons we'd like on the map assuming we have data on where they are.  I'm only seeing fuel stations in the available data.  

Are you thinking of state owned recharging stations?

**Comment by PeterBurkhard** [comment]
Yes I am thinking of State owned charging stations for now. We have some here at HQ that are incorrectly labeled Fuel Stations.

**Comment by ReedHunter-Wsdot** [comment]
I'll update the basemap with this info.  Turns out the fuel station data has a field listing the fuel types supported, and some of them support electric.

I will split the fuel station data into several basemap layers, one for each fuel type:
- Diesel
- Biodiesel
- Gas
- Electric
- Propane

**Comment by PeterBurkhard** [comment]
I love it!

**Comment by ReedHunter-Wsdot** [comment]
The bolt with a circle in it required a fairly big map icon before you could make out what it was.  For that reason I have made in the next basemap an icon of a gas pump with a capital letter 'E' over the middle instead.

Once it's ready for download, please take a look and see what you think.  I'd also be interested in your opinion of whether I should vary the colors of the symbols based on fuel type.  That would stand out better than just the letter over the fuel pump icon.

**Comment by PeterBurkhard** [comment]
Sounds good Reed!

**Comment by ReedHunter-Wsdot** [comment]
This is generated and will be available soon for testing.

**Comment by PeterBurkhard** [comment]
Nice!

**Comment by sheppamwsdot** [comment]
Nice job Reed!
