### ISSUE TITLE
UAS Remote Pilot License Certificate Number Field.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1372]
Like the Pesticide Applicator License. Can we add UAS Remote Pilot Cert # to the User Form?
![UASRIPCERTNUMBER](https://user-images.githubusercontent.com/15268732/68346781-db7b8600-00a9-11ea-981d-d6dcbfa97695.jpg)

**Comment by sheppamwsdot** [comment]
Will not be implemented at this time.
