### ISSUE TITLE
Backflow Feature and Form

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#1377]
Add backflow feature and form following 4.5 release. NWR Area 5 is looking for a point feature with multiple attributes and one form.

**Comment by sheppamwsdot** [comment]
@suttert Is this a duplicate of the item 24813 in Dev Ops?  

https://dev.azure.com/WSDOT/MaintenanceOperationsApps/_workitems/edit/24813/

**Comment by suttert** [comment]
This is a duplicate of item 24813 in Dev Ops.
