### ISSUE TITLE
Can crash by rapid map tapping on startup

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#138]
Joe could reproduce this again in HATS Beta 1.3B2, and I could reproduce on demand. Previous code changes to make the app resistant to this helped but did not prevent this.

**Comment by ReedHunter-Wsdot** [comment]
Locking out all user input between init of the UI until it finishes loading.  Tests haven't reproduced the error since writing this fix on 10/15.

**Comment by jhudsonWA** [comment]
Also confirmed in my test. I think this one is finally locked down. Good job Reed! :)
