### ISSUE TITLE
MAP LOS Reports fot CY 2019 by Region 

### ISSUE THREAD

**Issue by Shieldk** [WSDOT/HATS#1384]
There is a request from Eastern Region management for the 2019 Region MAP LOS scores. There are several MAP activities that do not have a score generated for them, and it appears to be an issue for all regions. Previous years 2017 and 2018 appear to work. Their request is to have the data by week end.

**Comment by sheppamwsdot** [comment]
This issue has been accepted and moved to DevOps.  
https://dev.azure.com/WSDOT/MaintenanceOperationsApps/_workitems/edit/26572
