### ISSUE TITLE
Test add 1/100th of milepost, updated 1/10th milepost data to basemap

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#143]
Make 2 new basemaps, one with 1/100th of milepost points and another with just 1/10th milepost points for Oai and Joe to test.
- The goal is to help crews estimate the milepost of their data entry/review
- Any basemap generated before 10/20/2015 has several year old milepost data, so the new basemap will have the latest milepost points available.
- This will also test how big the basemap grows again with all the points (around 900,000 of them) for 1/100th milepost data.
- This is an opportunity to make the milepost labels bigger

**Comment by ReedHunter-Wsdot** [comment]
Instead of making 2 basemaps, I'm making one basemap that has two milepost layers - a 1/10th of milepost points, and another that has only 1/100th milepost markers that are in between the 1/10th milepost markers.  That way you just turn off the 1/100th layer in the Toc to see what it's like without them.

**Comment by ReedHunter-Wsdot** [comment]
basemap is available for testing at \wsdot.loc\hq\public\30day\GRDO\HunterR\HATSiOS\basemapWithSensitiveAreas.  File size with the additional 100th of milepost data has doubled from 131MB to 270MB uncompressed.  Milepost label font sizes are increased by 2 points.  I attempted a while halo and white shadow off the text, but the SDK is confirmed to not support this.

**Comment by ReedHunter-Wsdot** [comment]
basemap now available for download within HATS Beta.

**Comment by ReedHunter-Wsdot** [comment]
I'm not seeing any issues in the new basemap's compatibility with current prod 1.2 HATS.

**Comment by joeschmit** [comment]
@ReedHunter-Wsdot can you make the text color a dark grey.  It might help a bit show up on the aerial images.

**Comment by ReedHunter-Wsdot** [comment]
dark grey for the milepost labels, right?

**Comment by joeschmit** [comment]
@ReedHunter-Wsdot correct.

**Comment by ReedHunter-Wsdot** [comment]
@joeschmit  Want me to make the circle symbols for the mileposts dark grey instead of black too?

**Comment by joeschmit** [comment]
@ReedHunter-Wsdot yes please.

**Comment by ReedHunter-Wsdot** [comment]
@jhudsonWA Please put the file where it can be downloaded to HATS iOS Beta.

I have built the updated basemap and copied it to \wsdot.loc\hq\public\30day\GRDO\HunterR\HATSiOS\basemap.

**Comment by jhudsonWA** [comment]
Will have to be Monday. SDO and I don't have laptop.

**Comment by joeschmit** [comment]
No problem.  Thx.

**Comment by jhudsonWA** [comment]
Basemap refreshed for Beta

**Comment by joeschmit** [comment]
This is good for now thanks.
