### ISSUE TITLE
Map highlight of identified feature

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#145]
When someone taps a feature with the identify command, it should be highlighted on the map.  The highlight is released when they either identify something else, or they close the identify command.

**Comment by ReedHunter-Wsdot** [comment]
Currently supported.  You tap an identify results cell, and the feature is highlighted.  Will enhance with a bigger selection symbol after I add support for showing the length attribute for line cells.  I'm leaving this open until I add that enhancement.

**Comment by ReedHunter-Wsdot** [comment]
Closing this out since highlighting of identifier features is now supported.  I'll open another issue that the highlight symbol will need to be bigger so people can see it more easily since that seems like a post 1.5 milestone issue.

**Comment by joeschmit** [comment]
Is this checked in?

Sent from my iPhone

On Mar 17, 2016, at 9:48 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #145https://github.com/WSDOT/HATS/issues/145.

�

**Comment by ReedHunter-Wsdot** [comment]
I checked it in weeks ago.  I'd expect it's in the latest beta.

**Comment by jhudsonWA** [comment]
The new identify? Yes it's in the latest beta

Sent from my iPhone

On Mar 17, 2016, at 9:56 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

I checked it in weeks ago. I'd expect it's in the latest beta.

�
