### ISSUE TITLE
Map feature edit UI feedback: line length

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#146]
I can make a piece of text show somewhere on the screen when guys are editing line features to show how long the total line has become.  I have the info, all I'd have to do is make a label show up with it.

**Comment by jhudsonWA** [comment]
I think this ties to #85

**Comment by ReedHunter-Wsdot** [comment]
checked in.  While adding line features or editing existing line features, UI shows length of feature in feet.  When new or edited feature is saved, the length is now passed along via the CompletedSketch object.

Note this is different than having the length appear in the identify results for features that happen to be a line.  I will close this when I have added that feature too.

**Comment by ReedHunter-Wsdot** [comment]
btw, also added lat/long UI feedback for the last vertex in a line, and for when feature happens to be a point.

**Comment by ReedHunter-Wsdot** [comment]
length in map identify results is now checked in.
