### ISSUE TITLE
[HATS Web] Add image thumbnail to "Current Records" for Feature Activities and Other

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#147]
Users like the ability to quickly browse through current records query to look for photos of specific work, adding a thumbnail image to the Current Records output table would be useful.

**Comment by jhudsonWA** [comment]
Sure, but how would we handle multiple pictures?

**Comment by joeschmit** [comment]
Maybe show 2 thumbs and a plus sign sort of thing.  

Or maybe even something simpler like a " has attachment" icon, that when clicked shows a popup with photos.  We have heard it would be "nice to have a way to see if a record has photos or attachments from the current records query"

**Comment by joeschmit** [comment]
@jhudsonWA not a priority for April 1.  Bumping out to July.

**Comment by jhudsonWA** [comment]
@brianblood: this something you can work on? 

On the features and other current records screen, update the grid with a icon to show if the record has attachments. If yes, allow them to click to show popup of the attachments. Something like:  http://hatsprod.wsdot.loc/Maintenance/management/activities/Attachments/GetAllActivityRecordAttachments but for the single record.

**Comment by brianblood** [comment]
Yup.

**Comment by brianblood** [comment]
In QA.
