### ISSUE TITLE
Dump all records from Multiple Work Activities 

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#151]
Dump all records, from the beginning of time, from Multiple Work Activities and save to Excel for seven year archive.

**Comment by jhudsonWA** [comment]
We can do this or just leave the current records up on the site but remove
Add from Web/App. Your call.

**Comment by joeschmit** [comment]
Eh, Oai can.  He needs the practice ha.

**Comment by jhudsonWA** [comment]
Easier for me ;)

**Comment by joeschmit** [comment]
Alwaysssss....

Sent from my iPhone

On Nov 6, 2015, at 11:24 AM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Easier for me ;)

On Fri, Nov 6, 2015 at 11:20 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Eh, Oai can. He needs the practice ha.
> 
> From: Joshua Hudson <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>>
> Reply-To: WSDOT/HATS <reply@reply.github.com<mailto:reply@reply.github.com>mailto:reply@reply.github.com>
> 
> Date: Friday, November 6, 2015 at 10:53 AM
> To: WSDOT/HATS <HATS@noreply.github.com<mailto:HATS@noreply.github.com>mailto:HATS@noreply.github.com>
> Cc: Joe Schmit <SchmitJ@wsdot.wa.gov<mailto:SchmitJ@wsdot.wa.gov>mailto:SchmitJ@wsdot.wa.gov>
> Subject: Re: [HATS] Dump all records from Multiple Work Activities (#151)
> 
> We can do this or just leave the current records up on the site but remove
> Add from Web/App. Your call.
> 
> On Fri, Nov 6, 2015 at 10:43 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>
> mailto:notifications@github.com>
> wrote:
> 
> > Dump all records, from the beginning of time, from Multiple Work
> > Activities and save to Excel for seven year archive.
> > 
> > �
> > Reply to this email directly or view it on GitHub
> > https://github.com/WSDOT/HATS/issues/151.
> 
> �
> Reply to this email directly or view it on GitHub<
> https://github.com/WSDOT/HATS/issues/151#issuecomment-154500178>.
> 
> �
> Reply to this email directly or view it on GitHub
> https://github.com/WSDOT/HATS/issues/151#issuecomment-154507163.

�

**Comment by jhudsonWA** [comment]
Make sure this is done soon. I am just finishing up on removing all Multiple activities support from HATS web today. Even if the current records view.

**Comment by jhudsonWA** [comment]
This won't be deployed before 1.3, I'm just prepping for it.

**Comment by tangoai** [comment]
I completed a data dump for Multiple Activities on 11/9 and again on 12/7. Data was sent to Kelly Shields.

**Comment by jhudsonWA** [comment]
Perfect.
Sent from my iPhone

Slush On Dec 8, 2015, at 7:12 AM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

I completed a data dump for Multiple Activities on 11/9 and again on 12/7. Data was sent to Kelly Shields.

�
