### ISSUE TITLE
Push HATS MobileDeviceFeedback records through GitHub API as new "issue"

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#152]
Label:  Application Feedback
Milestone:  ASAP
Assignee:  JoeSchmit or All

We can remove the email to all portion - we will be subscribed to the issues thread so we will get the emails anyways.

Joe

**Comment by jhudsonWA** [comment]
Groovy

**Comment by jhudsonWA** [comment]
This is now in QA. Please test. It will only email the whole group if the post to github fails for some reason. If all looks good I'll push the change to prod as 4.2.5 and close this issue.

For these tasks I removed the lat/long from the main feedback text since this site is public. If on our network you can click View Details to see that information.

**Comment by joeschmit** [comment]
Very cool, only thing that might be helpful is using the actual feedback message as the title, the body is great, could be hard to sift through just device IDs.  But very awesome.

On Nov 9, 2015, at 17:36, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

This is now in QA. Please test. It will only email the whole group if the post to github fails for some reason.

For these tasks I removed the lat/long from the main feedback text since this site is public. If on our network you can click View Details to see that information.

�

**Comment by jhudsonWA** [comment]
I thought about that but feedback can be long. Titles can are not made to be super long. Maybe first 150 chars?

**Comment by jhudsonWA** [comment]
Scratch that. I just tested and was able to pass a large paragraph into the title. I'll make the change.

**Comment by joeschmit** [comment]
@jhudsonWA this is great, works perfect, thank you, push it out whenever. Closed.

**Comment by jhudsonWA** [comment]
This is now in prod. Please do a test using the main HATS iOS application.
