### ISSUE TITLE
What is the WSDOT Secure password?

### ISSUE THREAD

**Issue by Maxman61** [WSDOT/HATS#180]
submitted by Chris Christiansen

**Comment by Maxman61** [comment]
Hi Chris,
WSDOT Secure password is your user name

**Comment by Maxman61** [comment]
Chris,
Password for WSDOT Secure is: the password you log-in with on your desktop computer.

**Comment by jhudsonWA** [comment]
Team: make sure you don't put sensitive info in here. This is a public page.

It's ok to log the ticket but anything such as user credentials should be communicated directly with the user outside this thread.

Sent from my iPhone

On Nov 16, 2015, at 1:12 PM, Max Schade <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Chris,
WSDOT Secure password is your user name

�

**Comment by Maxman61** [comment]
Will due,  Thanks, Mws
