### ISSUE TITLE
Milepost layer in imagery basemap

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#215]
Can we make the milepost layer standout more when using the imagery basemap?

**Comment by ReedHunter-Wsdot** [comment]
Oai, 
Please load through iTunes the basemap file "HATS-basemap.geodatabase" at \wsdot.loc\hq\public\30Day\GRDO\HunterR\HATSiOS\basemap

I have added a "hidden" basemap layer of mileposts with white symbols that are slightly more thick, giving a white halo effect around the milepost points.  I can only do this for the points and not for the milepost number labels.

If we go with this basemap change, I'll have to add some code for when visibility of the mileposts is toggled.  For now if you turn off the milepost layer, the white circles still remain.  An update to the app would also turn off the visibility of the other hidden white set of points.

**Comment by tangoai** [comment]
Reed,
I see a slight difference but I don't think it's significant enough. Would it be easy to change the mikepost labels black and the symbol be a small white dot.  I think those 2 combinations would show better on the offline and imagery basemap. Obviously it's not critical at this point but whenever you have the time.

**Comment by ReedHunter-Wsdot** [comment]
a small white dot instead of the dark grey circle would be invisible on the white background of the Wsdot basemap.  Are you thinking that we should have a white dot in the middle of the dark grey circle symbol?

**Comment by tangoai** [comment]
I was thinking a white dot with a ring of black around it. Similar to all our point features except it would be white. I think that would work well with both the offline map and the imagery basemap.

**Comment by ReedHunter-Wsdot** [comment]
I'm thinking that I should stick with the dark grey shading for the milepost labels since that shade was requested by Joe on 10/30 for issue #143.  I should have an updated basemap geodatabase for you later this morning.

**Comment by ReedHunter-Wsdot** [comment]
I have updated the basemap file at the same share as before.  Please take a look.

**Comment by tangoai** [comment]
Ok, I see it now. Yes I like that offline version! Can you make the points slightly smaller then replicate it to the imagery basemap? The only thing about the dark grey shading for the milepost label is it's hard to see it in the imagery baseman.  Can we darken it a bit? I know Joe said dark grey before but I'm going to use my size to override him.

**Comment by jhudsonWA** [comment]
"but I'm going to use my size to override him."
- LOL

Sent from my iPhone

On Dec 9, 2015, at 1:50 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, I see it now. Yes I like that offline version! Can you make the points slightly smaller then replicate it to the imagery basemap? The only thing about the dark grey shading for the milepost label is it's hard to see it in the imagery baseman. Can we darken it a bit? I know Joe said dark grey before but I'm going to use my size to override him.

�

**Comment by ReedHunter-Wsdot** [comment]
I think black labels show up better against the photos of gray roads.  I'm going to generate another basemap, this time making the white milepost layers accessible in the Toc, and I'm going to see if I can make white labels work for the white milepost layer at the same time black labels show up for the top gray milepost layer.  I'm thinking this can help if folks are in a section of orthophotos that obscure whatever label shade we pick.  The gray shade of the milepost circles plays nicer with the offline Wsdot basemap, so I'd like to stick with that even with the black labels.  I'm almost done with a new basemap demonstrating what I'm talking about, so you'll get a chance to see what I mean.

**Comment by ReedHunter-Wsdot** [comment]
Grr.  Not going to work.  The coincident labels clash, prevent both from showing up.  Black labels only then.

**Comment by joeschmit** [comment]
This is out of hand…and I feel threatened now…lol

**Comment by jhudsonWA** [comment]
Give the guy someone who reports to him and now he is the big man on campus :)

On Dec 9, 2015, at 3:47 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:

This is out of hand…and I feel threatened now…lol

**Comment by ReedHunter-Wsdot** [comment]
Oai, try the file now.

**Comment by tangoai** [comment]
I like that new version of the milepost markers and labels, I think it will work well with the world imagery basemap. Thanks Reed!

**Comment by jhudsonWA** [comment]
Reed, is this version something I should move out to the download area?
On Dec 10, 2015, at 8:10 AM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

I like that new version of the milepost markers and labels, I think it will work well with the world imagery basemap. Thanks Reed!

**Comment by ReedHunter-Wsdot** [comment]
With Oai liking it, I'd say it has passed tests.  Please go ahead and make it available for download.

**Comment by jhudsonWA** [comment]
Reopening until deployed. Just so I can track it.

**Comment by jhudsonWA** [comment]
Deployed to prod
