### ISSUE TITLE
Other Record types "Activities Report" showing no records...

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#221]
Other, “Activities Report” not working.  Export to Excel seems to work fine, but the reportsever stuff is yielding no records.  Only for “Other” types.

![hatsquery](https://cloud.githubusercontent.com/assets/884943/11746819/9b9fe4a2-9fd4-11e5-87ea-0135c9700880.JPG)
![hatsqueryreport](https://cloud.githubusercontent.com/assets/884943/11746822/9d08c30e-9fd4-11e5-91cb-1823e1085e8b.JPG)

**Comment by brianblood** [comment]
I just checked a fix into Git - ActivitiesReport was providing an undefined WSDOTFeatureNumber in the URL.  Not sure why this was suddenly breaking things, but since it's not even available to be set, I just removed it.

**Comment by jhudsonWA** [comment]
Thanks Brian. Most users just export to excel, so it's not surprising this just came up. We can push this out at any time.

**Comment by jhudsonWA** [comment]
Was deployed as part of 4.3
