### ISSUE TITLE
Investigate ArcGIS Online for the map service

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#256]
Experiment with using ArcGIS Online instead of our servers for hosting the map feature service.

**Comment by ReedHunter-Wsdot** [comment]
Published a feature service on ArcGIS Online and successfully downloaded and edited in Hats.  Next step is to (1) publish all the data from Hats in order to have an apples to apples performance comparison.  Preliminary test suggests performance will be slower from HQ using ArcGIS Online, but not necessarily slower from local sheds.  Also need to (2) figure out security access - it's different when working with ArcGIS Online, and currently has to be open to editing by the public in order for Hats to access.

**Comment by jhudsonWA** [comment]
bumping to HATS 2.0

**Comment by ReedHunter-Wsdot** [comment]
bumping to 2.5.

Issues uncovered during 2.0 testing: 
1- need to be able to administer data in an already published feature service, adding and deleting data in bulk.  ArcGIS Pro may work, or possibly some json exports from arcmap fed into service rest endpoints.  Both require time to investigate.
2- need to fix sync hang problem when adding features
3- will need to implement Oauth2 access so the feature service isn't open to anyone with an internet connection to add/delete/alter map features.

Also would still need to confirm our assumption that AGOL will work well under heavy load.  We could simulate this by coordinating about 20 or 30 iPads with edits syncing within a 10 minute window.

**Comment by jhudsonWA** [comment]
Just closing. I think with our last release we showed that we can handle the load now that we are no longer having each user create the offline geodatabases themselves.
