### ISSUE TITLE
[HATS Web]  Feature Activites > Activites Report Returns "No Records"

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#26]
Feature Activities Report is returning no records on search.  Excel export and Report Viewer both.

**Comment by jhudsonWA** [comment]
@joeschmit, @tangoai, @suttert : Further details on this one: Works fine if you don't set an activity. if you just report on a feature type it returns records. Still investigating.

**Comment by jhudsonWA** [comment]
This is now fixed in QA and will be deployed today. The problem was a combination of the new Yes/No type and showing the default values on the report. Now it shows the 'All' option for each question as it should.
