### ISSUE TITLE
Features without an activity report bug

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#291]
@jhudsonWA seeing an issue with this report, dropping SRMP data from region select filters.  Also if you do not choose an activity an hit "All" then "export to excel" it yields nill results. Show Report throws "You must choose an activity"

![screen shot 2016-01-25 at 10 59 01 am](https://cloud.githubusercontent.com/assets/884943/12561008/a910f2c4-c352-11e5-9637-0ee8e7d3b006.png)
![screen shot 2016-01-25 at 10 58 50 am](https://cloud.githubusercontent.com/assets/884943/12561010/aa2fe07a-c352-11e5-958d-fd9ea51f0e00.png)

![screen shot 2016-01-21 at 12 41 42 pm](https://cloud.githubusercontent.com/assets/884943/12560976/753f169c-c352-11e5-813d-8a2343ef47a3.png)

**Comment by jhudsonWA** [comment]
Ok, activity bug is because the report should not say “all”. This report was made to show features without a particular activity. So show me all the culverts without an inspection as an example.

Removed all. It should say [Select Activity]

**Comment by jhudsonWA** [comment]
fixed both issues and it is in production. Also noticed the same error in Activity Coverage report and fixed that as well.
