### ISSUE TITLE
(Data) Hydrant: Add/Copy Attributes

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#30]

**Comment by joeschmit** [comment]
Just got an update on the attribs for this:
-Water Meter Location (text)
-DV Location (text)
-B. Assembly (text)
-Hydrant Number (text)
-Type (text)
-Backflow Assembly Number (text)
-Notes (text)

**Comment by jhudsonWA** [comment]
These attributes are setup in Dev/QA/Prod
