### ISSUE TITLE
Modify Attributes for Noxious Weed Control - Priority

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#315]
Hey Josh,

Can we schedule a couple updates to the Noxious Weed Control roadside feature for HATS 1.5? The feature currently just has Notes and Species under Attributes and we will want to change Attributes to the following.

1) Common Name – Drop down of all noxious weed common names (I can provide this via email)
2) Legal Designation – Drop down of single choice answer: A, B, or C
3) IVM Prescription – Locked text field (not editable by user)
4) Notes

Also, is it possible to make taking a picture for a new Noxious Weed Control record (1616-Priority Infestation) a required field?

**Comment by jhudsonWA** [comment]
Yep! Assign to me here on GitHub

Sent from my iPhone

On Feb 17, 2016, at 3:42 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey Josh,

Can we schedule a couple updates to the Noxious Weed Control roadside feature for HATS 1.5? The feature currently just has Notes and Species under Attributes and we will want to change Attributes to the following.

1) Common Name � Drop down of all noxious weed common names (I can provide this via email)
2) Legal Designation � Drop down of single choice answer: A, B, or C
3) IVM Prescription � Locked text field (not editable by user)
4) Notes

Also, is it possible to make taking a picture for a new Noxious Weed Control record (1616-Priority Infestation) a required field?

�

**Comment by kechinn** [comment]
Leave a comment

**Comment by kechinn** [comment]
@jhudsonWA 
Noxious Weed List containing the Common Name selection for Question 1.
[Noxious Weed List.xlsx](https://github.com/WSDOT/HATS/files/145724/Noxious.Weed.List.xlsx)

**Comment by jhudsonWA** [comment]
This feature is now loaded into production web and attributes are setup. 

Published currently = false so that HATS-iOS 1.3 does not attempt to sync them.

**Comment by jhudsonWA** [comment]
Oops wrong feature :)

**Comment by jhudsonWA** [comment]
Attributes setup in production. Will show up in HATS iOS 1.5 and on web now.

**Comment by jhudsonWA** [comment]
Disabled Species (only 28 features had the attribute set), as it is replaced with Common Name, and only 5 of the 28 features could be migrated to common name, everything else didn't match since it was a free text box before.
