### ISSUE TITLE
New Feature Type: Zone 1 Spray - Line

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#318]
- [x] Preload existing inventory to HATS (Transactional, make show up in snapshots).
- [x] Next offline geodatabase create layers for add/edit/delete enabled.

Ability to do records against.

**Comment by jhudsonWA** [comment]
Assigned to back Keisha until we get the data

**Comment by kechinn** [comment]
@jhudsonWA 
- Name will be "Zone 1 Spray"
- I have emailed Reed with the added existing inventory in .gdb format 
- No standalone records tied to unique feature, there are existing records under 'Other'

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot FeatureTypeID is: 134

**Comment by jhudsonWA** [comment]
Database is all setup and ready on HATS side, we just need to load the features and attributes.

**Comment by jhudsonWA** [comment]
Features loaded into QA Web side.

@kechinn what attributes do you want for this feature, and out of those what ones are editable.

The geodatabase file had: 

Notes
Description (not sure how useful, all of them but a couple were 'Zone 1'
Prescription
Application Width

**Comment by kechinn** [comment]
@jhudsonWA 
Attributes:

Notes (editable)

**Comment by jhudsonWA** [comment]
This feature is now loaded into production web and attributes are setup. 

Published currently = false so that HATS-iOS 1.3 does not attempt to sync them.
