### ISSUE TITLE
New Feature Type: Zone 3 Nuisance Vegetation Control - Poly

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#320]
- [x] Preload existing inventory to HATS (Transactional, make show up in snapshots).
- [ ] Next offline geodatabase create layers (Can not add/edit/delete)

Ability to do records against.

**Comment by jhudsonWA** [comment]
Assigned to back Keisha until we get the data

**Comment by kechinn** [comment]
@jhudsonWA 
Name is "Zone 3 Nuisance Vegetation Control"  (or if too long, then "Zone 3 Nuisance Veg.")

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot FeatureTypeID is: 136

**Comment by jhudsonWA** [comment]
Database is all setup and ready on HATS side, we just need to load the features and attributes.

**Comment by jhudsonWA** [comment]
Features loaded into QA Web side.

@kechinn what attributes do you want for this feature, and out of those what ones are editable.

The geodatabase file had: 

Notes
Description (not sure how useful, all of them but a couple were 'Zone 3'
County
Acres

**Comment by jhudsonWA** [comment]
Also for this one, how i calculated the SR/SRMP may need to be updated. Not sure how big of a deal it is but it used the start point for the poly when they were calculated. Problem?

**Comment by kechinn** [comment]
@jhudsonWA No problem with calculation
Attributes:

Notes

**Comment by jhudsonWA** [comment]
This feature is now loaded into production web and attributes are setup. 

Published currently = false so that HATS-iOS 1.3 does not attempt to sync them.
