### ISSUE TITLE
New Feature Type: Noxious Weed Control General - Point

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#323]
- [x] Preload existing inventory to HATS (Transactional, make show up in snapshots).
- [x] Next offline geodatabase create layers for add/edit/delete enabled.

There will be no forms for this type

**Comment by jhudsonWA** [comment]
Assigned to back Keisha until we get the data

**Comment by kechinn** [comment]
@jhudsonWA 
Name is "Noxious Weed Control General"

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot FeatureTypeID is: 137

**Comment by jhudsonWA** [comment]
Database is all setup and ready on HATS side, we just need to load the features and attributes.

**Comment by jhudsonWA** [comment]
Features loaded into QA Web side.

@kechinn what attributes do you want for this feature, and out of those what ones are editable.

The geodatabase file had:

Notes
Description
County
Prescription
Designation

**Comment by kechinn** [comment]
@jhudsonWA @ReedHunter-Wsdot 

Attributes:
1) Common Name – Drop down of all noxious weed common names (editable; first column of excel sheet) [Noxious Weed List.xlsx](https://github.com/WSDOT/HATS/files/186955/Noxious.Weed.List.xlsx)
2) Legal Designation – Drop down of single choice answer: A, B, or C (editable)
3) Control required in this location? - Yes/No (editable)
4) Notes (editable)

**Comment by jhudsonWA** [comment]
This feature is now loaded into production web and attributes are setup. 

Published currently = false so that HATS-iOS 1.3 does not attempt to sync them.
