### ISSUE TITLE
New Feature Type: Landscape Maintenance - Poly

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#325]
- [x] Preload existing inventory to HATS (Transactional, make show up in snapshots).
- [ ] Next offline geodatabase create layers for (can't add/edit/delete)

**Comment by jhudsonWA** [comment]
Assigned to back Keisha until we get the data

**Comment by kechinn** [comment]
@jhudsonWA 
Name is "Landscape Maintenance"

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot FeatureTypeID is: 138

**Comment by jhudsonWA** [comment]
Database is all setup and ready on HATS side, we just need to load the features and attributes.

**Comment by jhudsonWA** [comment]
Features loaded into QA Web side.

@kechinn what attributes do you want for this feature, and out of those what ones are editable.

The geodatabase file had:

Name
Acres

**Comment by kechinn** [comment]
@jhudsonWA @ReedHunter-Wsdot 
Attribute(s):
Notes (editable)

**Comment by jhudsonWA** [comment]
This feature is now loaded into production web and attributes are setup. 

Published currently = false so that HATS-iOS 1.3 does not attempt to sync them.
