### ISSUE TITLE
Add "Site Name" Attribute to Liquid Deicier Tank, Sand Storage Facility and Salt Storage Facility

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#330]
Please add the "Site Name:" selection list attribute below as an attribute to Liquid Deicer Tank, Salt Storage Facility, Sand Storage Facility.  
![image](https://cloud.githubusercontent.com/assets/884943/13237012/359bd052-d97d-11e5-9eec-eeba9f4d2360.png)

**Comment by jhudsonWA** [comment]
Can you send me this list as an excel list. Otherwise I have to type these all out.

**Comment by jhudsonWA** [comment]
@joeschmit  Can you send again. Replying to github message does not upload attachments so it didn't come through

**Comment by jhudsonWA** [comment]
Loaded in Dev, QA and Prod
