### ISSUE TITLE
HATS Web When trying to set “Feature Attributes” - “Is Required = True” Exception Message:

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#356]
When trying to set “Feature Attributes” - “Is Required = True”

![screen shot 2016-04-01 at 6 35 18 am](https://cloud.githubusercontent.com/assets/884943/14208418/184a01c0-f7d4-11e5-91bc-835a6db073cf.png)

Exception Message: Procedure or function usp_HATS_UpdateRoadsideFeatureDisplayAttributeFlags has too many arguments specified. Session Variables: KeepAlive = 4/1/2016 6:33:08 AM FromHATS = True ActivityID = FeatureTypeId = 113 Stack Trace: at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at HATS.Classes.DataLayer.AdminDC.UpdateRoadsideFeatureDisplayAttributeFlags(String displayName, Nullable`1 roadsideFeatureDisplayAttributeId, Boolean viewOnWeb, Boolean viewOnMobile, Boolean allowEdits, Boolean isRequired)

**Comment by brianblood** [comment]
Updated stored proc to accept new arguments.
