### ISSUE TITLE
let managers set zoom level where Hats map features turn on

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#372]
Allow managers to set how tight the map zoom has to be when Hats map layers become visible.  Each Hats feature type should be set separately. This will not affect the basemap layers.

Use case: need to find the next nearest feature of a certain type.
 Steps: 1) start at a feature
  2) pinch zoom out until you see the next one down the road
  3) pinch zoom in
Unfortunately, they disappear once you zoom out at step 2 so you can't get to step 3.

**Comment by jhudsonWA** [comment]
For this one, what would you like to see: An int, or.. Meaning what should you get passed. A resolution text, a number, a string, a picture of puppies? 🐶

**Comment by ReedHunter-Wsdot** [comment]
int.  kittens and puppies would be nice too.  Expecting a range between 0 and 2000000, though most practical will be beween 1000 and 500000.  That's a lot of puppies and kittens, but happily just one int each.

**Comment by jhudsonWA** [comment]
Ok, can do. :)

Thanks!

**Comment by jhudsonWA** [comment]
What should be the current default for existing features?

**Comment by jhudsonWA** [comment]
Oh and you mentioned range. Do you need a min, max or is it just a single int between 0 and 2000000

**Comment by ReedHunter-Wsdot** [comment]
It would probably be good to have a min/max range for valid user input since I'm not sure what the SDK would do if you threw at it a value <= 0.  When zoomed out to see the entire state of Washington, the scale is 1:4,500,000.  Those could all be valid ranges in theory.  In practice, the number is between 1000 and 500000, way closer to 0 than to a large number.  The idea is to keep the map from showing too much data when you're zoomed out so the device stays responsive.  

Current default is 20,000.

**Comment by jhudsonWA** [comment]
Yesterday I added a column MobileMapInitialDisplayZoomLeve(int) to the LocalFeatureType table. So that would be 20,000? Would that be considered a min or a max in your example?

On Apr 21, 2016, at 9:27 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

It would probably be good to have a min/max range for valid user input since I'm not sure what the SDK would do if you threw at it a value <= 0. When zoomed out to see the entire state of Washington, the scale is 1:4,500,000. Those could all be valid ranges in theory. In practice, the number is between 1000 and 500000, way closer to 0 than to a large number. The idea is to keep the map from showing too much data when you're zoomed out so the device stays responsive.

Current default is 20,000.

**Comment by ReedHunter-Wsdot** [comment]
Neither.  20,000 is the default scale dependent threshold.   Let's have a valid range of between 1000 and 4,500,000.

**Comment by jhudsonWA** [comment]
I’m confused. :) Let’s chat about this today.

On Apr 21, 2016, at 9:45 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Neither. 20,000 is the default scale dependent threshold. Let's have a valid range of between 1000 and 4,500,000.

**Comment by jhudsonWA** [comment]
Ok, got it. So there is now a property on LocalFeatureType called: mapDefaultScaleThreshold. Can be nil or have a int. 

Current status is this is in the iPad and on the server. Still need to build the admin screens to allow Joe's team to edit.

**Comment by jhudsonWA** [comment]
Assigning to you so you can read the value and set the scale on app load.

**Comment by ReedHunter-Wsdot** [comment]
Map layers, identify command button enabling, and current location reset button now all respond to the mapDefaultScaleThreshold.  Code is checked in.
Test passed using guardrail at 40000 scale.

Now we just need the admin web UI.

**Comment by jhudsonWA** [comment]
Nice. Feel free to close this issue then as I created a new issue for web admin changed and assigned to Brian Blood yesterday. #380

Thanks!

Sent from my iPhone

On Apr 22, 2016, at 11:59 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #372https://github.com/WSDOT/HATS/issues/372 to @jhudsonWAhttps://github.com/jhudsonWA.

�
