### ISSUE TITLE
Update ESA/GHPA Popups

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#373]
Brian / Josh

Regarding the task to integrate ESA/GHPA into HATS… I have been working with Oai on this… and have one task to run by you:

See the attached screen shot of the pop up window for an ESA reporting record… can you revise to the language to the following (separate paragraphs):

If this work triggers an HPA permit [work in water or on bridges over waters of the state] then document the record using the HPA compliance reporting.

You are entering an ESA 4(d) reporting record for soil disturbing work that could impact water occurring in or near sensitive areas and buffers.  Documenting such work is a requirement of WSDOTs ESA 4d coverage.

Please confirm when this is complete.  Thanks

**Comment by jhudsonWA** [comment]
Done on iPad
![simulator screen shot apr 20 2016 9 08 42 am](https://cloud.githubusercontent.com/assets/702446/14681852/bc88069e-06d7-11e6-8015-4912fa4bc494.png)

**Comment by jhudsonWA** [comment]
And web is also changed: 

![screen shot 2016-04-20 at 9 24 21 am](https://cloud.githubusercontent.com/assets/702446/14682292/c6cf7da6-06d9-11e6-80fe-3a8f223edc27.png)
