### ISSUE TITLE
Data: Remove unused columns from the schema, app where appropriate 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#376]
The following columns are never used on the web or iPad. Can you work to remove them from the database model?

MetricGroup:

MetricGroupShortName
MetricGroupDescription

Parameter:

ParameterDescription

ActivityDefinition:

ActivityDescriptoin:
**_Used in the CTS application**_, only remove this one from the Feature Activity Admin page, not the schema.

**Comment by jhudsonWA** [comment]
This one grew. Brian is removing all the unused things.

**Comment by brianblood** [comment]
The code and stored procs are all updated and ready for column dropping goodness.  Working with data modelers to modify the database schema.

**Comment by jhudsonWA** [comment]
this change deployed in QA. I think we are ready for prod on monday when 5.0 ships.
