### ISSUE TITLE
Add Document Library Screen

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#388]
New screen on iPad. Would show all files Joe's team want to display to users. Allow them ability to hit download, download file and present system open in dialog so they can save the file wherever they want.

**Comment by jhudsonWA** [comment]
From @joeschmit : Series of weblinks to files, that can be downloaded on sync, such as our common safety documents, manuals etc.

**Comment by jhudsonWA** [comment]
Done. Added to 2.0B2 (uploaded to /beta)

Screen is there, links sync from server. Last part needed is #390  (web editor)

**Comment by jhudsonWA** [comment]
Still need to add better network error detection

**Comment by joeschmit** [comment]
CLOSED!
