### ISSUE TITLE
(HATS iOS) Map Search Functionality 

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#4]
> Users want to be able to find a feature based on a feature id search string via map view on iOS

Making this a more broad feature request:
1. Allow for search of a feature by feature number
2. Allow for search of all feature in a state route / mile post range
3. Allow for search of features by type
4. More...?

**Comment by ReedHunter-Wsdot** [comment]
fyi, UI will support launching activities, deleting, etc. from the search results just like the map identify results.

**Comment by jhudsonWA** [comment]
Local DB Support for Search by Feature Number is checked in.

RoadsideFeatureRepository.getRoadsideFeatureByExactAssetReferenceTextOrNumberOnly("12345")
RoadsideFeatureRepository.getRoadsideFeatureByExactAssetReferenceTextOrNumberOnly("WSDOT0000012345")

Need to checkout latest and do a sync for search only by asset text or number to work. Had to add a new column for every feature and this bumps the schema version to 26.

**Comment by ReedHunter-Wsdot** [comment]
Completed and added to beta for testing.
