### ISSUE TITLE
Sort File Library by region, area and org code

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#419]

**Comment by jhudsonWA** [comment]
This can be ready for 2.0. 1.6 will include the File Library as is today.

**Comment by jhudsonWA** [comment]
@joeschmit Quick question. For this: Is orgcode needed or does region and area capture the filters you would need? I have added orgcode support to the database but since Maintenance orgcode's contain region and area (the first 4 numbers) the one extra bit of info it would get you is shed level files.

**Comment by jhudsonWA** [comment]
Example of first change to support this: Files will show the Region/Maint area they belong to. With a Region filter at the bottom.

![screen shot 2016-06-07 at 5 57 43 pm](https://cloud.githubusercontent.com/assets/702446/15879486/7816df76-2cd9-11e6-80b6-f236d9e2cac4.png)

**Comment by joeschmit** [comment]
Region and Area is fine for now...

Sent from my iPhone

On Jun 7, 2016, at 5:58 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Example of first change to support this: Files will show the Region/Maint area they belong to. With a Region filter at the bottom.

[screen shot 2016-06-07 at 5 57 43 pm]https://cloud.githubusercontent.com/assets/702446/15879486/7816df76-2cd9-11e6-80b6-f236d9e2cac4.png

�

**Comment by jhudsonWA** [comment]
Great. I’ll leave the orgcode column just in case we want it in the future, but won’t enable it in the UI (iPad or Admin Page).

On Jun 8, 2016, at 8:04 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:

Region and Area is fine for now...

Sent from my iPhone

On Jun 7, 2016, at 5:58 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:

Example of first change to support this: Files will show the Region/Maint area they belong to. With a Region filter at the bottom.

[screen shot 2016-06-07 at 5 57 43 pm]https://cloud.githubusercontent.com/assets/702446/15879486/7816df76-2cd9-11e6-80b6-f236d9e2cac4.png

�

**Comment by Deb-Achord** [comment]
I am glad you are leaving the orgcode column as that will be a request from some I'm sure...  all these refinements are great!

**Comment by jhudsonWA** [comment]
iPad side is done as of next beta (Beta 9, which is now on /beta). Working on updating admin screens next.

![simulator screen shot jun 8 2016 8 59 05 am](https://cloud.githubusercontent.com/assets/702446/15901267/729af19e-2d57-11e6-8237-cc67ea71cbfa.png)

![simulator screen shot jun 8 2016 8 58 53 am](https://cloud.githubusercontent.com/assets/702446/15901300/9969df4c-2d57-11e6-817f-6f2de4f9454a.png)
