### ISSUE TITLE
Map feature transparency

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#426]
Is it possible to create a transparency/opacity slider? Or increase transparency of polygons when viewing aerial? That way users don't have to turn on/off to view underneath feature.

**Comment by PeterBurkhard** [comment]
That would be sweet....

**Comment by jhudsonWA** [comment]
This requires app changes. Bumping to next major release after 2.0. 2.0 is getting full with 1 month to go.

**Comment by ReedHunter-Wsdot** [comment]
How about a transparency toggle button we put on all TOC layers?  When tapped it would switch that layer between 100% opacity and say 60%.  I could put it on the TOC category cell as well.

**Comment by kechinn** [comment]
Can we do the toggle button just for polygons for now to see what it looks like? Not sure we need transparency for point and line features.

**Comment by jhudsonWA** [comment]
This seems old, bumping to 4.0 to keep alive but is it still needed?

**Comment by jhudsonWA** [comment]
Closing per @joeschmit. No longer needed.
