### ISSUE TITLE
Width of Zone 1 and Zone 2 lines

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#427]
Hey Reed, can we make the Zone 1 and 2 lines thinner? Since they are just about everywhere they can cover up a lot on map.

**Comment by ReedHunter-Wsdot** [comment]
Can do.

**Comment by ReedHunter-Wsdot** [comment]
@kechinn, @tangoai, please take a look at the latest beta features map, and let me know if you want me to adjust width again on Zone 1 and Zone 2 lines.  I think Josh made a new beta available last night.  You will need it otherwise Hats won't let you see the new features map.

**Comment by ReedHunter-Wsdot** [comment]
done
