### ISSUE TITLE
Add "Map" capability for records via web query

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#431]
-Add a "Map" button for Current Records, Pending Activities, Activities Report and Features without an Activity for Feature and Other Record Types
-When user clicks the point or line it gives the record data in the popup

**Comment by jhudsonWA** [comment]
It's time for this one. I've added to 5.6. Goal for end of October.

**Comment by joeschmit** [comment]
Thank you!

**Comment by sheppamwsdot** [comment]
Has been moved to Dev Ops
