### ISSUE TITLE
TOC Bug when switching from WSDOT Offline basemap to Online Basemaps

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#438]
When switching between WSDOT Offline basemap to any of the online basemaps, almost all of the basemap features, except for Hydrant, are toggled on and off in TOC. After doing this, I have noticed another issue with both milepost layers. The glitch can cause the both or one or the other mileposts to still show even when eye toggled off.

**Comment by ReedHunter-Wsdot** [comment]
fix checked in
