### ISSUE TITLE
[HATS Web] Attempting to Edit Current Records, on Save getting Error

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#44]
Attempting to Edit Current Records, on Save getting Error:

Log Type    Note    Date    User
Exception   Exception Message: Procedure or function 'usp_HATS_UpdateLocation' expects parameter '@BeginSRMP', which was not supplied. Session Variables: FromHATS = True ActivityID = FeatureTypeId = 103 CurrentActivityRecordsSearchResults = SavedScreenValues-Other-Records = System.Collections.Generic.Dictionary`2[System.String,System.String] Stack Trace: at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at HATS.Classes.DataLayer.AddEditRecordDC.UpdateEventRecord(Int32 eventId, Nullable`1 userId)

**Comment by jhudsonWA** [comment]
Fixed in production.
