### ISSUE TITLE
Prompt To Sync After 1 Week

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#444]
Prompt users to sync devices (redirect to sync screen) on start if user is:
1. Connected to WSDOT network (vpn or wifi)
2. Have not synced in over a week
3. Have not showed this prompt yet for the current day

**Comment by jhudsonWA** [comment]
![simulator screen shot may 25 2016 4 19 29 pm](https://cloud.githubusercontent.com/assets/702446/15559769/ee3694a2-2299-11e6-80ea-f082534b388c.png)

Done

**Comment by PeterBurkhard** [comment]
I like it.
