### ISSUE TITLE
Mobile Dashboard

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#445]
- This is mostly feature totals based on Area/Region/State
- Features without an Activity/Activity Coverage Report

**Comment by jhudsonWA** [comment]
Shooting for 2.0 if time allows (it probably won't..) 👍

**Comment by jhudsonWA** [comment]
This is looking more like a 2.5 thing with roughly 3 weeks until 2.0 launch.

**Comment by joeschmit** [comment]
Ya bump it back

Sent from my iPhone

On Jun 9, 2016, at 11:24 AM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

This is looking more like a 2.5 thing with roughly 3 weeks until 2.0 launch.

�

**Comment by jhudsonWA** [comment]
Closing per @joeschmit. Will reopen when we can redesign this effort.
