### ISSUE TITLE
New Feature Type: Map Survey 2016

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#447]
Keisha will/has given to the data to @ReedHunter-Wsdot

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot RoadsideFeatureTypeId = 140

**Comment by jhudsonWA** [comment]
Setup in Dev and QA on Commitment Activities side. Just need to load data.

**Comment by ReedHunter-Wsdot** [comment]
Data loaded in QA and available for testing in the latest map.  Will need the latest beta (from last night) in order to test.
