### ISSUE TITLE
New Feature Type: Map Survey 2016 - Bridge

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#448]
Keisha has/will give the data to @ReedHunter-Wsdot

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot RoadsideFeatureTypeId = 139

**Comment by jhudsonWA** [comment]
Setup in Dev and QA on Commitment Activities side. Just need to load data.

**Comment by ReedHunter-Wsdot** [comment]
Is this point or line data?

**Comment by jhudsonWA** [comment]
You have the data file right? Can you look?

On Jun 6, 2016, at 10:55 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this point or line data?

**Comment by ReedHunter-Wsdot** [comment]
(forehead smack) no I need everything spoon fed apparently

**Comment by jhudsonWA** [comment]
;)

On Jun 6, 2016, at 11:01 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

(forehead smack) no I need everything spoon fed apparently

**Comment by ReedHunter-Wsdot** [comment]
@kechinn Do you know a TOC Category to which this and the other map survey layer should be assigned?  Roadside Features?

**Comment by tangoai** [comment]
Put them under "Other"

**Comment by jhudsonWA** [comment]
Forgot to send earlier both features have been loaded into QA Web. Will need to be loaded to QA map service before field tested.

**Comment by ReedHunter-Wsdot** [comment]
Data is loaded into the latest beta map, and is ready for testing.
