### ISSUE TITLE
[HATS iOS] Update application for iOS 9 support.

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#45]

**Comment by jhudsonWA** [comment]
Will close after final testing with iOS 9. Keynote is Sep 9.

**Comment by joeschmit** [comment]
status update?  @jhudsonWA

**Comment by jhudsonWA** [comment]
The GM passed all my tests. Would love for your team to sign off. Does anyone over there have iOS 9 yet? Lands for all on Wednesday.

**Comment by jhudsonWA** [comment]
I'll push out a new beta now, has the forced re-download for 500 errors
