### ISSUE TITLE
New Feature Type: Bridge

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#450]
Load from BPO inventory data on GIS workbench.

**Comment by jhudsonWA** [comment]
current status: GIS Data office is working with Jason to get ETL to load current data. Once I hear it is complete we will start process to get it into HATS.

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot : Roadside Feature Type Id = 2

**Comment by joeschmit** [comment]
@jhudsonWA just confirming we will also load any/all attributes?

**Comment by jhudsonWA** [comment]
That is the plan. Looking at the current workbench data they have: object_Id, structure_id, bridge_no, SR, direction indicator, ARM Beg/End, SRMP Beg/End, AB indicator, Lat/Long Beg/End, Crossing Description, Facilities_Carried, Feature_Intersected, Length, Vertical Clearance Max/Min, Actual Deck Max/Min, On or Under Bridge, And Shape information.

**Comment by ReedHunter-Wsdot** [comment]
now this data I don't have.  Safe to assume these will be line features?

**Comment by ReedHunter-Wsdot** [comment]
on 2nd thought, will sift workbench to see.

**Comment by jhudsonWA** [comment]
Line yes, it's in the workbench now, but don't load yet. BPO is working to refresh data there.

Sent from my iPhone

On Jun 6, 2016, at 11:44 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

now this data I don't have. Safe to assume these will be line features?

�

**Comment by jhudsonWA** [comment]
Talked with Jason S. He was just given a new view today. Should have it in test tomorrow or wednesday and I'll use it to pull the QA data.

**Comment by jhudsonWA** [comment]
Bridge data is now loaded in Production. By doing it tonight that saves us over an hour Monday morning while the load script ran. 

For now I left the bridge feature type turned off so that our current users don't have to sync 3700+ bridges and 25,000+ attributes. They will get them with 2.0 on Monday.
