### ISSUE TITLE
Web: Ability to "build a report"

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#452]
@brianblood : Get more details from @joeschmit and team.

**Comment by jhudsonWA** [comment]
So @joeschmit , it seems we never did get more details form yourself and team on this one. Can it be bumped to 5.5 and discussed when we talk about next versions?

**Comment by joeschmit** [comment]
Of course.  We are meeting tomorrow afternoon so I’ll have the “what” answered.  I’ll get something on the books with you guys following.
