### ISSUE TITLE
[HATS iOS]  Add ability to launch "Other" Record Type from Map View...

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#46]
Add ability to launch any "Other" Record Type from Map view by simply tapping + hold and release on any location on the map.  The lat/long of the point could populate SRMP data if it was near.  Would also drop a pin or symbol at that location and have similar (i) identify task functionality.

**Comment by ReedHunter-Wsdot** [comment]
Is there a Wsdot ID associated with Other records?  A milepost and SR?  My recommendations on this depend on the answer to that question.

**Comment by jhudsonWA** [comment]
WSDOT numbers no, sr/srmp maybe. Depends on the record

Sent from my iPhone

On Jul 18, 2016, at 10:46 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there a Wsdot ID associated with Other records? A milepost and SR? My recommendations on this depend on the answer to that question.

�

**Comment by ReedHunter-Wsdot** [comment]
The most simple UI is to add an "Other" entry in the [+] button panel's list of features, showing up alphabetically such as between Noxious Weed Control Group and Pavement Markings.

Do we want our crews to only add new Other records from the map, or do we want them to delete/update existing Other records from the map?
