### ISSUE TITLE
Set statewide extent for MAP layers

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#464]
Could we set the two MAP layers to be viewable in HATS even when zoomed out to a statewide extent?

**Comment by jhudsonWA** [comment]
You would just have to set their threshold to a high enough number using admin tools

Sent from my iPhone

On Jun 6, 2016, at 6:20 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:

Could we set the two MAP layers to be viewable in HATS even when zoomed out to a statewide extent?

�
