### ISSUE TITLE
New Nightly Job: Identify Possible unknown repair cost estimates matches

### ISSUE THREAD

**Issue by Deb-Achord** [WSDOT/HATS#469]
system to look for potential matches to unknown K-jobs 

it would notify final reviewer of a potential collision report match, but would require an individual to verify the match

**Comment by jhudsonWA** [comment]
@joeschmit  will make final call on where this lands, but it is something we have wanted to do for years. Have a nightly process keep an eye on collision reports for our unknown RCEs and identify potential matches based on date/time, close location etc.

**Comment by jhudsonWA** [comment]
Set as Web 5.5 for now.

**Comment by jhudsonWA** [comment]
@kechinn This is something Deb wanted to do for years. See comments above. Still something we need or should we revisit when we dive further into K's next year (iPad version, web mvc upgrades)

**Comment by kechinn** [comment]
@jhudsonWA Still sounds like a good one to me! It might be good to revisit when we start working on mapping K's on the iPad next year, with more accurate spatial locations. I'd like to brainstorm on how we will go about mapping and recording K jobs - damage to assets in feature inventory vs other third party damage, etc. which might affect on filtering potential matches.

**Comment by jhudsonWA** [comment]
Setting to web 6.5
