### ISSUE TITLE
iOS Sync failing when record has photo attachment see error screenshot

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#470]
in Beta 2B10...

Action: LogMessage • Device Name: GiantHogweed • Device Model: iPad Pro • Device System Version: 9.3.2 • Application Version: HATS-iOS.beta 2.0B10 • Message: Sync Complete With Errors • Log: 06-10-2016 06:31:52 AM: Attachment (IMG_0062.JPG) Could Could Not Be Saved To The Server For Server Activity Record Id 276744. URL: http://hatsqa.wsdot.loc/Maintenance/Management/Activities/Attachments/AddMobileEventAttachment, Error Message: The data couldn’t be read because it isn’t in the correct format. 06-10-2016 06:31:50 AM: Saving Attachment (IMG_0062.JPG) To The Server For Server Activity Record Id 276744. 06-10-2016 06:31:50 AM: Feature Activity Record: Culvert - Cleaning (WSDOT0001261618) [06-10-2016 06:31 AM] Saved To The Server. Server Feature Activity Record 276744. 06-10-2016 06:31:49 AM: 2 Activity Record Attachments To Sync 06-10-2016 06:31:49 AM: 1 Feature Activity Record To Sync 06-10-2016 06:31:49 AM: Number of Days Since Last Sync: 0 06-10-2016 06:31:49 AM: Starting Sync (BETA)...

![img_0064](https://cloud.githubusercontent.com/assets/884943/15965914/835fe4a6-2ed5-11e6-9612-3572818d900f.PNG)

**Comment by PeterBurkhard** [comment]
Cool

**Comment by jhudsonWA** [comment]
This was due to the server needing to be updated to account for some of the empty database fields removed and an error message being thrown when the attachments associated event was pulled. I updated the code to no longer look for the removed columns and sync completed fine.
