### ISSUE TITLE
[HATS iOS]  If sync completes with errors, popup needs to better highlight failure...

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#48]
If sync completes with errors, popup needs to better highlight failure, such as bold/red text.  Users were easily overlooking popups that had sync errors.  Also recommend language changes such as:  "SYNC FAILED!  See the log for more details.  Contact IT Support."

**Comment by jhudsonWA** [comment]
Done for 1.1
![Screenshot](https://cloud.githubusercontent.com/assets/702446/8853877/c10067bc-3111-11e5-9657-4ef3bafcbb32.png)
