### ISSUE TITLE
Labor and Police Division Lists

### ISSUE THREAD

**Issue by Deb-Achord** [WSDOT/HATS#483]
Ability to hide policy divisions and labor based on org code like the equipment works so elegant or maybe just a simple alphabetical sort :)

**Comment by kechinn** [comment]
Police Divisions not based on orgcode.

**Comment by jhudsonWA** [comment]
I think deb's thought on this was the ability to only show applicable police devisions for a given area, so they don't have to see the full list everywhere in the state.

Sent from my iPhone

On Apr 24, 2017, at 7:16 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Police Divisions not based on orgcode.

**Comment by kechinn** [comment]
Right. Although the way its set up now it's just the name, not attached to area or org. Is this something that can be added? If so, I can go through the list and clean it up and associate each with an area as needed.

**Comment by jhudsonWA** [comment]
Yes, that was what she intended we do. A lot of these are like one lines as that was how Deb logged things, but there usually was good motive behind them. :) Assign to me and I’ll add it to the list. I do think this one in particular would be a great addition.

On Apr 24, 2017, at 8:01 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Right. Although the way its set up now it's just the name, not attached to area or org. Is this something that can be added? If so, I can go through the list and clean it up and associate each with an area as needed.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Add this one to the work list. Now that you are working on the estimate side of HATS. This would be Estimates Admin: Police Divisions. What we would want is to store the Region # and Maintenance Area Number for each Police Division in the admin list. Next step would be to update the Add/EditKJob.aspx pages to only show Police Divisions in the users area, with a button that would show all (like SR and County on that page)

**Comment by jhudsonWA** [comment]
Complete will roll out with 5.6 along with new UI
