### ISSUE TITLE
KJob Admin Distribution List Creation And Link

### ISSUE THREAD

**Issue by Deb-Achord** [WSDOT/HATS#488]
A email group that would go to the admin types for record undeletes, adding police divisions and enhancements... perhaps a button on the form; we can flesh this out better during one of our meetings...

**Comment by jhudsonWA** [comment]
We can easily add a KJob Admin distribution email list. Let us know on here where to place a button or link.

**Comment by jhudsonWA** [comment]
These types of requests are going to be handled by @joeschmit's office for now. Closing. We can create another mailing list if needed.
