### ISSUE TITLE
TRAINS interface

### ISSUE THREAD

**Issue by Deb-Achord** [WSDOT/HATS#489]
we have the interface to pull actual dollars from the TRAINS - WORD table could this be expanded to include actual hours as well?

**Comment by jhudsonWA** [comment]
Good question, let me look at what comes back in our Trains webservice and see if hours are available.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot We currently have a web service in HATS. This task would be to look at the response and see if there is a way to pull hours as well as the current dollars.

**Comment by lundyc-wsdot** [comment]
The only numeric return appears to be the expenditures.  The answer lies in the data available to the service and the willingness to alter it if hours are internally available.

## 

Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
Thanks for checking.  We can close this then. It’s not worth opening that can of worms.

On Sep 8, 2016, at 9:34 AM, lundyc-wsdot <notifications@github.com<mailto:notifications@github.com>> wrote:

The only numeric return appears to be the expenditures. The answer lies in the data available to the service and the willingness to alter it if hours are internally available.

## 

Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge." -- Daniel J. Boorstin
