### ISSUE TITLE
table view

### ISSUE THREAD

**Issue by Deb-Achord** [WSDOT/HATS#490]
A view that would allow deb to see records that are in the table doesn’t need costs associated just the records on the main table ( in case something happens like it did this week so I can review and not have to rely on Josh or Brian when they may not be available )

**Comment by jhudsonWA** [comment]
@Deb-Achord Get https://msdn.microsoft.com/en-us/library/mt238290.aspx installed by your IT support staff and we can get you read only access to the estimates database plus give you a few SQL queries you can run

**Comment by jhudsonWA** [comment]
If someone wants to do this I'd rather they do it using SSMS instead of a web view for a single user or several users.
