### ISSUE TITLE
Training Site

### ISSUE THREAD

**Issue by Deb-Achord** [WSDOT/HATS#491]
currently we use the qa site for training the data is quite old....  
ability to do an occasional refresh that would include:
1. some of the more current k's (not all the data) 
2. rates from the tables
3. the ability to have the permissions/user rights be assigned to one person easily for the purpose of the training, so folks outside the training are not getting random emails :)

**Comment by jhudsonWA** [comment]
QA should be enough for this. We can refresh if "newer" data is needed.
