### ISSUE TITLE
Change attribute wording for Cable Barrier feature type

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#493]
Begin/End Type (essentially removing redundant language):
- Other
- Tie to thrie beam bull nose
- Tie to w-beam
- Tie to bridge
- Specific to manufacturer

**Comment by jhudsonWA** [comment]
Done in production and beta. Please sync to see changes. Also updated the previous features that had set attributes to previous values. Was only a couple of features so sync should stay fast.
