### ISSUE TITLE
Data: Restore Culverts In Production

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#494]
@ReedHunter-Wsdot when you get any free time over the next week can you please re-add these culverts. They should be in the snapshots now. 

WSDOT0000836150
WSDOT0000836151
WSDOT0000836152
WSDOT0000582866
WSDOT0000582867
WSDOT0000582868
WSDOT0000582869
WSDOT0000836153
WSDOT0000582871
WSDOT0000582859
WSDOT0000836154
WSDOT0000582858
WSDOT0000784255
WSDOT0000582856
WSDOT0000784258
WSDOT0000784259
WSDOT0000784260
WSDOT0000784261
WSDOT0000784262
WSDOT0000784263
WSDOT0000784270
WSDOT0000784271
WSDOT0000784272
WSDOT0000784273
WSDOT0000784274
WSDOT0000784275
WSDOT0000784277
WSDOT0000031797
WSDOT0000030116
WSDOT0000030115
WSDOT0000030113
WSDOT0000030098
WSDOT0000030110

**Comment by ReedHunter-Wsdot** [comment]
done with one exception: WSDOT0000582869 didn't show up among points or lines.

**Comment by jhudsonWA** [comment]
You are correct. Missed this one on my side. Should be in the snapshots now

**Comment by ReedHunter-Wsdot** [comment]
This is resolved, and happens to be included in the 2.0 feature service.
