### ISSUE TITLE
(HATS iOS) Ability to filter SR list based on Region > Area

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#5]
(HATS iOS) Ability to filter SR list based on Region > Area

**Comment by jhudsonWA** [comment]
Worked with DBA's yesterday and we know have the source data we need in all environments. This work has been bumped up from 1.5 to 1.3

**Comment by jhudsonWA** [comment]
Boom! 
![screen shot 2015-10-27 at 11 26 08 am](https://cloud.githubusercontent.com/assets/702446/10774936/cb6facca-7cc1-11e5-9052-c707e04178a2.png)

Shipped as 1.3B5
