### ISSUE TITLE
[Data] Provide High Res Ortho files for areas where data is available. 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#500]

**Comment by ReedHunter-Wsdot** [comment]
Experimentation with high resolution Orthos can begin in about 2 weeks.  I'm for now using that server to generate fixed Naip 2015 tile packages - ones that no longer have slivers of images from adjacent maintenance areas, or cut off images where a maintenance area's boundary runs right on the edge of an SR.

**Comment by sheppamwsdot** [comment]
Add to backlog

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
