### ISSUE TITLE
Attachments: Allow edits on Attachment Description on feature/other record add/edit

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#521]

**Comment by jhudsonWA** [comment]
see #520

**Comment by brianblood** [comment]
Done - added ability for record creator to edit the description of attachments on Edit only.  The process for adding an attachment did not lend itself to adding descriptions, but all adds should be done in the field on the device, so this is not terribly important.

**Comment by joeschmit** [comment]
@brianblood, thanks.
