### ISSUE TITLE
Features Hidden On Web: Hide from map and search

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#528]
Features that are hidden on web: show up in TOC as layer name and still show up on map and search.

**Comment by jhudsonWA** [comment]
When a feature is hidden on web it will no longer be included in  the localfeaturetype table on device. So yo could use that to decide if they should show up in these areas.

**Comment by ReedHunter-Wsdot** [comment]
The test for excluding a layer from the map and Toc will be whether it's missing from the localFeatureType table.
