### ISSUE TITLE
Convert basemap to vector basemap

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#542]
After upgrading HATS to use the Esri Quartz upgrade, convert the Offline basemap to be a vector basemap.  It will perform faster at runtime.

Also investigate converting the official Wsdot basemap to a vector basemap.  It may compact enough to be comparable or better than the current offline basemap.

The word from the Esri SDK team was that the Quartz beta is a little slow at loading the vector base maps at first, but is much faster at rendering them after the first load.  They said they'll be improving that initial load time by when Quartz is at the 1.0 release.

Note this is for the basemap only.  Vector base maps are optimized to be read-only and cannot be edited, so the performance and compression improvements won't apply to the Hats features.

**Comment by jhudsonWA** [comment]
And this would include the basemap layers like towns and NPDES areas?

**Comment by ReedHunter-Wsdot** [comment]
You got it.

**Comment by ReedHunter-Wsdot** [comment]
While attempting to convert HATS to the latest Quartz beta, I have found that Beta 3 does not yet offer the minimum features required for HATS.  Vector basemaps will have to wait until after Quartz has all the ArcGIS Runtime SDK for iOS components we're already using. 

I'm leaving this at 2.5 since Quartz may support our needs before Jan 1, 2017.

**Comment by ReedHunter-Wsdot** [comment]
The 100.0.0 version of the ArcGIS Runtime SDK release November 2016 now supports the offline edit and service sync pattern.

**Comment by ReedHunter-Wsdot** [comment]
Since this depends on the SDK upgrade, I'm marking this for after 3.0.

**Comment by ReedHunter-Wsdot** [comment]
@kechinn Do you know whether layers like NPDES Areas , cities, and Water Quality TMDL Boundaries are sometimes toggled on/off by themselves?  

Part of what makes vector basemaps fast is that they merge layers together into a single layer.  This makes a trade off where you can only turn on/off all layers participating in the basemap together, not one at a time.  

I'm going to split the offline basemap into several different vector basemaps, and I was wondering if you know of crews who like to toggle those three layers individually such that we shouldn't merge them into other layers.  

Thanks

**Comment by kechinn** [comment]
I believe those listed are fine merged together. I think the only time they might be toggled on/off individually or all at once (more likely), is when someone is using aerial imagery and wants to check the boundaries.

**Comment by sheppamwsdot** [comment]
Backlog

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
