### ISSUE TITLE
support milepost range map searches

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#545]
Crews were asking to search for map features by SR and milepost, or milepost range.  If we're still planning on supporting this, the search would ...
1. offer a pick list of SRs, presumably filtered based on what's close by.  Maybe a toggle switch would let folks pick from all SRs
2. prompt for a from and to milepost
3. After users tap a [Search] button, it would display a list of Hats features from layers turned on in the TOC

An enhancement would be to order list results by milepost instead of alphabetically by feature type. This could be controlled by a toggle switch when running a new search.  Crews could then scroll down the milepost sorted results as they head down the road.

@tangoai , @kechinn , @joeschmit , please let me know if this should be added.

**Comment by jhudsonWA** [comment]
Replaced by #554
