### ISSUE TITLE
Bridge lines look almost exactly like Zone 1 Spray lines

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#547]
@ReedHunter-Wsdot 
Need to change the blue color of Bridge feature, it looks too similar to Zone 1 Spray. Considering what colors are already taken for line features, maybe a darker green or lighter purple?

![bridge_zone1](https://cloud.githubusercontent.com/assets/16247034/17196072/cf9d4dfc-5416-11e6-9bba-c562e027de04.PNG)

**Comment by ReedHunter-Wsdot** [comment]
I have features map with a lighter reddish purple color for the bridges at \wsdot.loc\hq\Public\60Day\HunterR\HatsiOS.  The QA feature service is updated with this change.  I also made the lines for bridges just a bit wider.

As an aside, please try to sync your current HATS beta _before_ updating your offline geodatabase to this file.  This is a chance to confirm that a cartographic change like this does not break compatibility with existing offline maps, meaning we could put this change into production and nobody with the old map symbols would run into any sync problems from this.  I was able to sync my old offline features map just fine even after changing the service.

**Comment by kechinn** [comment]
I was able to sync, add the new geodatabase and sync again successfully. That new bridge color looks better. Thanks!

**Comment by joeschmit** [comment]
@kechinn status?  Can we close this out?

**Comment by kechinn** [comment]
All good. Closing...
