### ISSUE TITLE
Map Search: Find a SR/SMRP

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#554]
Enter a SR/MP and have the map zoom to that location.

**Comment by ReedHunter-Wsdot** [comment]
Be aware that milepost numbers duplicate along spurs and alternate routes vs the main route.  If someone wants SR 195 somewhere between MP 0.1 and 0.6, the map will zoom close to but not at Spur SP195 MP 0.1 through 0.6.  I'll proceed with supporting zooming to the mainline only to keep the UI simple for now.

![image](https://user-images.githubusercontent.com/2709194/26991193-524fadee-4d0e-11e7-8ed7-63917f970359.png)

![image](https://user-images.githubusercontent.com/2709194/26991243-786e79ce-4d0e-11e7-89ff-15737478aaaf.png)

**Comment by jhudsonWA** [comment]
I would still look at supporting ARs (shown as A in our UI), Couplets and spurs. That's what we do in the shared HATS SR list.

Would it make sense to just use my SR picker and then have them type in a mile post range? Might help with consistency in use and supporting the limited RRT/RRQs that show up everywhere else.


Sent from my iPhone

On Jun 9, 2017, at 12:24 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Be aware that milepost numbers duplicate along spurs and alternate routes vs the main route. If someone wants SR 195 somewhere between MP 0.1 and 0.6, the map will zoom close to but not at Spur SP195 MP 0.1 through 0.6. I'll proceed with supporting zooming to the mainline only to keep the UI simple for now.

[image]<https://user-images.githubusercontent.com/2709194/26991193-524fadee-4d0e-11e7-8ed7-63917f970359.png>

[image]<https://user-images.githubusercontent.com/2709194/26991243-786e79ce-4d0e-11e7-89ff-15737478aaaf.png>

**Comment by ReedHunter-Wsdot** [comment]
Although I spotted and was using the picker, I didn't spot the StateRoutes table for populating it.  This will be perfect.

**Comment by jhudsonWA** [comment]
We can tackle the rest of the UI monday. In ActivityRecordViewController there are several functions like 'populateXforpopup' one of those does the calls to get the state routes using the StateRouteRepository class.

**Comment by ReedHunter-Wsdot** [comment]
completed
