### ISSUE TITLE
[Data] Stormwater Ditch Randomly Assigns Sub-feature Type

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#56]
Need to add "None" as a sub-feature to stormwater ditch so that those ditch features aren't assigned to other stormwater bmp types. Possible example is feature 919010.

**Comment by jhudsonWA** [comment]
Looking into this. I asked Jason to send me the current cross walk table.

**Comment by jhudsonWA** [comment]
@suttert Talked wirth Cory, he said after he put it none this seems resolved. Please verify.

**Comment by suttert** [comment]
Looks like it’s working correctly. Thanks
