### ISSUE TITLE
Web:  Create "Non-AVL Trucks" table in HATS 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#562]
@joeschmit  will get back to us on this one. Users requested it but he wanted to verify. If the answer is no then we will create a truck table in the HATs database to manage non AVL trucks as the truck table from winter ops is going away

**Comment by joeschmit** [comment]
Dropping this request, please keep "trucks" as-is, we will manage through WinterOps for this year.

**Comment by jhudsonWA** [comment]
Got it.  However I still think we may want to look into creating a truck list just for Non-AVL trucks in the HATS database. We could even migrate those trucks over from the current WinterOps db. 

The reason for this is because we will mostly be retiring the WinterOps site this year and I still would like to create a new AVLVehicleLocations DB and it will not have the truck management piece. 

Thoughts?

**Comment by joeschmit** [comment]
@jhudsonWA  No concerns whatsoever, I am more than happy having tables like that brought over to CommittmentActivities/HATS Press on.  Issue reopened and modified to reflect.

**Comment by jhudsonWA** [comment]
Will reopen as a AVL task
