### ISSUE TITLE
Admin: Budget Table

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#566]
@joeschmit  will give example

Allows users with rights to set budget for activities and cost per activity.

**Comment by jhudsonWA** [comment]
@joeschmit  can you start hashing this out. As we currently have more help available to us it will be good to be able to assign this to someone. I have a feeling we will get to it quicker than I would of expected.

**Comment by joeschmit** [comment]
Perf will do!

Sent from my iPhone

On Sep 21, 2016, at 5:52 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

@joeschmithttps://github.com/joeschmit can you start hashing this out. As we currently have more help available to us it will be good to be able to assign this to someone. I have a feeling we will get to it quicker than I would of expected.

�

**Comment by joeschmit** [comment]
Option one from the spreadsheet attached, please

![image](https://cloud.githubusercontent.com/assets/884943/19278785/7db2699c-8f93-11e6-9ce7-6be69eb25e94.png)

[Mock Detailed Plan 9-28-16.xlsx](https://github.com/WSDOT/HATS/files/522363/Mock.Detailed.Plan.9-28-16.xlsx)

**Comment by jhudsonWA** [comment]
Great. Thanks Joe!

**Comment by joeschmit** [comment]
cid:image002.png@01D214E1.3D07BC80

**Comment by joeschmit** [comment]
![image002](https://cloud.githubusercontent.com/assets/884943/19869655/7d2207bc-9f6a-11e6-9a74-79b8ff2fbfc2.png)

Org starting in 63 also please

**Comment by joeschmit** [comment]
Add "HQ" to the Control Totals tabs and also add 63 to two digit org code list for control totals, please.

Both 34 and 63 should appear on the HQ tab.

**Comment by jhudsonWA** [comment]
This has been completed, but due to timeline we have decided to push it to 5.5 to allow for reporting features to be added as requested by Maintenance Budget.

**Comment by jhudsonWA** [comment]
Marking as complete as it's in production
