### ISSUE TITLE
MAP - Statewide Rollup

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#570]
For MAP features MAP 2016, MAP 2016 Bridge and MAP Survey, create a report that mimics the old report attached, crosswalk table attached.  We need this to close out the calendar year and the report is provided to the legislature and GNB.  If we could get a working version by November 1 at the latest that would be swell.

http://www.wsdot.wa.gov/NR/rdonlyres/A6DB60B6-2BD6-4746-949B-6380E042F7BC/0/Statewide.pdf

[CrosswalkHatsMap2016.xlsx](https://github.com/WSDOT/HATS/files/407911/CrosswalkHatsMap2016.xlsx)

**Comment by jhudsonWA** [comment]
@brianblood, after you finish search by attribute please tackle this.

**Comment by jhudsonWA** [comment]
This is now in production. Still needs some forms created but it is working and ready.
