### ISSUE TITLE
New Feature Type: "Avalanche Paths"

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#586]
January 1 2017

**Comment by jhudsonWA** [comment]
@joeschmit Will they be doing work against? Do these need WSDOT feature numbers or is this a new basemap layer?

New date: 11/1

**Comment by kechinn** [comment]
@jhudsonWA Yes, need WSDOT feature numbers. They will be doing work against "Avalanche Path" features. 

Attributes that will be pulled from table:  Name, Elevation of Start Zone, Elevation of Road, Vertical Fall, Path Length, Aspect, Track, Road/Runout, Frequency/Comments, History

**Comment by jhudsonWA** [comment]
Where is this staging data?

**Comment by kechinn** [comment]
By staging data do you mean the feature geodatabase? I'm creating that right now, just waiting on a bit more data from the avalanche crew. I let them know that we need the rest of the data asap.

**Comment by jhudsonWA** [comment]
Ah ok, you mentioned the attributes so I thought you may have it already. Let us know once you get it. We can't really do anything until it exists.

**Comment by ReedHunter-Wsdot** [comment]
Done
