### ISSUE TITLE
Admin Report:  Device Utilization

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#598]
In an effort to better understand "How much our iPads are being used", I'd like a report for Admins:
- Report by Device ID or string like "ER%", so a regions worth of devices or the state etc. 
- simple count of ApplicationLog transactions, so ER1234568 has had 456 transactions with the database
- last transaction line from ApplicationLog, so what was the last thing this particular device did with our database (which should mostly be "Sync Complete" but...in the event its not, may make troubleshooting simpler for staff, give me some input on this, not too glued to this)
- date range filter
- Export to Excel and table view.

*Not a high priority

Example report of what I recently had to send to eastern region1

[ER1 HATS iPad Utilization Summary.xlsx](https://github.com/WSDOT/HATS/files/485436/ER1.HATS.iPad.Utilization.Summary.xlsx)

**Comment by jhudsonWA** [comment]
In QA Web
