### ISSUE TITLE
[HATS] Update Work Op Code List

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#6]
FY 2015/17 there were changes to work op codes made in TRAINS/Datamart, the current list in HATS for Feature Activities will be outdated.  Possibly work a manageable table in which Admin's can update/maintain the work op list for the future.  Reversing the process HATS Table to Datamart vs Datamart to HATS?

**Comment by jhudsonWA** [comment]
This list is loaded from the WSDOTDataLibrary. I can see when/if they will be refreshing that data for 2015/17.

**Comment by jhudsonWA** [comment]
Email sent to DRM group.

**Comment by jhudsonWA** [comment]
Was hardcoded to use 2014 list. Updated to calculate current fiscal year and pull those codes. Will deploy Thursday.
