### ISSUE TITLE
Make HATS email us when someone has a 500 map sync error

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#60]
We're notified about crashes, but not sync failures.  Josh supplied me with code to trigger an email when we have a sync failure.  I'll integrate this into the map sync error handler.

**Comment by ReedHunter-Wsdot** [comment]
fyi, you have to attempt to sync again after a sync failure before the error message email can be sent to us.

**Comment by jhudsonWA** [comment]
These will come in as our normal feedback messages.
