### ISSUE TITLE
Data:  Update Region Boundaries data

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#600]
There are new region boundaries in the workbench, this needs to be loaded into HATS and features processed.

The following updated data is now available for WSDOT use:
Available via the Geodata Catalog Business Area - under 'Source Data by Subject:' – Political and Administrative:'

WSDOT Regions 24k

For more information, please see the metadata:
\wsdot.loc\hq\Corporate\Data\GIS\GISOSC\GEODATA\Layers\NEW\PoliticalAdminBoundaries\WSDOTRegions24kCGIS.htm

WSDOT Regions 500k

For more information, please see the metadata:
\wsdot.loc\hq\Corporate\Data\GIS\GISOSC\GEODATA\Layers\NEW\PoliticalAdminBoundaries\WSDOTRegions500kCGIS.htm

WSDOT Maintenance Areas 24k

For more information, please see the metadata:
\wsdot.loc\hq\Corporate\Data\GIS\GISOSC\GEODATA\Layers\NEW\PoliticalAdminBoundaries\WSDOTMaintenanceAreas24KCGIS.htm

WSDOT Maintenance Areas 500k

For more information, please see the metadata:
\wsdot.loc\hq\Corporate\Data\GIS\GISOSC\GEODATA\Layers\NEW\PoliticalAdminBoundaries\WSDOTMaintenanceAreas500KCGIS.htm

Note -There was a change between the SC and EA Regions along SR 395.  There was also a maintenance area change along SR 101 in the area of the intersection with SR 008.

Jordyn Mitchell
GIS Database Administrator
Washington State Department of Transportation
PO Box 47430
Olympia, WA 98504-7430
360-705-7645
mitchejo@wsdot.wa.gov

**Comment by ReedHunter-Wsdot** [comment]
A copy of the updated basemap file is available at \wsdot.loc\hq\Public\30Day\GRDO\Hunterr\HATiOS_Basemap\, and can be loaded for now through iTunes.  Josh will probably load it up by the end of Monday for basemap download within Hats Beta.

**Comment by ReedHunter-Wsdot** [comment]
offline basemap with updated Wsdot maintenance area and region boundaries is now available for download within Hats beta.  Please take a look and confirm everything is there.  If you guys give it the thumbs up we'll make it available for prod.  Thanks
