### ISSUE TITLE
[HATS iOS] proposed enhancement: convert as many point feature types to icons as possible

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#61]
Joe, 
Let me know if you'd eventually want this enhancement.
-Reed

We have very few feature colors that we haven't already used, which may be confusing for folks to determine what feature type they're seeing.  Green dots for example could be stormwater ponds or culvert ends.  

I can replace some dots with images such as a grate cover for drainage inlets, perhaps a small pond icon for stormwater ponds and their subtypes.  Some like manhole or hydrant would be easy, and others like vortex vault and permeable pavement surface might be more challenging.  Homeless camp may be sensitive for what symbol we use.  The benefit may be more intuitive training, and colored circles no longer having multiple meanings.

Icons would need to be approved before I just started dropping them into the map.

**Comment by jhudsonWA** [comment]
We had icons for the AVL site when we first launched. The problem there was when they stacked up on top of each other it looked like a pile of icons and was hard to tell what they were doing. 

I'd think we would have similar issues with HATS in the city, but for most of the state it would probably be a good idea. 

Plus color generally isn't a great idea for accessibility (color blindness)

**Comment by joeschmit** [comment]
I like the idea, but it needs to be clean, simple etc.  Can we just go with different shapes?  Triangles squares etc?

**Comment by ReedHunter-Wsdot** [comment]
Simple features would be squares, diamonds (squares rotated 45 degrees), Triangles pointed up, Triangles pointed down, and circles.  We can vary the thickness of the outline, and we can stack symbols (smaller triangle within a larger circle, etc.).

Would you like Oai to take charge of making recommendations?

**Comment by ReedHunter-Wsdot** [comment]
I have a first cut of this ready, but since we're 2 days before the 1.3 release I think now isn't the right time to begin the review process with Oai.  I'm belaying this til Tuesday, and I'm marking this as a 1.4 feature.

**Comment by ReedHunter-Wsdot** [comment]
Updated QA feature service has these updated icons.  You'll be able to see them in the 1.5 beta.

**Comment by jhudsonWA** [comment]
Closing out
