### ISSUE TITLE
[Data] Provide Naip2015 and High Res Ortho files.

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#62]

**Comment by jhudsonWA** [comment]
**2015 Data Based - New generation process:**

http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/EA_Area1.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/EA_Area2.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/EA_Area3.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/EA_Area4.zip

http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NC_Area1.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NC_Area2.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NC_Area3.zip

http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NW_Area1.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NW_Area2.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NW_Area3.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NW_Area4.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/NW_Area5.zip

http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/OL_Area1.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/OL_Area2.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/OL_Area3.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/OL_Area4.zip

http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SC_Area1.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SC_Area2.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SC_Area3.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SC_Area4.zip

http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SW_Area1.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SW_Area2.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SW_Area3.zip
http://hatsprod.wsdot.loc/App/hats/iOS/Ortho/SW_Area4.zip

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot Here are all the production links.

**Comment by jhudsonWA** [comment]
I think for these both the Beta and the Prod version can use the same files. Even compressed this is taking up 20GB of data on the server. :)

**Comment by joeschmit** [comment]
will these be the permanent links to the files?

**Comment by jhudsonWA** [comment]
Yes, but don't share them yet. They haven't been fully tested yet and we would like to build in app download support.  If you want to test, grab one or two, uncompress them and drop them into the HATS app using iTunes.

**Comment by jhudsonWA** [comment]
Oh and of course these links will only work on network.

**Comment by joeschmit** [comment]
@jhudsonWA copy that.

**Comment by ReedHunter-Wsdot** [comment]
@joeschmit Are you thinking that we'll have folks with thumbdrives take this out to the sheds and side load files onto iPads using iTunes?  If so, then I think this task should be closed and I should make another task for seeing if I can improve the file size (maybe I can), and improve the clipping edges (this I know I can do) for the orthos.

**Comment by ReedHunter-Wsdot** [comment]
NAIP 2015 data is now available.  I've requested access to both the higher resolution orthos and to the NAIP 2015 images.  I'll make tile packages from both.

**Comment by ReedHunter-Wsdot** [comment]
Updates: 
- higher resolution data is available for SRs 005, 016, 101, 121, 163, 302, 510.  Jordyn will make some other SR high res orthos available over the coming months.  
- I will have naip 2015 data for all other SRs on an external drive tomorrow (Thurs, 3-15-16).  This data will have to be projected and clipped before I can make it available.  Expect this to take weeks of processing time.
- Updated orthophotos will include turnbacks.  This is missing from the naip 2013 tile packages we currently have for Hats.

**Comment by jhudsonWA** [comment]
Since these are currently being generated and won't be part of the actual 1.5 release Wednesday I'm moving i to ASAP, which lets us track it for release outside of 1.5 which we will want to close out Wednesday.

**Comment by ReedHunter-Wsdot** [comment]
fyi, I'm aware of an issue with the Orthos I'm generating: the maintenance area boundaries I used to clip the orthos are sometimes running parallel to and just about 40 yards from the center of some SR sections.  This is making the orthos clip more tightly around the routes than crews will want.  I've seen this in SR20 mp148 to 158, visible in NC_Area3.tpk, SR 263 mp0-9 and SR21 mp 0-7.5 visible in EA_Area2.tpk.  

The roads and some adjacent area are still visible in these cases, just not as much.  I will adjust boundaries and regenerate these images differently post the 2.0 release since we have an easy workaround for now: simply also deploy the adjacent maintenance area's tpk file, and you'll have the extra image buffer within that neighboring maintenance area.

**Comment by ReedHunter-Wsdot** [comment]
btw, since all the areas are already clipped in a previous step, going back and reclipping all these would set back release of these image files by about 2 weeks.  That's another reason why I'm making this post 2.0 to correct.

**Comment by ReedHunter-Wsdot** [comment]
last of the Naip2015 tile packages have been created.  Josh, when you have the time can you grab the last 3 of them from the 60day folder I set up?  Next I'll start on the high resolution orthos.

**Comment by jhudsonWA** [comment]
Per Reed: High Res is a next release type of thing. Closing this one as all the normal packages are ready and will open a new task for 2.5.
