### ISSUE TITLE
(Data) Add "Date of Install" to Liquid Deicer Tank attributes (date field)

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#63]
Please add the date type attribute "Date of Install" to Liquid Deicer Tank feature.

**Comment by jhudsonWA** [comment]
I'm planning on spending about two hours tomorrow morning adding attributes for 1.1. I'll rope this in.

**Comment by jhudsonWA** [comment]
This is now in DEV/QA/Prod
