### ISSUE TITLE
[HATS IOS] turn off offline orthophotos when using online basemap

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#64]
One thing I noticed with the beta version offline ortho image is that it stays on even after u choose a different ortho world image. Making things blurry.

**Comment by ReedHunter-Wsdot** [comment]
Once orthos are fully supported, one of the features will be that the offline ortho layers will turn off when users select an online map, and return to being visible when the offline basemap is turned back on.

**Comment by ReedHunter-Wsdot** [comment]
checked in.  Will be available in the next build.
