### ISSUE TITLE
Feature and Other Activities Report Export to Excel Button bug

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#640]
When filtering by State Route, selecting anything other than a mainline will result in the Export not Excel button not working (no response). For example: Cannot export to excel Other Roadkill records on 097A, but can on 097. The Show Report button still works either way.
![roadkill_otheractivity](https://cloud.githubusercontent.com/assets/16247034/20327742/454831ce-ab43-11e6-9d3c-b62d7d12aa64.JPG)

**Comment by jhudsonWA** [comment]
Brian has a fix for this one. I don't think it's made it to my code branch yet. We will push out tomorrow.

**Comment by brianblood** [comment]
The fix is now checked in!

**Comment by brianblood** [comment]
Derp.  Juggling too many branches on my dev environment.  It's now checked in and pushed to Prod.
