### ISSUE TITLE
Missing Attributes in Avalanche Path Activity Record report

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#643]
If I check Include Feature Attributes for Avalanche Path it will export to Excel with only 2 out of 18 (Alpha Angle and Beta Angle).
![avalancheatlasexportmissingattributes](https://cloud.githubusercontent.com/assets/16247034/20358694/9e61cf9c-abe1-11e6-8843-7407373d5725.JPG)
![avalanchepathattributes](https://cloud.githubusercontent.com/assets/16247034/20358695/9fb7e2e6-abe1-11e6-8f0b-9c77797be197.JPG)

**Comment by jhudsonWA** [comment]
Fixed in prod.
