### ISSUE TITLE
MAP Report Bugs

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#645]
Kelly Shields provided some issues found in the map report.  See the attached.

[RestArea_11_15_16.xlsx](https://github.com/WSDOT/HATS/files/596182/RestArea_11_15_16.xlsx)
[MAP_Survey_Report_QA.xlsx](https://github.com/WSDOT/HATS/files/596183/MAP_Survey_Report_QA.xlsx)

.

**Comment by jhudsonWA** [comment]
Jake is working on these now.

**Comment by jkiehl** [comment]
I have some clarifying questions regarding 4 of the issues Kelley found.  Please see the highlighted red areas in the attachment.

Thanks!

[MAP_Survey_Report_QA.xlsx](https://github.com/WSDOT/HATS/files/598266/MAP_Survey_Report_QA.xlsx)

**Comment by jhudsonWA** [comment]
@joeschmit please send Jakes comment and attachment.

**Comment by joeschmit** [comment]
Picked this up and sent to Kelly for more details...thanks.

**Comment by jhudsonWA** [comment]
This is fun. :) Github message tag.

**Comment by jkiehl** [comment]
Thanks.

**Comment by jhudsonWA** [comment]
After the back and forth last week I think all bugs have been resolved. We can reopen if not.
