### ISSUE TITLE
Crash in HATS iOS within forms that allow filter by truck

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#652]
If you disregard org code info in a snow and ice form and go to filter by truck it causes HATS to crash.

**Comment by jhudsonWA** [comment]
Will fix this morning.

Sent from my iPhone

On Nov 30, 2016, at 7:03 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #652<https://github.com/WSDOT/HATS/issues/652> to @jhudsonWA<https://github.com/jhudsonWA>.

�

**Comment by jhudsonWA** [comment]
Fixed and pushed to /rc as 2.2.3
