### ISSUE TITLE
Create overview map button

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#655]

**Comment by jhudsonWA** [comment]
@kechinn What was this one?

**Comment by kechinn** [comment]
@jhudsonWA Oai might have a better idea about this than me as it was his suggestion. I believe the idea was to create a small overview box in a corner of the screen that would give users an option to view map at larger extent while zooming in close, so as to help locating other HATS features or to gain orientation.

**Comment by ReedHunter-Wsdot** [comment]
Oai, is the use case for this to see the nearby road when you're zoomed in close?  Maybe knowing what assets are just outside the map extent?

When we get to this I can add something like a non-interactive corner map where tapping it just toggles minimizing/showing it.

**Comment by jhudsonWA** [comment]
This is bumped to 4.5

Sent from my iPhone

On Aug 31, 2018, at 1:48 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Oai, is the use case for this to see the nearby road when you're zoomed in close? Maybe knowing what assets are just outside the map extent?

When we get to this I can add something like a non-interactive corner map where tapping it just toggles minimizing/showing it.

**Comment by PeterBurkhard** [comment]
Yes!

**Comment by sheppamwsdot** [comment]
Closing for now.
