### ISSUE TITLE
[Data] Add "Facility" as an attribute to ALL features.  If possible list from datamart

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#66]
We need to start to be able to flag features based on "facility", I believe there is an inclusive list in datamart.  This would be ALL WSDOT facilities to include pit sites/ICPs/fuel stations/radio sites etc.

**Comment by jhudsonWA** [comment]
Bumping to 2.0, we need a way to bring in related tables to attributes, otherwise we are just going to get massive lists of switches users have to scroll to find the one they want.

**Comment by jhudsonWA** [comment]
@joeschmit still needed?

**Comment by jhudsonWA** [comment]
No updates on this one in two years. Closing.
