### ISSUE TITLE
Data: Create View for GeoTech group

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#663]
Work with Tim Rydholm on this one, when you guys get time please and thank you.

From: "Fish, Marc" <FishM@wsdot.wa.gov>
Date: Monday, October 31, 2016 at 3:45 PM
To: Joe Schmit <SchmitJ@wsdot.wa.gov>
Cc: Oai Tang <TangOa@wsdot.wa.gov>, Keisha Chinn <chinnk@wsdot.wa.gov>, "Trople, Tracy" <TropleT@wsdot.wa.gov>, "Rydholm, Tim" <rydholt@wsdot.wa.gov>, "Struthers, James" <StruthJ@wsdot.wa.gov>, "Luhr, David" <LuhrD@wsdot.wa.gov>, "Reynolds, Colleen" <ReynolC@wsdot.wa.gov>, "Velupula, Dinesh" <VelupuD@wsdot.wa.gov>
Subject: Create view in HATS & link
 
Joe,
 
We would like to mine some of the data we have recently been inputting into HATS to our unstable slopes management system and GIS.  The Feature Types we are entering include “Geotechnical Cable Net”, “Geotechnical Horizontal Drains”, “Geotechnical Fence”, and “Geotechnical Wire Mesh”.  It is my understanding that to accomplish this task we need to get a SQL view created.  We are interested in the following data: “Date”, “Feature”, “Name”, “Activity”, “SR”, “SRMP”, “End SRMP”, “USMS#, and “How is the system performing” (see attached example HATS form). 
 
We would also like a HATS link to the “Feature Activities-Current Records-view/edit so we can go directly from the USMS and GIS to the form and its attachments. 
 
Is this something you can help us with?
 
Sincerely, 
 
Marc Fish, L.E.G.
Asst. Chief Engineering Geologist
Unstable Slopes Unit Manager
WSDOT Geotechnical Office
Engineering & Regional Operations
Materials Laboratory
PO Box 47365
Olympia, WA  98504-7365
360-709-5498 (office)
360-485-5825 (cell)
fishm@wsdot.wa.gov

**Comment by jhudsonWA** [comment]
Views sent to Tim R.
