### ISSUE TITLE
Provide larger high res Ortho files for areas with Avalanche Path polygons

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#664]
Offline orthoimagery for areas with avalanche path polygons that extend beyond 500 ft

**Comment by jhudsonWA** [comment]
Reed,

The thought on this was this: When creating our clips add the avalanche polygons as a references for clipping. So it would be 500 ft round the highway still but also include all areas where there are avalanche polygons.

**Comment by ReedHunter-Wsdot** [comment]
That's what I was thinking too.  @kechinn, would you prefer that I buffer around the avalanche polygons?  I'd assume that those folks would appreciate aerial photos around their avalanche zones and not just clipped right at the edge.

**Comment by kechinn** [comment]
@ReedHunter-Wsdot Sounds good to me!

**Comment by jhudsonWA** [comment]
Closing per @joeschmit. Will reopen if this becomes a priority.
