### ISSUE TITLE
Update Route Segments basemap layer

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#671]
Low priority, but at some point will need to update to the latest state routes to account for change(s) to the LRS.

**Comment by joeschmit** [comment]
@kechinn status?

**Comment by kechinn** [comment]
@joeschmit Working on this. Running into labeling issues with updates to new features causing the basemap to truncate data.

**Comment by jhudsonWA** [comment]
In 3.0 we have the ability to push out a new basemap at a later date, so if this is not ready at launch tomorrow we will force upgrade everyone to a new copy of the current basemap (with a version id of 1 instead of 0) and can push this one at a later date.

**Comment by kechinn** [comment]
@jhudsonWA Sounds good. I'm still working on trying to get the basemap to draw properly, getting blown up with labels. Hoping to get one out Monday if not today.

**Comment by jhudsonWA** [comment]
Did Reed tell you what we need for a version number label?

Sent from my iPhone

On Sep 21, 2017, at 6:15 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonwa> Sounds good. I'm still working on trying to get the basemap to draw properly, getting blown up with labels. Hoping to get one out Monday if not today.

**Comment by kechinn** [comment]
He told me to use version 1.

**Comment by ReedHunter-Wsdot** [comment]
Go ahead and bump your version number to 2 since version 1 will be our current basemap with an upgrade number.  Otherwise we won't be able to force download to your basemap.

**Comment by jhudsonWA** [comment]
Yep, 2 please unless it’s done before prod release today.

Sent from my iPhone

On Sep 21, 2017, at 7:17 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Go ahead and bump your version number to 2 since version 1 will be our current basemap with an upgrade number. Otherwise we won't be able to force download to your basemap.

**Comment by kechinn** [comment]
Ok, I’m pretty sure it’ll be after so I’ll switch to 2

**Comment by kechinn** [comment]
Completed for HATS 3.0
