### ISSUE TITLE
HATS Web: Export Attributes on Search Inventory when "Filter on Attributes" is checked

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#679]
At some point in the future, not a high priority, please export the attributes when doing an inventory search and "filter on attribs" is selected.

**Comment by kechinn** [comment]
Definitely need a way to export the attributes from feature inventory for when there are data requests! Currently, can only get feature attributes of those that have activities on web, which doesn't work out if features don't have activities.

**Comment by jhudsonWA** [comment]
This has been assigned to Brian. As soon as he get's through budget he will tackle this option. We should be able to utilize some of existing code to make it happen.

**Comment by jhudsonWA** [comment]
Bumping out. Budget is almost to QA. Still a higher priority from my perspective.

**Comment by joeschmit** [comment]
Agreed.

**Comment by jhudsonWA** [comment]
@brianblood Can you take a bit and code this out? 

https://github.com/WSDOT/HATS/issues/679

**Comment by jhudsonWA** [comment]
@brianblood this one needs looked at as well. Ping. ;)

**Comment by brianblood** [comment]
All done and checked into QA.
