### ISSUE TITLE
CommitmentActivities:  Nuke ALL pending activities created on or before July 1, 2015

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#680]
For the love of god, please get rid of these, whenever you are bored, no rush.

**Comment by jhudsonWA** [comment]
All pending activities prior to 7/1/2015 have been closed out with a [Closed Via Script] message appended to any comments.

**Comment by jhudsonWA** [comment]
First sync may be a bit slow. Ended up being around 7500, and all those id's need to be sent to iPads and then deleted.

**Comment by jhudsonWA** [comment]
Side note, should I also create a issue on here to create a script in a week or so to complete all pending activities tied to hidden features. I seem to remember you mentioned that may be an issue. I believe I can fix it server side to make sure pending activities get closed out on feature hide.

**Comment by joeschmit** [comment]
Yes please.

Sent from my iPhone

On Feb 7, 2017, at 5:27 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:


Side note, should I also create a issue on here to create a script in a week or so to complete all pending activities tied to hidden features. I seem to remember you mentioned that may be an issue. I believe I can fix it server side to make sure pending activities get closed out on feature hide.

**Comment by jhudsonWA** [comment]
Oops, bug in script, rolling it back

**Comment by jhudsonWA** [comment]
and bug fixed. All pending activities prior to 7/1/2015 deleted (Feature and other)
