### ISSUE TITLE
[HATS Web] Print Blank does not show Yes/No for Yes/NO Questions types.

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#69]

**Comment by jhudsonWA** [comment]
@joeschmit Is the print blank even used any more. I know we moved it to admin only, but if it is not used can we just retire the functionality?

**Comment by joeschmit** [comment]
Retire it please, no pen and paper documentation.

Sent from my iPhone

On Jun 7, 2016, at 1:01 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Reopened #69https://github.com/WSDOT/HATS/issues/69.

�

**Comment by jhudsonWA** [comment]
Done
