### ISSUE TITLE
[HATS iOS] ESA Questions based off questions/answers

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#7]

**Comment by joeschmit** [comment]
Josh I am going to need this bumped up on the list following 1.1.  I am being pressured to deliver this.

**Comment by jhudsonWA** [comment]
I'll try to get it done as soon as possible but 1.2 is about a month away. It will take at lest a few weeks of work to get this working at least. Web + iPad updates required. Trust me it's next on my list.

**Comment by jhudsonWA** [comment]
Beta 1.5B2 released for test with this feature.
