### ISSUE TITLE
Web: Activities Report, when a Record ID is added, form requires top level filtering

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#701]
Shouldn't a record ID, similar to Feature ID number override any top level filtering?

<img width="943" alt="screenshot 2017-03-16 08 33 41" src="https://cloud.githubusercontent.com/assets/884943/24004920/d99f6b22-0a24-11e7-9ae1-80abb147c860.png">

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Can you take this one. A record id should bypass all other validation.

**Comment by lundyc-wsdot** [comment]
OK


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin
