### ISSUE TITLE
Web: Feature/Other Activities Report, where Predefined, multiple choices selected, respective answer column is blank on Export to Excel

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#702]
Try viewing then exporting record 475690, Culvert, Cleaning. Note the missing answer data.

**Comment by jhudsonWA** [comment]
@brianblood Can you check this one out?

**Comment by brianblood** [comment]
Could not duplicate.  I may have fixed this one after Joe reported it?
