### ISSUE TITLE
Search for Device Id 

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#705]
Can we please have the ability to search by Device Id in the "Device Utilization Log" and the "Application Log"? Can we also have the option to view all records in one page instead of having to click "next"?

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Clay can you do this?

**Comment by jhudsonWA** [comment]
@lundyc-wsdot : 
Ignore this line for now: Can we also have the option to view all records in one page instead of having to click "next"?
