### ISSUE TITLE
Update Feature Type: MAP Survey 2017 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#706]
I will give data to @ReedHunter-Wsdot. Due date mid April if not contingent on HATS iOS 3.0 release

**Comment by kechinn** [comment]
Will deploy June 1st.

**Comment by jhudsonWA** [comment]
This has been loaded to QA Web and is ready for Reed to load into a new Map service so they can show up on the iPad in 2.5

**Comment by jhudsonWA** [comment]
Also @kechinn please verify thew web version looks good.

**Comment by jhudsonWA** [comment]
Loaded into production
