### ISSUE TITLE
[HATS iOS] Map TOC layers should be alphabetized, grouped

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#71]
TOC layers will be listed by alphabetical order.
Grouping criteria will need to be confirmed, but will at least separate basemap/read-only layers from the editable layers.

If we need to group layers belonging to the same parent feature type, we'll need a different UI to distinguish the subtype layers from the parent layers.

Next steps
- clarify whether we're going to group by subtypes and/or by basemap vs editable layers
- I can in the meantime make a basic alphabetical listing of the editable layers.

**Comment by ReedHunter-Wsdot** [comment]
Hey Reed - we would like these grouped.  I will get Oai et all to come up a best way to do this and get back to you shortly, so you can assigned this issue to Oai for now.  Subtype is most likely not the exact way, I think it's more going to be like "Roadway Features, Roadside Features, Barrier, Drainage, etc"

Sent from my iPhone

On Jul 31, 2015, at 2:17 PM, Hunter, Reed HunterR@wsdot.wa.gov wrote:
Joe,

What kind of grouping did you have in mind for layers in the Toc?  

Are you thinking we’d alphabetize A-Z those layers that can be edited in one group, and then start over A-Z the read-only basemap layers at the bottom of the TOC?

Thanks
-Reed

**Comment by joeschmit** [comment]
![image](https://cloud.githubusercontent.com/assets/884943/9087965/952a8e7a-3b42-11e5-9f86-b6dd462c4d21.png)

**Comment by ReedHunter-Wsdot** [comment]
Should Cable Barrier be in the Roadway Features category, or in the barriers category?  I'd need this to start off with being in just one category rather than being in two at the same time.  If you need there to be multiple entries for one layer that's something better to schedule after the 1.2 milestone.

**Comment by joeschmit** [comment]
Should be in Barriers Reed.

**Comment by jhudsonWA** [comment]
Server side is updated to support this, sending Reed the code he needs iPad side now. 

note: on server, setting these values is manual right now but I'll be updating the local feature type admin screen so you guys can manage this.

**Comment by joeschmit** [comment]
Sounds good thanks.

**Comment by ReedHunter-Wsdot** [comment]
checked in sorted Toc code.  Layers not categorized are added to the "Others" group, as are any unrecognized HATS layers (shouldn't happen).  Any basemap geodatabase layer or tile package is added to the "Basemap" group.

Groups so far are just labels and do not collapse when tapped.  I'm looking at supporting collapsing categories to a single cell when the category header is tapped.

**Comment by ReedHunter-Wsdot** [comment]
Checked in support for collapsing groups of layers.  Would like to have it be more animated instead of being instantly open when tapped.  Look/feel is ready for testing once a new beta build comes out.

**Comment by jhudsonWA** [comment]
I can grab my laptop tomorrow and create a new beta in the afternoon.

Sent from my iPhone

On Nov 30, 2015, at 4:43 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Checked in support for collapsing groups of layers. Would like to have it be more animated instead of being instantly open when tapped. Look/feel is ready for testing once a new beta build comes out.

�

**Comment by ReedHunter-Wsdot** [comment]
Animation and some other UI improvements are checked in.  This is ready for testing and feedback.

**Comment by ReedHunter-Wsdot** [comment]
UI bug fixes checked in.  Expect a beta shortly.

**Comment by jhudsonWA** [comment]
Beta delivered. This is now in test by @joeschmit's team.

**Comment by ReedHunter-Wsdot** [comment]
Since it sounds like there are no issues, closing this.
