### ISSUE TITLE
Add New Feature Type: Pavement Project

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#711]
Need to add new feature layer in HATS called Pavement Project. Will give GDB to @ReedHunter-Wsdot once data has been collected and mapped. Due date to deploy new version of HATS (along with MAP Survey layers): June 1st.

Feature: Pavement Project (name not set in stone...)
Attributes: Pavement Type, Notes
Activities: Will re-create from currently used Other Type Activity forms (Pavement-Concrete and Pavement- HMA/BST)

**Comment by ReedHunter-Wsdot** [comment]
@kechinn , Just to confirm for Pavement Project points, this also is ok to add as a point featureclass with no rows of data?

**Comment by kechinn** [comment]
@ReedHunter-Wsdot Not this one. I was supposed to get an excel sheet of data with lat/long to map from Kim Willoughby, I will email her and see if that is ready...it was supposed to be finished earlier, but I think she was running into issues collecting data.

**Comment by ReedHunter-Wsdot** [comment]
As I recall, the beta target date is Thursday next week, and Monday is a holiday.  I think that if we don't have pavement project data in hand, we can just make an empty feature class for now so there's a placeholder for it in Hats features.  Then we just load data once it's available. @jhudsonWA , if you make the feature types available, assigning them featureTypeIds, exposing the types in the snapshot tables, etc., I could make a new QA map service on Friday.

**Comment by jhudsonWA** [comment]
Loaded into production.
