### ISSUE TITLE
Add New Feature Type: Ferry Anchor Points

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#713]
Spoke to Kim Runkel (Sup. from Eastern Region) and crew who brought up a concern with locating Ferry Anchor Points when the water level rises above the anchors. No set due date yet, if possible push out with the June 1st update.

- New point feature called "Ferry Anchor" (no existing data)
- May have Inspection work activity
- Attributes: Type of Rope, Water Elevation, Notes

**Comment by ReedHunter-Wsdot** [comment]
@kechinn, are you ok if I just make an empty point featureclass for this and include for the June 1 release?

**Comment by kechinn** [comment]
@ReedHunter-Wsdot That sounds good for this feature. I'll notify the region when it's ready and they can start adding the points.

**Comment by jhudsonWA** [comment]
An empty dataset has been added to QA (web) you can use admin tools to setup attributes. Won't show up on iPad until Reed adds to a new map service
