### ISSUE TITLE
File Library on web

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#719]
Can we please have access to all file library content on the web? Thank you!

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Clay can you add this to your list of tasks. I can explain when you are ready to tackle.

**Comment by lundyc-wsdot** [comment]
OK


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
@lundyc-wsdot This one as well, please keep it on your work list. I can show you the file library on the iPad. We would want to duplicate a screen for the web.

**Comment by jhudsonWA** [comment]
This is complete and ready to test in QA web. Shows up as File Library in the top menu.
