### ISSUE TITLE
[HATS iOS] Crash On iOS 8.4 When Taking Picture

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#72]
From Oai : "Guidance no… I just  downloaded 1.1 and restored my device but the same thing is still happening.  It crashes while attempting to attach a photo to a record. I can attach an existing photo but once I try to take a new one, it crashes! Looks likes Max is having the same problem. It crashes right after I tap on “Use Photo”."

**Comment by jhudsonWA** [comment]
So this seems like a new bug in iOS 8.4 and iOS 9.0. The picture saves fine to the Photos app, but gives us a Nil link back to the photo. The Asset Library that we use to handle photo management is actually deprecated as of iOS 9, so I've started migration to the new iOS 8+ Photos Framework. Some major changes from Asset library, but I've mostly got the attachment page switched over.

**Comment by joeschmit** [comment]
Got it thanks.

**Comment by jhudsonWA** [comment]
Fixed for 1.1.1.

**Comment by jhudsonWA** [comment]
As part of this change I removed file name from the attachment grid. We don't have access to it without loading the full image with the new photos framework. It is loaded when the image is sent to the server.
