### ISSUE TITLE
Export Feature Inventory Options on HATS Web

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#724]
If possible, allow feature inventory with attributes to be exported to shapefile and/or FGDB or Google Earth kml file from HATS Web. This could be very useful when responding to future data requests and editing/updating inventory such as roadside features.

**Comment by jhudsonWA** [comment]
Should be possible. At least KML. I'll add for 5.7 (Novemberish)

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
