### ISSUE TITLE
Filter Current Records Grid to only show records with Attachments

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#727]
At some point in future, not high priority, add a filter to search for feature activities with attachments.

**Comment by joeschmit** [comment]
basically what @kechinn is needing is either a SQL query or report to excel that dumps features and attributes, Pick feature - export all

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Just adding to your radar. Add to task list when time allows.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Just pinging so this doesn't fall off your list. This would be under Activities -> Current Records ( both Feature and Other ). Add a filter that allows the search to only return records with attachments. We currently show the records that have attachments but don't filter by those flags yet.

**Comment by jhudsonWA** [comment]
This went out with version 5.5. I found a bug so I'll create a new task for that.
