### ISSUE TITLE
Upload TEF Equipment does not allow for import excel sheet at Statewide Level

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#729]
Fleet Operations came out with the updated statewide 2017 TEF Equipment Rental Rate list that needs to be updated in HATS. The Equipment Items page does not allow a user to import an excel sheet unless an OrgCode is specified. Need to fix this so we can bulk update statewide TEF rates, which are currently being used for billing.

**Comment by jhudsonWA** [comment]
@brianblood This was fixed yesterday correct?

**Comment by brianblood** [comment]
Not exactly - there is a manual process that needs a DBA to update the statewide list.  As I recall, Debbi and I talked about updating HATS to do this, but had other higher priority items.  As a placeholder, I wrote a stored proc that merged data from a temp table populated via flat file import so Debbi wouldn't have to keep doing them one record at a time.

**Comment by brianblood** [comment]
The stored proc had a bug in it - that's the thing I fixed yesterday.

**Comment by jhudsonWA** [comment]
K, I'll bump this to future release. Still would be nice to have.

**Comment by sheppamwsdot** [comment]
This has been completed.
