### ISSUE TITLE
[HATS iOS] Assist Esri's 500 map sync error investigation so they'll fix it 

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#73]
Finish the automation I wrote simulating multiple hundreds of editor sessions in Hats in an attempt to cause the 500 error to happen whenever we want - and thus give Esri what they need to take action to fix that error: steps to reproduce it.

I have to add code that adds, updates, and deletes a few test features.
I need to tweak a few variables to make it better match what people have been making.

**Comment by ReedHunter-Wsdot** [comment]
Status update on this since a lot has changed: 
1- I have no plans now on making automation to reproduce this issue.  The hurdle before was Esri wouldn't do anything unless we could get them reproduce the issue in their own computers. I was able to raise enough noise and use the most recent errors as leverage to get past that - they're examining our systems now instead.
2- I have pushed past just having the first analyst assigned to us, and acquired a 2nd Esri analyst who seems to be a specialist in the technology area that has been the problem.  I got her pointed at our problem on Monday, 9-14-15.
3- Since they can't and won't likely be able to reproduce the problem without the 3weeks X ~900 users that it seems to take, I'm johnny on the spot to provide our systems to them and perform tests for them.  Even after I get done with my current tasks to assist them, this will likely take my time until this is resolved.

**Comment by ReedHunter-Wsdot** [comment]
I'm going to be sending a status email on this about once a week, among other reasons to keep a little pressure on the Esri analysts.  Unfortunately those have to have lots of detail so I don't get an email storm with the more technical folks being CC'd.  I'll send you guys a short & sweet summary first next time.

**Comment by ReedHunter-Wsdot** [comment]
status update - uploading VMs to Esri, should be done by Saturday morning 10-31-15. Once the virtual machine copies of our servers are in their hands, they should be able to reproduce our bugs on demand, examine the servers to their heart's content, and confirm fixes their developers author.  I just have to upload a more fresh backup of our geodatabase, and then wait for them to eventually deliver either a hotfix (if they make one) or an update in the next version of ArcGIS Server.

**Comment by jhudsonWA** [comment]
Yo! This is done. Closing out.

**Comment by ReedHunter-Wsdot** [comment]
Much obliged :)
