### ISSUE TITLE
Low priority - Mobile System Message History

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#731]
Very low priority. I was just thinking that since we're making so many changes to HATS that it'd be nice to offer a way for users to view old mobile system messages via web or iPad for whenever we blow the old one away with a new message. Similar to the same way the Apple App Store allows people to view Version History under the app's Details tab. 

Not only would users be able to see any important tips, tricks and fixes/changes to HATS they might've missed, but it would also be a good way for us admins to track app improvement and version releases over time. For now I'll continue to copy&paste all the messages into a Word document.

**Comment by jhudsonWA** [comment]
Requested server table to store history of these messages. Once we get that I'll add to mobile.

**Comment by jhudsonWA** [comment]
Done and in the beta version.
