### ISSUE TITLE
Hide BMP's and CB's where WSDOT Responsible has been set to 'No'

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#736]
SWID has a Yes/No/Unknown for the attribute WSDOT Responsible. Can we hide all features, both BMP's and CB's, where "No" was selected?

**Comment by jhudsonWA** [comment]
Sure, we need to talk this over, do you simply want to hide or do you want to also give users the ability to hide based off the WSDOT Responsible reason.

**Comment by suttert** [comment]
Simply hide, the users can continue to place in city responsibility.

**Comment by jhudsonWA** [comment]
Groovy. We will make it so over the next week or so.

On Jun 7, 2017, at 9:19 AM, Trett Sutter <notifications@github.com<mailto:notifications@github.com>> wrote:

Simply hide, the users can continue to place in city responsibility.

**Comment by jhudsonWA** [comment]
I didnt forget about this, I will need to work with Keisha we will want to make sure any features that get hidden also get removed from the map which will require a process from Keisha.

**Comment by jhudsonWA** [comment]
@suttert This looks like this will hide around 1600 features. I need to give the hide a reason. City Limits ok? Or should i create a new (non user selectable) WSDOT Not Responsible reason.

**Comment by jhudsonWA** [comment]
@kechinn Do you have time this week? After I delete the features we need to do a true up of the data. I would like to do this at a time where you have the time to do a feature true up on the SDE side soon after I do the hide of these 1600 features.

**Comment by kechinn** [comment]
@jhudsonWA I have time on Thursday to do the true up. Anytime after 11 am would work.

**Comment by jhudsonWA** [comment]
@kechinn Ok, give me a call Thursday after 11.

**Comment by kechinn** [comment]
@jhudsonWA Will do!
