### ISSUE TITLE
Grab Pavement Project (149) Multi-Part Ids 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#737]

**Comment by ReedHunter-Wsdot** [comment]
@kechinn for this you just need the object ids of the multipart lines in 149_lines?

**Comment by jhudsonWA** [comment]
This one is for me. you would never see the multipart lines as they were not put in the snapshots

**Comment by jhudsonWA** [comment]
@kechinn Do we need to do anything here?

**Comment by kechinn** [comment]
@jhudsonWA Nope, I got everything sorted out with the multi-part stuff and re-drew them on my iPad. Closing.
