### ISSUE TITLE
Triggering Pending Activity via Web

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#745]
Low priority, but I want to make note that if you trigger a certain pending activity from a drop down list via the web form and then decide to change to a different pending activity, the form will not catch the change unless you go back to 'select' on the drop down and then to the correct activity. A great example being the Pavement Project Concrete or HMA/BST Inspection forms (see below).
![image](https://user-images.githubusercontent.com/16247034/27403725-52cff96a-5680-11e7-8a0b-6546653961f5.png)

**Comment by jhudsonWA** [comment]
So this is even before a save. Interesting. We will add it to post 5.4 deployment

**Comment by jhudsonWA** [comment]
@brianblood If you get a moment between budget work and would like to tackle, can you take a look at this. Seems web pending activities are not always properly changing

**Comment by jhudsonWA** [comment]
@brianblood Can you check this out to see if it still an issue?

**Comment by brianblood** [comment]
Yep, still an issue.  I’ll look at it after some cake.

**Comment by jhudsonWA** [comment]
@brianblood  checked in a fix for this and it's now in prod.
