### ISSUE TITLE
Map improvement: project avalanche paths to web mercator in next geodatabase

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#748]
back in October of 2016 I didn't catch that avalanche path polygons were in Wa State Plane South. 
 This just makes the map refresh a bit slower when you're looking at those paths.  If I fix this now it will break sync compatibility for all iPads, so we have to wait until the next time we make a whole new geodatabase.   This task is a reminder to make that fix the next time opportunity comes.

**Comment by jhudsonWA** [comment]
Next time will probably be 3.0. As we will be adding attribution for the ‘scheduled work map” that is a good time to reload the full geodatabase as new.

- Josh

On Jun 29, 2017, at 9:34 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


back in October of 2016 I didn't catch that avalanche path polygons were in Wa State Plane South.
This just makes the map refresh a bit slower when you're looking at those paths. If I fix this now it will break sync compatibility for all iPads, so we have to wait until the next time we make a whole new geodatabase. This task is a reminder to make that fix the next time opportunity comes.

**Comment by ReedHunter-Wsdot** [comment]
The dataset queued up for the next release is in web mercator.  I'll make sure that as Jason makes the new geodatabase that the updated dataset is used.
