### ISSUE TITLE
Add Clear/Reset Button to new SR/MP Zoom tool on iOS

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#749]

**Comment by ReedHunter-Wsdot** [comment]
Do you mean a previous extent button?  Nothing is highlighted on the map.

**Comment by kechinn** [comment]
No, a button to clear whatever a user types into Search by SR/MP as it stays put until you close the app. I just thought about it while finishing drawing a few new Pavement Project lines on different state routes (those weird multi-lines). It might be nice to have a clear button rather than scroll or backspace.
![image](https://user-images.githubusercontent.com/16247034/27707853-afd6dee8-5ccb-11e7-9680-8631e8cb252b.png)

**Comment by ReedHunter-Wsdot** [comment]
<img width="576" alt="screen shot 2017-07-03 at 11 13 07 am" src="https://user-images.githubusercontent.com/2709194/27803889-b2560aaa-5fe0-11e7-9a3f-b40dcf89e754.png">
I added a button each for the SRMP inputs and the map search input.  This will be available the next time Josh builds a beta.
