### ISSUE TITLE
[HATS iOS] Make "Collect GPS" Required if GPS = Green

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#75]
If possible make collect GPS a required field, if it is "green" on ALL records/feature types where Lat Long required is = true.

Also if a feature is a "line" allow a start/end gps point to be collected in the record.  This is helping us with QA of data.

**Comment by jhudsonWA** [comment]
Yes, but I'm not sure this is a quick fix. Requires changes on iPad and web. Can we move to 1.2 milestone? Couple extra weeks would help. Trying to keep 1.1.1 to bug fixes were necessary.

**Comment by jhudsonWA** [comment]
Joe,

For the line is both begin and end required if green?

**Comment by joeschmit** [comment]
Yes please

**Comment by jhudsonWA** [comment]
Done in 1.2B2

![screen shot 2015-09-08 at 4 18 24 pm](https://cloud.githubusercontent.com/assets/702446/9749795/653417a4-5645-11e5-948c-5ee5d84bae94.png)
![screen shot 2015-09-08 at 4 18 13 pm](https://cloud.githubusercontent.com/assets/702446/9749794/65336b56-5645-11e5-8999-0304d69f28a3.png)

**Comment by jhudsonWA** [comment]
![screen shot 2015-09-08 at 4 21 06 pm](https://cloud.githubusercontent.com/assets/702446/9749833/a94f99f4-5645-11e5-9838-073771c04bde.png)
![screen shot 2015-09-08 at 4 21 18 pm](https://cloud.githubusercontent.com/assets/702446/9749834/a96500fa-5645-11e5-8e17-5bdb740e8a05.png)
