### ISSUE TITLE
Update Work Op List

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#750]
Need to refresh the work op list. We created 1197 for hydrants that does not appear on the current list.

**Comment by jhudsonWA** [comment]
It pulls from the current fiscal year. Is this a 2017-2019 workop or was it added to the current? And when did you ask for it.

**Comment by joeschmit** [comment]
This will be for the new biennium.

**Comment by jhudsonWA** [comment]
Ok, we pull from the data library so in theory on July 1 we will see the new. If we don't for some reason let us know.

**Comment by joeschmit** [comment]
@jhudsonWA @brianblood Delay this until we give a go ahead, apparently accounting hasn't actually done the update, and yes we will have some work op changes to catch basin and culvert.

**Comment by jhudsonWA** [comment]
I believe we pull from the wsdot data library, once accounting does there work they should update the 2017 FY work op codes and the app should reflect without us doing anything. At least that is the hope ;)

**Comment by brianblood** [comment]
That is my understanding as well.  We shouldn't need to do anything.

**Comment by jhudsonWA** [comment]
@joeschmit status on this one? Did the list ever update with your new codes?

**Comment by jhudsonWA** [comment]
@joeschmit safe to close?
