### ISSUE TITLE
Culvert Injunction List

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#755]
I want to lock down all culverts where "On Statewide Fish Passage List" or "On Culvert Lawsuit Injunction List" has been selected for the attribute Fish Barrier Status. At this point, I only want to prevent them from removing these select culverts.

**Comment by jhudsonWA** [comment]
@suttert This would require a code change on the iPad to look for these attributes and hide the delete button. Right now you can only turn the delete off for a full feature. I can add it but it wouldn't go out out until the next release likely 3.0

**Comment by suttert** [comment]
That works. Thanks

**Comment by jhudsonWA** [comment]
Done in 3.0 beta 3 (not yet pushed). Also blocks stormwater verified from being hidden as our discussion.

![simulator screen shot - ipad pro 9 7 inch - 2017-08-01 at 16 39 04](https://user-images.githubusercontent.com/702446/28851798-dba568a0-76d9-11e7-8b29-fb015a20304f.png)
![simulator screen shot - ipad pro 9 7 inch - 2017-08-01 at 16 47 43](https://user-images.githubusercontent.com/702446/28851799-deeb9354-76d9-11e7-8983-adfa089e3f05.png)
![simulator screen shot - ipad pro 9 7 inch - 2017-08-01 at 16 48 56](https://user-images.githubusercontent.com/702446/28851803-e0f1b3e0-76d9-11e7-92d3-e0fbcc0395e0.png)
