### ISSUE TITLE
[Data] "Location" Field should be required and a multiple selection

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#76]
"Location" Field should be required and a multiple selection, we are finding that there are situations where multiple locations of a single activity are taking place and would like the ability to query those.  Understanding this is a model change.

**Comment by jhudsonWA** [comment]
We are probably looking at a 1.4 or 1.5 (Pesticide) for this change.

**Comment by jhudsonWA** [comment]
@joeschmit still needed/wanted?

**Comment by jhudsonWA** [comment]
No updates on this one in two years. We can always re-create/re-open.
