### ISSUE TITLE
HATS Web: Pesticide, Need Delete Record Button

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#762]
Similar to HATS proper, need to be able to delete records from the Edit screen, when proper user rights are in place.

**Comment by jhudsonWA** [comment]
What user rights should be used? Activity records have that whole two week thing

**Comment by joeschmit** [comment]
@jhudsonWA thats fine. Same rights as HATS web. 14 day window then locked then "editor" with appropriate org code rights -- has rights. Admins can do anything.

**Comment by jhudsonWA** [comment]
Using same editor list as main HATS?

On Jul 12, 2017, at 12:32 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonwa> thats fine. Same rights as HATS web. 14 day window then locked then "editor" with appropriate org code rights -- has rights. Admins can do anything.

**Comment by jhudsonWA** [comment]
Added in dev
