### ISSUE TITLE
[Data/iOS] Add "Concrete Barrier" and "Fence" feature types to map

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#77]
Reed, need you to turn on the "Concrete Barrier" feature, when you can.

**Comment by ReedHunter-Wsdot** [comment]
Just to confirm - this is a HATS feature and not a basemap feature, right?

**Comment by joeschmit** [comment]
@ReedHunter-Wsdot affirmative, a HATS feature, linear type, with a current load of inventory.

**Comment by ReedHunter-Wsdot** [comment]
Feature type id of 5.  No problem adding to map, but I'll wait until shortly before release in case you need to add more feature types.  I'd rather push out the services only once for the next release than to risk running through all steps multiple times.

**Comment by jhudsonWA** [comment]
We will want to talk through this one as well. I don't want to change the service and force a full redownload again. If that's required, we may stagger this release to keep the number of folks updating at once down.

**Comment by joeschmit** [comment]
Done!
