### ISSUE TITLE
Ability to Update/Force Update basemap to a new version 

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#776]

**Comment by ReedHunter-Wsdot** [comment]
Part of this is now supported.  The offline basemap now can report a version number.  An outdated basemap version can now be detected.

**Comment by jhudsonWA** [comment]
Second part is done where it will now sync the required version from the server and on next app start force the download if needed. This is a forced download, a user won't be able to cancel it, the file is deleted on the check and the app won't continue on until the download completes.

Will be part of next beta.
