### ISSUE TITLE
HATS Web: Pesticide - Milepost Ranges on View/Edit, needs Edit capability

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#777]
HATS Web > Pesticide > View/Edit > Route > Need an "Edit" button - please.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot, they would rather have an edit and a delete, than just delete and re-enter on route, so please add to your list (near the top)

**Comment by lundyc-wsdot** [comment]
To which screen is this referring?

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
Add and edit pesticide application. Highway segment section

Sent from my iPhone

On Jul 21, 2017, at 9:22 AM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:

To which screen is this referring?

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by lundyc-wsdot** [comment]
Thank you.


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by lundyc-wsdot** [comment]
This is pushed and synced (whew!!) and also includes the augmented field sizes (Item #788).

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
I'll move to QA soon.

**Comment by jhudsonWA** [comment]
Deployed to QA, will go out with next prod push (5.4.x)
