### ISSUE TITLE
HATS Web: Pesticide, Search by Rec ID 

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#778]
HATS Web > Pesticide > Current Records > Need a Search by Record ID field please.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot, please add to your list (near the top)

**Comment by lundyc-wsdot** [comment]
This is completed, pushed, and synced.  Any preference on which task next?  BTW – I don’t know how to mark a task as ready for test in this environment.

For tomorrow, the required Security course first, and then back to real work.

Have a great weekend.

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
I sent two new ones regarding pesticide. Either of those would work.

Sent from my iPhone

On Jul 20, 2017, at 4:46 PM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:

This is completed, pushed, and synced. Any preference on which task next? BTW – I don’t know how to mark a task as ready for test in this environment.

For tomorrow, the required Security course first, and then back to real work.

Have a great weekend.

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
This is complete and ready for test in QA. Thanks @lundyc-wsdot
