### ISSUE TITLE
Pesticide: Increase size of notes column to 1000

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#788]
@lundyc-wsdot : Got some regional feedback today that the comments/notes field may not be big enough to capture both the sensitive contacts and comments for bigger applications. Currently set at a size of 250 chars. 

Please work with database support and update stored procs (insert,update) to increase size of the notes field to 1000. Also on the add/edit pesticide page change the counter to reflect thew new size.

**Comment by lundyc-wsdot** [comment]
I see this for the Note field.  Should it also be done for the TargetGroup field?

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
Yea.. just to be safe. I don’t think it has the same risk,  but now is the time of you are working on it.

Sent from my iPhone

On Jul 26, 2017, at 8:20 AM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:

I see this for the Note field. Should it also be done for the TargetGroup field?

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by lundyc-wsdot** [comment]
OK


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
Done in Dev - Prod. Right now the web won't allow more than 250 to be typed in until the next prod deployment. But the iPad can send up the full 1000.
