### ISSUE TITLE
9.7 inch iPad: Landscape: Keyboard covers feature search id/number box.

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#792]
Might have to rethink this UI for 3.0. If in landscape the feature search section is hidden behind the keyboard. Maybe a popup tool would be better and fit in the space we have in landscape? Something like keep side menu search menu but it can be used to launch the filter tools into popup windows?

![simulator screen shot - ipad pro 9 7 inch - 2017-08-01 at 16 56 33](https://user-images.githubusercontent.com/702446/28851895-645c924a-76da-11e7-8ea1-fdb1b2d77ac4.png)

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot Let's discuss on your non flex day this week and see if we can come up with some ideas. I would be willing to implement, as you area busy on higher priority areas.

**Comment by ReedHunter-Wsdot** [comment]
I think an accordion-style control would preserve the real estate down below.  It would be another tap for some users, and we may have to preserve their previous accordion tap between sessions for users who only like to use one of the two search options, but it would resolve the problem of the keyboard covering the input.

**Comment by jhudsonWA** [comment]
That is a good idea, like the TOC. I’ll work on it next.
On Aug 3, 2017, at 6:56 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


I think an accordion-style control would preserve the real estate down below. It would be another tap for some users, and we may have to preserve their previous accordion tap between sessions for users who only like to use one of the two search options, but it would resolve the problem of the keyboard covering the input.

**Comment by jhudsonWA** [comment]
Still a work in progress but I'm thinking I'm going to use this idea. Where you pick the tool at the top and it swaps out the lower section with the selected tool. This will pull up the text fields enough to make them not be under the keyboard and allows us to support more and more tools in the future.

The accordion style would of worked as well but as you add tools it pushes everything down and if we add a few more tools they could also be under the keyboard if they contain text boxes.  

![simulator screen shot - ipad pro 9 7 inch - 2017-08-10 at 17 15 40](https://user-images.githubusercontent.com/702446/29197383-cff65290-7def-11e7-829f-4382b1ea4e7e.png)

**Comment by jhudsonWA** [comment]
Completed. In 3.0 beta 6

**Comment by kechinn** [comment]
@jhudsonWA Any chance you could minimize some of the white space near the scroll pick tool at top or between SRMP(s) and Route under the SR/MP Zoom tool? The keyboard still sort of covers the Route scroll picker and definitely covers the Zoom button, so you still have to close the keyboard to zoom.
![image](https://user-images.githubusercontent.com/16247034/29930003-079f272a-8e22-11e7-9099-0bfab41620ee.png)

**Comment by jhudsonWA** [comment]
Yep, but that may not be fully avoidable. We can try, my goal was to get it so any typeable areas were not covered.

On Aug 31, 2017, at 8:03 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonwa> Any chance you could minimize some of the white space near the scroll pick tool at top or between SRMP(s) and Route under the SR/MP Zoom tool? The keyboard still sort of covers the Route scroll picker and definitely covers the Zoom button, so you still have to close the keyboard to zoom.
[image]<https://user-images.githubusercontent.com/16247034/29930003-079f272a-8e22-11e7-9099-0bfab41620ee.png>

**Comment by kechinn** [comment]
Gotcha. Well, either way it works much better than it did before:)

**Comment by jhudsonWA** [comment]
Here is the best I could do, can still hit the zoom button. Will be in the next beta Tuesday 

![simulator screen shot - ipad pro 9 7 inch - 2017-08-31 at 17 25 47](https://user-images.githubusercontent.com/702446/29950591-92119cae-8e71-11e7-9886-73466dcac6fb.png)

**Comment by jhudsonWA** [comment]
I'm going to look if there is a way to remove the shortcuts bar (the bar on top of the keyboard) in this view, it's not needed here and that would give us some more room.

**Comment by jhudsonWA** [comment]
Here we go. Dropped the shortcut bar and it looks good. All text and buttons fully visible.  

![img_0002](https://user-images.githubusercontent.com/702446/30187255-bd121ce6-93dd-11e7-803b-6e28c181ff90.PNG)

**Comment by kechinn** [comment]
Cool, looks good! Thanks!
