### ISSUE TITLE
Add button for Statewide/OrgCode filter of Labor/Equipment in K-Job Record

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#793]
@jhudsonWA As we discussed, this would be a good idea to add for Labor and Equipment lists-lots of requests to filter specifically by OrgCode. Or at the very least place all OrgCode-specific items on top of statewide list regardless of Sub-class/Name order. Brian helped me update new FY 2018 TEF Equipment list in HATS and it's gone from 19 to 31 pages long...

**Comment by jhudsonWA** [comment]
This is probably because he added all subclasses. In the past we trimmed it down to only a subset of the equipment (well @Deb-Achord did). But yes, I'll get @lundyc-wsdot working on this next.

**Comment by jhudsonWA** [comment]
Moving to Web 6.5 as that will be the K-Job update release

**Comment by jhudsonWA** [comment]
Holding off for now until we know what new k-job area will look like.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
