### ISSUE TITLE
Web Homeless Camp Posting Notification Activity Error

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#794]
Jim McBride contacted me about this one - after collecting and syncing Homeless Camp Posting Notification activity from iPad, date of posting date on web defaults to January 2012. Looks okay on iPad under history.
![homelesscamppostingnotificationactivityerror](https://user-images.githubusercontent.com/16247034/28942286-a083d73a-784f-11e7-8083-62ea41ecb0b5.PNG)

**Comment by jhudsonWA** [comment]
Must something weird how it’s binding to the web field. We will take a look.

- Josh

On Aug 3, 2017, at 1:38 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Jim McBride contacted me about this one - after collecting and syncing Homeless Camp Posting Notification activity from iPad, date of posting date on web defaults to January 2012. Looks okay on iPad under history.
[homelesscamppostingnotificationactivityerror]<https://user-images.githubusercontent.com/16247034/28942286-a083d73a-784f-11e7-8083-62ea41ecb0b5.PNG>

**Comment by jhudsonWA** [comment]
@brianblood can you check this one out when you get back? Date is stored correctly in the observation table, but knockout is binding it to a different date on display.

**Comment by brianblood** [comment]
Fixed in dev.

**Comment by jhudsonWA** [comment]
This has been pushed to production. However, the browser may have cached the javascript file that needed to be updated. If you still see the issue hold down control and hit refresh.

**Comment by kechinn** [comment]
@jhudsonWA Works, thanks. I did have to do the control refresh and was able to see the changes then,

**Comment by jhudsonWA** [comment]
Chrome likes to cache javascript files longer than it should.

On Aug 28, 2017, at 1:25 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonwa> Works, thanks. I did have to do the control refresh and was able to see the changes then,
