### ISSUE TITLE
Web: Bug, Features without an Activity Report

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#805]
Web > Features Without an Activity > Any Feature > Any Activity > Filter by Region > **[Unable to Select Region]**

Only allowing "All"

<img width="663" alt="screen shot 2017-09-07 at 7 18 13 am" src="https://user-images.githubusercontent.com/884943/30168024-0cf2e61e-939d-11e7-9815-e9440161e78e.png">

**Comment by jhudsonWA** [comment]
Extra } in the javascript for the page. Was fixed in 5.5 in dev and QA but never made it to the 5.4.x prod line. Deployed fix as of this morning as 5.4.11

**Comment by brianblood** [comment]
Thanks Josh!
