### ISSUE TITLE
In the Planned/Pending map: Disable + button, disable hide and edit buttons on identify and search results

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#808]
@ReedHunter-Wsdot I'll try tackle this one and ask if I need guidance. They want the planned/pending view to only be for completing work and viewing attributes, not for doing edits of any kind that is on the main map view.

**Comment by ReedHunter-Wsdot** [comment]
I suppose you could access the user preferences state, though I'd prefer a different mechanism for tracking the current map status.

**Comment by jhudsonWA** [comment]
This is checked in. On change a notification is raised and the table is rebuilt. It doesn't redo the identify so you get the same results but the delete and edit buttons are hidden. Also on view change I close map/identify results panels to help "reset". This work with identify but not with map search.
