### ISSUE TITLE
Web: Fix MAP Survey Report for annual reporting

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#810]
Some minor bugs, Kelly will provide the details shortly. Will need to be done prior to December 1-ish.

**Comment by jhudsonWA** [comment]
Will do

On Sep 18, 2017, at 8:15 AM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


Some minor bugs, Kelly will provide the details shortly. Will need to be done prior to December 1-ish.

**Comment by joeschmit** [comment]
@jhudsonWA Status? Is something needed from my side? I believe the report output is blank when ran.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot for next week

**Comment by jhudsonWA** [comment]
This shipped by the way a few weeks ago.
