### ISSUE TITLE
Feature and Other Current Records:  Attachments Column is empty on paging. Only the first page has data.

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#824]
@lundyc-wsdot Move this one up your list please once you finish the Planned Activity admin task.

**Comment by lundyc-wsdot** [comment]
Will do.


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by lundyc-wsdot** [comment]
This is fixed, pushed, and synced.


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
Moved to production.
