### ISSUE TITLE
HATS Web UI: Bootstrap it up!

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#826]
Liking the bootstrap CSS, this is a placeholder with mockups shortly, but its time to update look and feel of the web UI.

**Comment by jhudsonWA** [comment]
Adding the whole team to this one. :)

**Comment by jhudsonWA** [comment]
Todo: 

- [ ] map window frame, can map scale as it shrinks/grows?

**Comment by jhudsonWA** [comment]
Update on this one. All pages have been converted as of todays release except for Edit feature (Work in progress) and web add feature (Work in progress) and KJob/Estimates add/edit.

**Comment by jhudsonWA** [comment]
All pages except for KJob done. So closing this task
