### ISSUE TITLE
iOS: Map Search Tool, Filter SRMP by Region, Area

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#831]
On the map search function, add the ability to filter SRMP list by Region, Area, one or both.

**Comment by jhudsonWA** [comment]
Hmmm ok. So little space on that screen when the keyboard is up in landscape on the 9.7 inch devices. I could put the filter below the zoom/clear. On the record entry screen we have the users orgcode to do the filter, what do we filter on here? Add Orgcode box that defaults to the selected users?

**Comment by joeschmit** [comment]
Agree, the challenge with this one is scrolling through every SR in the tight space as you can imagine. Not sure how else to work the UI but the users are looking for the same hatsy option they see in the "Other" record screens....

**Comment by sheppamwsdot** [comment]
Move to backlog

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
