### ISSUE TITLE
Make username a required field under add user in HATS iOS

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#838]

**Comment by jhudsonWA** [comment]
![img_0004](https://user-images.githubusercontent.com/702446/31244732-c61ee020-a9be-11e7-9b37-192f45cd7eb0.png)

Done for next beta!

**Comment by jhudsonWA** [comment]
Actually tweaked the layout a bit more. I noticed on edit some controls were hidden below the keyboard in landscape on the 9.7 inch devices (so little space!)

![img_0005](https://user-images.githubusercontent.com/702446/31247385-43a59024-a9c5-11e7-9910-c4874573c947.png)
![img_0006](https://user-images.githubusercontent.com/702446/31247386-43a6d236-a9c5-11e7-9179-172af014335a.png)
