### ISSUE TITLE
iOS: In Feature Info popover display "last updated date"

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#843]
When Roadside features spatial is updated we need to be able to show the user when this happened in the popover along with the "added date"

**Comment by jhudsonWA** [comment]
Just when the location was updated? Or when the feature was updated at all?

**Comment by joeschmit** [comment]
Just the spatial, I am not sure where else there is value is showing a last update date other than maybe the attributes screen,

**Comment by jhudsonWA** [comment]
Alrighty, We have a FeatureCurrMeasureDate in the database. I'll use that. Need to make sure it has been properly updating on spatial update. If not we can fix that issue and sync it down. 

The Feature's RecordUpdateDate is updated whenever a change happens to attributes, hide status, location change and I've confirmed that is working.

**Comment by jhudsonWA** [comment]
Ok, bug fixed, the FeatureCurrMeasureDate column is now updated when the spatial is changed on device. This doesn't affect previous records, but from here on out will update properly.

**Comment by jhudsonWA** [comment]
![img_0007](https://user-images.githubusercontent.com/702446/31468824-60295d38-ae94-11e7-9af6-b6c6acf36eb9.png)
How does this look?

**Comment by jhudsonWA** [comment]
See Location Updated date in result

**Comment by joeschmit** [comment]
This looks good, ship with 3.5

**Comment by jhudsonWA** [comment]
Then it's done and will be in next beta
