### ISSUE TITLE
If pending record is saved as incomplete, feature should not disappear from Planned/Pending map

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#844]

**Comment by kechinn** [comment]
@jhudsonWA Joe encountered this situation in class today. I know we discussed this before via group chat, but might want to brainstorm more on this?

**Comment by jhudsonWA** [comment]
Ok..  If you don't remove it from the map, they click +Activity again what should it show? 

Right now it would show nothing as that records has been saved (ie completed from the queries point of view) 

Also if that was the last planned/pending you marked as complete but saved as incomplete the + activity button would go away.

So we would need to also enhance this workflow to have +Activity show incomplete records in a new/updated view.

So not really a pending with complete button back, but a new Incomplete Records view for that feature. Would that work?

**Comment by jhudsonWA** [comment]
Updated my last comment , so if  checking via email click to read it :)

**Comment by sheppamwsdot** [comment]
Closing because the request is stale.  Please re-open if this continues to be an issue in the future.
