### ISSUE TITLE
Show length of features and use to set length attributes on device.

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#85]
(Data) Run a process to compute geometry on " any feature that is a "linear" feature types where two points or more exist to ascertain a length attribute.

**Comment by ReedHunter-Wsdot** [comment]
Where do you want this attribute to show up?  If you need this in the HATS UI, I could probably expose this in the identify results for any line feature, displayed on the fly.  If you need this stored in the database as a separate attribute as an input for some other function, then I'd probably need to compute that value.

**Comment by joeschmit** [comment]
@ReedHunter-Wsdot both?  "Length" is currently a database attribute for the culvert, cable barrier, guardrail etc.  It would be fine to keep it there.  I don't think having it along with SRMP etc on the Identify results would be too great, then it could turn into exposing all the attributes there.  I would like to eventually lock editing on that and make it read only as well, which already has support built in.

**Comment by jhudsonWA** [comment]
I think we can just handle this on my side since I store all the geometry and have access to the attributes.

**Comment by ReedHunter-Wsdot** [comment]
checked in support for this.

**Comment by jhudsonWA** [comment]
Reopening since I still need to propagate to the various length attributes on edit, save.

**Comment by jhudsonWA** [comment]
New beta on /beta (#13): Length attribute is now read and sent to attribute edit screen on when a user hits Edit when viewing attributes where applicable, user would need to save to actually save the value. 

Note: The view attributes screen always shows the current values in the local database, while the identify results always show the current length measurement. So the workflow here would be to identify, show attributes, then hit edit and the current length will be added to the feature. A save will update the local database and the server on sync.

On feature add the length attribute is also sent to the attribute screen now, and the server on sync.

On feature edit the length attribute is automatically saved if applicable and sent to the server on sync. 

All of this depends on a feature having a editable length attribute enabled on the server. I switched all features to use the same length attribute id so no other setup is needed for this feature except for on Feature Attributes admin screen you set View on Mobile to true and Edit to true.
