### ISSUE TITLE
Add ability to filter by Source System when filtering by attributes in Feature Inventory

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#876]
Maybe Creation/Found date too? It would be useful to have the ability filter by those attributes when exporting from feature inventory as well as see them included as columns in the export.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot I can show you what to do on this one one you are ready.

**Comment by lundyc-wsdot** [comment]
OK


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
@lundyc-wsdot has started work on this.

**Comment by jhudsonWA** [comment]
Done in development, will roll out with 5.6

**Comment by jhudsonWA** [comment]
Found an issue during QA deployment. Not yet complete.

**Comment by jhudsonWA** [comment]
In production
