### ISSUE TITLE
[HATS ios] Updated NPDES Layer

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#88]
Can we update the NPDES layer on the iPad. The layer is updated approximately every 5 years with the last update occurring a few months back. The layer currently on the iPad is from the previous permit. The new layer replaced the old one on the workbench.

**Comment by ReedHunter-Wsdot** [comment]
I have this in included already in the next basemap, but I will mark this off only after that's deployed for download.

**Comment by ReedHunter-Wsdot** [comment]
This is available in the test basemap file at \wsdot.loc\hq\Public\30Day\GRDO\HunterR\HATSiOS\basemapWithSensitiveAreas

**Comment by ReedHunter-Wsdot** [comment]
published for download
