### ISSUE TITLE
Edit feature location attributes

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#881]
@jhudsonWA Joe and I got to talking about this again this morning. Is there a way to allow for location data to be edited via the iPad (i.e. direction, SR/SRMP, etc.)?

**Comment by jhudsonWA** [comment]
Of course. I just spent 3 days in Disneyland. Anything is possible (and in this case easy enough)

Sent from my iPhone

On Nov 13, 2017, at 11:56 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #881<https://github.com/WSDOT/HATS/issues/881> to @jhudsonWA<https://github.com/jhudsonwa>.

**Comment by kechinn** [comment]
LOL. Cool, sounds good:)

**Comment by jhudsonWA** [comment]
Now in the latest 3.5 beta.
