### ISSUE TITLE
Excel and Grid Buttons not matching in Activity Dashboard

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#889]
@jhudsonWA Got an email from SW region about some weirdness with the dashboard. Confirmed that when you click on the grid button for Inspections it shows 5 runs on the web page, however when you click to export to excel it only shows 1. Seeing same issues with other region pie charts.

**Comment by jhudsonWA** [comment]
We know about this one. Joe pointed it out Thursday night. Thanks for creating a tracking issue.

Sent from my iPhone

On Dec 5, 2017, at 7:03 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #889<https://github.com/WSDOT/HATS/issues/889> to @jhudsonWA<https://github.com/jhudsonwa>.

**Comment by jhudsonWA** [comment]
Check it out now in a few regions. The issue was that the charts and excel used the start/end date picked on the screen where the webpage grid always used NPDES reporting year, which doesn't match up for cable barrier.

**Comment by jhudsonWA** [comment]
Fix pushed as 5.5.12
