### ISSUE TITLE
HATS/AVL Web: Join Crew Manager Operator Data with AVL OperatorId

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#893]
For reporting and linking to employee data, join "AVL Serial Number" from Crew Manager to the "OperatorID" in AVL.

This will allow one single point for operator/crew data.

**Comment by jhudsonWA** [comment]
Add this as a discussion the next time we meeting in person. We have discussed before but I want to know where in the current AVL reports, screens, maps, etc you would want to see the crew manger data and what from crew manger would come over on the "join"

**Comment by joeschmit** [comment]
Will do.

**Comment by sheppamwsdot** [comment]
Closing because the request is stale.  Please re-open if this continues to be an issue in the future.
