### ISSUE TITLE
HATS Web: Create lookup table for "Work Op Codes" 

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#894]
-Add/Edit/Delete, Export list to Excel
-Feed to "Activities" 

Maintenance is looking to replace the current process from Financial Datamart pull.

**Comment by jhudsonWA** [comment]
Justification? (doesn't have to be here)

This will be a red flag for the data modelers for sure so lets discuss.

**Comment by joeschmit** [comment]
Currently we are using MS Access to create/manage the list that is then fed manually each year to TRAINS, looking for a more "modern" tie in.

**Comment by jhudsonWA** [comment]
I can dig it.

**Comment by jhudsonWA** [comment]
That is a good justification. :) Timeline?

**Comment by joeschmit** [comment]
Sometime before the end of 2018

**Comment by joeschmit** [comment]
@jhudsonWA can i bump you on this ::bump::

**Comment by jhudsonWA** [comment]
Starting work on this now.

**Comment by jhudsonWA** [comment]
This will be in QA on next push.
