### ISSUE TITLE
HATS Web: Other Activity Records Missing "End Date/Time"

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#896]
Seems that our "Other Record Types" on web that are flagged to have End Date/Time are missing the said fields via web. They are visible on iPad just fine.

**Comment by kechinn** [comment]
All good, set to false on web.

**Comment by jhudsonWA** [comment]
Reopening to make sure that the ipad/web no longer use the hardcoded snow/ice logic. Both should be using the flags we setup for activities for trucks and end dates.

**Comment by jhudsonWA** [comment]
Seems to no longe be an issue.
