### ISSUE TITLE
HATS - Sub- Category Toggles for Training Videos

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#898]
Please see attached informational graphic. 

![sub category toggles](https://user-images.githubusercontent.com/15268732/33728943-fcaf6e90-db30-11e7-9c72-ff28c6312a0f.png)

**Comment by jhudsonWA** [comment]
Bumped to 4.0 now that we have a new schedule/scope for 3.5

**Comment by jhudsonWA** [comment]
@lundyc-wsdot You can help me on this one on the web side. We need to update the FileLibraryUrl table to allow for parent/child ids. We will need to work with Marina to rework categories. Right now they are simply text entered. They probably need to be moved to their own table so we can set up child/parent ids.

**Comment by lundyc-wsdot** [comment]
In the 558 rows in table MobileFileLibraryUrl (in production), 20 distinct CategoryName va;ues are contained.  There are sub-caregories such as Training Videos vs. HATS Training Videos vs. iPad Video Tutorials and perhaps others, so there would be some decisions in that area.

It appears to be doable.

They are primarily referring to videos, but it appears to me that we should consider sub-categorizing the other types of media also while we are doing.

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
The web is ready in QA to allow assigning categories and sub-categories. Working on fishing up displaying these on the iPad. Should be good to go for Web 6.9 and HATS 4.0 (beta incoming Monday)

**Comment by jhudsonWA** [comment]
This is done. Creating 4.0b10 now

**Comment by jhudsonWA** [comment]
![simulator screen shot - ipad pro 9 7-inch - 2018-10-23 at 10 28 00](https://user-images.githubusercontent.com/702446/47378929-64499e80-d6ae-11e8-9ad4-5adda3a279cf.png)

**Comment by jhudsonWA** [comment]
![simulator screen shot - ipad pro 9 7-inch - 2018-10-23 at 10 28 13](https://user-images.githubusercontent.com/702446/47378946-6ad81600-d6ae-11e8-963c-654ec8f617c4.png)
