### ISSUE TITLE
Set Filter on Attributes to show all users

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#903]
Not all users are able to see the Filter on Attributes button on HATS web Feature Inventory page.

**Comment by jhudsonWA** [comment]
Have you seen this? I'm seeing any logic that would hide this option for any users

**Comment by PeterBurkhard** [comment]
I conducted a class last week in a class room full of WSDOT PC's. From my account on the main instructor PC I showed the class how to run reports on Pavement Markings / 2326 - Inspect Pavement Markings Durable. Jeremy Combes did not have the include checkboxes on his screen. I verified he was on the same page I was:
http://hatsprod.wsdot.loc/Maintenance/management/activities/FeatureActivityRecordReports/ActivitiesReport

Or 

http://hatsprod.wsdot.loc/Maintenance/management/activities/FeatureActivityRecordReports/ActivitiesCoverageReport

Include Deleted Records:   (Missing)

Include Feature Attributes:    (Missing)


<img width="1613" alt="missing check boxes" src="https://user-images.githubusercontent.com/15268732/34184538-27ec4d1e-e4d5-11e7-93a0-ad52cb0aa4f6.png">

**Comment by jhudsonWA** [comment]
Well that is a different page than Feature Inventory. :) 

Looks like the bug is that Included Deleted was supposed to be Admin Only, but the include feature attributes got in that check.

Should deleted be admin only? I've fixed the feature attributes so it always shows in next beta

**Comment by PeterBurkhard** [comment]
Jeremy just wanted access to attributes in his reports. :)

**Comment by jhudsonWA** [comment]
Then fixed in the next big release.
