### ISSUE TITLE
Search Filter On Attributes text fields

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#905]
Any way to search by a word or part of a sentence rather than the exact wording within the Filter On Attribute text fields? Unless you know exactly what was written it is difficult to filter by that attribute.

**Comment by jhudsonWA** [comment]
Weird. I would assumed this is the way it was already written. We will make it so. Thanks!

**Comment by jhudsonWA** [comment]
Assigning to @lundyc-wsdot

**Comment by jhudsonWA** [comment]
Inventory -> Search Inventory -> Check Filter On Attributes and if there is a text box, we need to track down stored proc that filters and change to like to allow partials.

**Comment by jhudsonWA** [comment]
This is now in production.
