### ISSUE TITLE
New UI Issues: Other Activity Record

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#906]
(See issue about Feature Activity Record page - similar issues)

- ~~Other Activity type: West Nile > View/Edit record > Print button leads to server error~~
![image](https://user-images.githubusercontent.com/16247034/34184763-5b7b9c74-e4d6-11e7-9c40-619241bdf329.png)

- ~~Location is marked as required * but is not necessary in order to save record.~~

**Comment by jhudsonWA** [comment]
![ms-sb7vts](https://user-images.githubusercontent.com/702446/34185005-f671a2b8-e4d7-11e7-8456-e461084870ac.gif)

LOL

**Comment by jhudsonWA** [comment]
Other Activity type: West Nile > View/Edit record > Print button leads to server error - Fixed and pushed to QA

**Comment by jhudsonWA** [comment]
Copy and past error on location. Removed star and re-pushed. Should not be required (at least it is not now in prod)

**Comment by jhudsonWA** [comment]
All noted issues fixed and repushed. @kechinn Ready for retest. Close if complete.

**Comment by kechinn** [comment]
Tested and looks good.
