### ISSUE TITLE
New UI Issues: Current Feature Activity Page

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#907]
#906 (similar UI issues on this page too)

- ~~Start/End Dates are required, no option to search all (same for Other Activity Record page).~~ (As Designed)

- ~~Some Feature Activity Records (e.g. record # 279004) > History > Click Edit button > At bottom, missing Application:~~
![image](https://user-images.githubusercontent.com/16247034/34185642-64902d98-e4db-11e7-8d48-b00e741f529f.png)

- ~~Edit Feature Activity Record missing Start/End SRMP, Direction, SR and Location boxes.~~
![image](https://user-images.githubusercontent.com/16247034/34185621-35b7b784-e4db-11e7-95e9-16394f40ce04.png)

- ~~Location is marked as required * but is not necessary in order to save record.~~

**Comment by jhudsonWA** [comment]
@kechinn for: Some Feature Activity Records (e.g. record # 279004) > History > Click Edit button > At bottom, missing Application:

The page is displaying what is in the database. The issue is the ApplicationVersionId is null in the database. I'm looking into that. Other issues are fixed and pushed and ready for retest. Close if fixed.

**Comment by jhudsonWA** [comment]
Fixed bug that was causing web saved records to save as null. Looks like iOS was fine. Will not update current records, but fixed for new once this version is pushed.

**Comment by kechinn** [comment]
@jhudsonWA I realize I never wrote the note I had for the first picture. Didn't see this on anything else, but when searching for Avalanche Occurences from previous year, there were missing Attribute and history buttons (see top image).

**Comment by jhudsonWA** [comment]
Taking a look

**Comment by jhudsonWA** [comment]
Those records are not tied to a feature. Probably because we started Avalanche as a other type then migrated over before launch. I think we will be fine in prod.
