### ISSUE TITLE
Web Bug: Add Pesticide Application

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#910]
Noticed this in QA and same thing happening currently in Prod- seeing Error Application set object object popup when entering the Total Gallons of Mixture or Pounds Dry Applied @ * question and clicking the Product Information button throws Ajax Fail! error in red at top after any editing of the location information (direction, mp, lat/long) in Location List.
![image](https://user-images.githubusercontent.com/16247034/34216256-946f0a6c-e55c-11e7-96c2-995602ea4148.png)

![image](https://user-images.githubusercontent.com/16247034/34216299-addb1536-e55c-11e7-9712-af773d44d0c4.png)

**Comment by kechinn** [comment]
To add to this issue...if you go to a current record and edit the location information and hit save (without touching the product info section) then it saves just fine. But if you do edit the location information and attempt to add a new product in the Product Information section then it will throw the errors. 

Also, after the location info is edited, if you try to edit an existing product, it will not allow you to do so-clicking the edit button does nothing. If you have more than one product in the Product List and click one of the delete buttons, it will delete ALL products in list.

**Comment by jhudsonWA** [comment]
Neither of those bugs are optimal. I’ll fix those in both QA and production today…

On Dec 20, 2017, at 8:25 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


To add to this issue...if you go to a current record and edit the location information and hit save (without touching the product info section) then it saves just fine. But if you do edit the location information and attempt to add a new product in the Product Information section then it will throw the errors.

Also, after the location info is edited, if you try to edit an existing product, it will not allow you to do so-clicking the edit button does nothing. If you have more than one product in the Product List and click one of the delete buttons, it will delete ALL products in list.

**Comment by jhudsonWA** [comment]
@kechinn Fixed in QA and Prod. Please retest then close if fixed.

**Comment by kechinn** [comment]
@jhudsonWA Testing, all previous errors and seems all good. Noticed one new thing though - there is no ability to add or view attachments from View/Edit page. Is that a bug or was it set up that way for a reason? 

Might also be helpful to have a search by records with attachments button since there is no way to know from that search screen which records ones do or don't (can only track back from all pesticide application attachments screen).

**Comment by jhudsonWA** [comment]
So the ability to add attachments via the web was cut due to time needed to launch pesticides and apparently never picked up again. Please add issues for adding/editing attachments, plus one for searching pesticide records with attachments to make it #hatsy and I'll close this task since the bug has been fixed.
