### ISSUE TITLE
New UI Issues: Add Pesticide Application

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#911]
Filled out QA pesticide record normally (without editing anything) and it does not recognize added Route Segment or Product information, will not let you save and shows error detected warning at top of screen.

![image](https://user-images.githubusercontent.com/16247034/34217735-17449246-e561-11e7-800c-12b4561efa56.png)

Also see #910 -Same edit location bug

**Comment by jhudsonWA** [comment]
Probably related to other issue you reported. Thanks

On Dec 20, 2017, at 8:39 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Filled out QA pesticide record normally (without editing anything) and it does not recognize added Route Segment or Product information, will not let you save and shows error detected warning at top of screen.

[image]<https://user-images.githubusercontent.com/16247034/34217735-17449246-e561-11e7-800c-12b4561efa56.png>

**Comment by jhudsonWA** [comment]
@kechinn Fixed. Copy and paste issue on my side with the new UI. Please retest.

**Comment by kechinn** [comment]
Tested and is working fine, closing.
