### ISSUE TITLE
Vertical Align TOC in HATS AVL Map

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#912]
Currently centered on AVL symbols

**Comment by kechinn** [comment]
Also, at some point update map layers in Prod for new layer Ferry Anchor Points (currently seen only in QA map)

**Comment by jhudsonWA** [comment]
@kechinn Ready for retest. May have to control refresh to pick up the new javascript

**Comment by kechinn** [comment]
Looks much better, thanks:) 
Now, just need to talk to Reed about the labels themselves (text spacing, commas and what not).

**Comment by jhudsonWA** [comment]
We can open new issue on that when you are ready. Lets close this one.
