### ISSUE TITLE
New UI Issues: Find K-Job Cost Estimates

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#914]
- ~~Start/End Date not required (if we're doing it to other pages, makes sense to also do it here). It's thrown me a runtime error once while searching.~~

- ~~Search all is pulling what appears to be records from Prod and if you click view/edit on one then it throws server error~~ (Only one record is throwing an error due to invalid police division. I'm looking into that)
![image](https://user-images.githubusercontent.com/16247034/34227484-1bc655cc-e582-11e7-80d3-85e245e66053.png)

- ~~Details popup button does not work~~

- ~~Start/End SRMP does not always capture correct ranges e.g. I search between 10 and 20 and it returns records with end mp of190~~ (the QA database was loaded with prod data a while back so that explains all the records)
![image](https://user-images.githubusercontent.com/16247034/34227284-7cc83922-e581-11e7-8d21-0ca645a8da77.png)

- Enhancement (can create separate GitHUb Issue if needed) > Separate Date Type into "Occurred" and "Observed" rather than "Occurred/Observed". Also, move "Create" Date Type to it's own box because it is misleading (in record the only date types are occurred and observed) and because it overwrites the filter Start/End Date with the record history.

**Comment by jhudsonWA** [comment]
For this one the Start/End does not only capture K's that fall only in that range. From the start it's always found any damage in that range (start or end). The damage does not have to be fully contained in the start/end range. As long as one value falls within the range it returns. As designed.

**Comment by jhudsonWA** [comment]
@kechinn ready for retests (except for crasher). Please add this one as new.

Enhancement (can create separate GitHUb Issue if needed) > Separate Date Type into "Occurred" and "Observed" rather than "Occurred/Observed". Also, move "Create" Date Type to it's own box because it is misleading (in record the only date types are occurred and observed) and because it overwrites the filter Start/End Date with the record history.

**Comment by jhudsonWA** [comment]
Crasher is due to page being updated to not show all police divisions so old records that had one police devision set may no longer have them in their list due to regional issue. I'll make it so it no longer crashes and adds the existing police division to their list when viewing.

**Comment by jhudsonWA** [comment]
@kechinn crasher is fixed. Edit should load just fine now. All should be ready for retest

**Comment by kechinn** [comment]
Tested and all seems good. Will add enhancement as new issue.
