### ISSUE TITLE
New UI Issues:  Find General Estimates

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#915]
Similar search issues to #914 with filter by SRMP

- Details popup: Estimated Costs are showing the same as Actual Costs (checked Prod and this is also the case there as well. I thought that this had been resolved in past, but seems like it's still popping up)

**Comment by jhudsonWA** [comment]
@kechinn  Fixed in QA. Actuals/estimates should print correctly for general and K popups: ready for retest.

**Comment by kechinn** [comment]
All good:)
