### ISSUE TITLE
Police Division Server Error

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#916]
@jhudsonWA Adding the ddlPolice error as separate issue here for better tracking.

**Comment by jhudsonWA** [comment]
Should be fixed. Please verify.

Sent from my iPhone

On Dec 20, 2017, at 2:40 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #916<https://github.com/WSDOT/HATS/issues/916> to @jhudsonWA<https://github.com/jhudsonwa>.

**Comment by kechinn** [comment]
Not seeing this issue anymore - closing.
