### ISSUE TITLE
New UI Enhancement: Find K-Job Cost Estimate

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#917]
As discussed, making a new issue for this one.

Separate Date Type into "Occurred" and "Observed" rather than "Occurred/Observed". Also, move "Create" Date Type to it's own box because it is misleading (in record the only date types are occurred and observed) and because it overwrites the filter Start/End Date with the record history.

**Comment by jhudsonWA** [comment]
Assigning to @VinceRanger

**Comment by sheppamwsdot** [comment]
Closing because the request is stale.  Please re-open if this continues to be an issue in the future.
