### ISSUE TITLE
Canned Comments Enhancements

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#924]
So, looks like the same things are set up in Prod too. Enhancements more than UI issues.

- Don't know if it's because I'm an admin, but can see all canned comments set to a feature/other type regardless of what OrgCode its been set to

~~- You can put letters in the OrgCode field~~

~~-Any chance admin can get ability to delete altogether rather than just set to false? Sucks if you mess up because you can't edit the comment text or the feature, just the orgcode~~

~~- Can add comment with no text~~ (looks like you just fixed it as I was writing this)
![image](https://user-images.githubusercontent.com/16247034/34277992-f82ca842-e65c-11e7-8d4d-6039a71707d7.png)

**Comment by jhudsonWA** [comment]
Comments without an org are like statewide comments. They always show up.

Sent from my iPhone

On Dec 21, 2017, at 2:45 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #924<https://github.com/WSDOT/HATS/issues/924> to @jhudsonWA<https://github.com/jhudsonwa>.

**Comment by kechinn** [comment]
Got that, but I was able to see one that was assigned to an org (e.g. "roadway deformation" for culvert feature assigned org 43).

**Comment by kechinn** [comment]
Lol, also not a big deal but it looks like a semicolon got left out of the code at bottom of page:)

**Comment by jhudsonWA** [comment]
Oh I see what you mean. Orgcode not filtering list

Sent from my iPhone

On Dec 21, 2017, at 2:45 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #924<https://github.com/WSDOT/HATS/issues/924> to @jhudsonWA<https://github.com/jhudsonwa>.

**Comment by jhudsonWA** [comment]
:) fixed on my side. I’ll look into logic could be admin

Sent from my iPhone

On Dec 21, 2017, at 2:50 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Lol, also not a big deal but it looks like a semicolon got left out of the code at bottom of page:)

**Comment by jhudsonWA** [comment]
I've moved this to be an enchantment. I'm not sure why delete and edit isn't an option. Seems silly since these are just copied into event. We will make the changes.

**Comment by jhudsonWA** [comment]
@kechinn Can you contact me so we can walk through this one. I'm not able to duplicate seeing orgcode specific comments.

I've fixed it so orgcode can't be text and added ability to delete.
