### ISSUE TITLE
New UI Issues: Pesticide Roadside Locations

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#925]
Similar to canned comments page...

- Can add location with no text

- Doubt this one will matter, but no character limit error, just cuts off (e.g. "Some remote place off the side of WSDOT Right of W~~ay~~")

**Comment by jhudsonWA** [comment]
Thanks!

**Comment by jhudsonWA** [comment]
@kechinn Fixed these, ready for retest

**Comment by kechinn** [comment]
Tested-All good.
