### ISSUE TITLE
New UI Issue: System Message

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#926]
- Clear button pops up the 'System Message Has Been Updated' box and then clears when you click OK . It removes any existing system message on screen, does not update if text changed.

**Comment by kechinn** [comment]
Nm. I realize that's a thing in Prod too. I was thinking clear cleared the text box, not the existing message itself.

**Comment by jhudsonWA** [comment]
I’ve updated in for next push to read Clear Current System Message

On Dec 21, 2017, at 3:16 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Nm. I realize that's a thing in Prod too. I was thinking clear cleared the text box, not the existing message itself.

**Comment by jhudsonWA** [comment]
pushed out. Should be a bit clearer
