### ISSUE TITLE
More UI Issues: Canned Comment

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#930]
Continued from #924
Noticed some other stuff to fix after I closed previous comment, will just put them here since these are smaller issues:

- ~~Comments will not delete when clicking X and shows "Failed to deleted (lol) comment"~~

- ~~"the orgcode" is written repeatedly under number of canned comments~~

- ~~Consider retitling from "Feature" to "Activity" or something else since it also includes Other activities that are not features~~

**Comment by jhudsonWA** [comment]
LOL? "the orgcode" is written repeatedly under number of canned comments WHAT?!?! How did that happen. 

Also fixed the failed to deleted text. Copy and paste error. :) 

Also fixed the ; issue for real this time.

**Comment by kechinn** [comment]
@jhudsonWA So, the text for cannot delete is fixed, but you still cannot delete an object by hitting the X. Did you want to leave this open or are you working on that?
