### ISSUE TITLE
Table of Contents Tool not lighting up in blue.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#934]
When you tap the table of contents tab it does not become blue like the map search, add feature and information tools. Not a big issue but is not consistent
![table of contents tool not lighting up in blue](https://user-images.githubusercontent.com/15268732/34746782-30c31f00-f54a-11e7-8d02-e2a570392d55.jpg)
.

**Comment by jhudsonWA** [comment]
Thanks. I can look into it for 3.5. I think the initial thought was we wanted a way to indicate what tool on the right was the active one and the TOC is not a tool. But should be easy enough to do both.

**Comment by PeterBurkhard** [comment]
I've been traveling around the state calling it the Table of Contents Tool.   :/

**Comment by jhudsonWA** [comment]
Will be in next beta
![simulator screen shot - ipad pro 9 7-inch - 2018-01-10 at 16 22 55](https://user-images.githubusercontent.com/702446/34802481-b21b1b92-f622-11e7-865a-ca3a66a1e682.png)


![simulator screen shot - ipad pro 9 7-inch - 2018-01-10 at 16 22 48](https://user-images.githubusercontent.com/702446/34802477-b0876b3c-f622-11e7-85a0-c75e74632535.png)
