### ISSUE TITLE
(App Feedback) It would be great to add a new features just for irrigation systems to mark location s of main shut offs and back flows devices.

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#94]
Device Name: SWC6431103 
Device Model: iPad Air 
Device System Version: 8.4 
Application Version: HATS-iOS 1.1 
Name: Matthew Hays 
Location: 45.65168762207031,-122.6676712036133
Has Attachments: False 

Feedback: It would be great to add a new features just for irrigation systems to mark location s of main shut offs and back flows devices. And mainly location of system valves this will so much time and money. And I mean thousands of dollars in water waste and time management. Thank you. 

Details: View Details

**Comment by PeterBurkhard** [comment]
Doug Gow has brought this up as well. Eastern region would like this. Can we make this happen?
Negative.

Device Name: ERD7991003 
Device Model: iPad Pro (12.9-inch) 
Device System Version: 12.3.1 
Application Version: HATS-iOS 4.3.3 
Name: Doug Gow 
Location: 47.6826230427197,-117.408452698569
Has Attachments: False 

Feedback: Blake Gerdes for Ritzville is requesting a new feature under the “Other” category for locating and marking irrigation valve boxes. They are commonly in shrub area and get overgrown and difficult too find for new individuals. Spokane has asked for the same. 

Details: View Details

**Comment by Douggow** [comment]
So is this a NO?

**Comment by PeterBurkhard** [comment]
Doug the word "Negative" above was from your response to my question, "Doug has anyone gotten back to you yet about this". I failed to delete it from the original copy and pasted email. @ReedHunter-Wsdot can we do this?

**Comment by ReedHunter-Wsdot** [comment]
There is time to add more features.  In case several other layer types show up to be included I'll add this a few weeks before release.

It's better to pay the overhead only once and add all the new layer types at the same time.


________________________________

**Comment by PeterBurkhard** [comment]
Another request for this feature has come in. 

Hi James I believe this idea has been requested previously. If so it is logged into GitHub here: https://github.com/WSDOT/HATS/issues/94
Please take a look, and if this not what you are requesting please call me 360 705 7847

Thanks for your feedback!

😃 Have a Great Day! 

Peter Burkhard
Technology Resource Program Specialist
Headquarters Maintenance UAS Program Manager
Information Technology - Headquarters Maintenance Division - WSDOT
Office ( 3 6 0 ) 7 0 5 - 7 8 4 7

On Oct 28, 2019, at 7:01 AM, HATSiOSFeedback@wsdot.wa.gov wrote:

Device Name: SCD9760766 
Device Model: iPad 5 
Device System Version: 13.1.2 
Application Version: HATS-iOS 4.3.3 
Name: James MacRoberts 
Location: 46.0913508665246,-118.259811345598
Has Attachments: False 

Feedback: Could you make a marker for valve boxes in landscape areas in hats 

Details: View Details

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
