### ISSUE TITLE
MSM Hyperlinks

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#940]
Markdown recognizes hyperlink, but cannot be opened from HATS iOS. Would be cool if users could click a link when connected to WiFi:)

![image](https://user-images.githubusercontent.com/16247034/35285035-31316dee-0011-11e8-8279-4e989951e6b4.png)

![image](https://user-images.githubusercontent.com/16247034/35285804-28e3a542-0013-11e8-828d-2a360badc7d9.png)

**Comment by jhudsonWA** [comment]
Fixed. Links in the System Message will now open in Safari on device in next beta.
