### ISSUE TITLE
Mini Map inside records requiring mileposts. 

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#945]
Mini Map inside records requiring mileposts. I keep getting the question - " Can we auto populate SR MP when we collect GPS?". 

<img width="1024" alt="map record mockup" src="https://user-images.githubusercontent.com/15268732/35521122-cfab7d14-04cd-11e8-8272-111048c2e81d.png">

**Comment by PeterBurkhard** [comment]
We really want this, I won't let it Die!

**Comment by jhudsonWA** [comment]
Set for 4.5 in spring.

**Comment by jhudsonWA** [comment]
Duplicate
