### ISSUE TITLE
Basemap Identify Attributes

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#950]
I've gotten requests for more of these basemap attributes. Maybe would also help us get set up for searching for these features by attribute later?

- At some point during one of the updates, the attribute to mark Fuel Stations disappeared (i.e. Gas (G), Biodiesel (B), Electric (E), Propane (P), or Diesel (D))
- Add direction indicator (i.e. Inc, Dec, Both, Ramp) to the 24k Route Segments
- Add street name for Local Roads
- Names of Cities

I've also gotten requests to make the County and Maintenance Area layers able to be turned on and off for clearer viewing of boundaries, so worth testing removing the '_' in the runtime SDK.

**Comment by ReedHunter-Wsdot** [comment]
Yep, I can add a table of to the identify results so we can show some more attributes.
