### ISSUE TITLE
New UI Issue: Raw AVL Report 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#956]
The calendar month and year for Begin and End Date for the Raw AVL Report is missing.

![image](https://user-images.githubusercontent.com/16247034/35987653-20fa30d0-0cb1-11e8-9ad4-8026142bf230.png)

**Comment by jhudsonWA** [comment]
Oops, missed converting a calendar. Fixing now.

**Comment by jhudsonWA** [comment]
This has been fixed and pushed to prod
