### ISSUE TITLE
Add Predefined Comments for Feature Attributes

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#957]
Brought into question after learning about how Jerri has been typing (or copy pasting) same values in on the iPad for multiple Zone 1 Spray lines, etc.

**Comment by joeschmit** [comment]
Canned comments for attributes?

Why not simply make “Predefined” attributes? Like a drop down menu...?

- Joe

On Feb 8, 2018, at 12:16, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Brought into question after learning about how Jerri has been typing (or copy pasting) same values in on the iPad for multiple Zone 1 Spray lines, etc.

**Comment by jhudsonWA** [comment]
I thought of that as well, but here is an example: We could make the Prescription a multiple select attribute but do the oz differ for those products? I guess that would be a pesticide team question. If not then multiple select would work, if they do then thinking of ways to make editing text box based attributes easier. 

![img_0188](https://user-images.githubusercontent.com/702446/35996595-cf7e5536-0ccb-11e8-9ee5-c0ff4cb2aada.PNG)

**Comment by kechinn** [comment]
I will talk with Ray when he's back in next week. I think the type and oz can change for each region and/or maintenance area on a annual basis.

**Comment by sheppamwsdot** [comment]
Duplicate
