### ISSUE TITLE
Pending Level 2 Culvert Inspections

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#960]
I would like to have all existing pending level 2 culvert inspections for a feature close out once a level 2 culvert inspection is performed on that feature. This would be the same set up as catch basin cleaning.

**Comment by jhudsonWA** [comment]
I'll add this to the work list. May be a week or so but it's doable.

**Comment by jhudsonWA** [comment]
This is done and has been deployed to production.

**Comment by jhudsonWA** [comment]
It will only affect new level 2 inspections coming in.
