### ISSUE TITLE
(App Feedback) The MP I I putted were 40.2 & 44.2 When I re-read report before I synced they changed

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#97]
Device Name: NWC0858010 
Device Model: iPad Air 
Device System Version: 8.4.1 
Application Version: HATS-iOS 1.1.1 
Name: Kathryn Rogers 
Location: 48.1945915222168,-122.6393203735352
Has Attachments: True 

Feedback: The MP I I putted were 40.2 & 44.2 When I re-read report before I synced they changed! See attached 

Details With Attachments: View Details And Attachments

**Comment by joeschmit** [comment]
Device Name: NWC0858010 
Device Model: iPad Air 
Device System Version: 8.4.1 
Application Version: HATS-iOS 1.1.1 
Has Attachments: True

Feedback: Database Uploaded For Support. Reason: Requested by HQ viaJoshua Hudson 

Details With Attachments: View Details And Attachments

**Comment by jhudsonWA** [comment]
This is purely a display issue. Has to do with round trip of decimal into and out of sqlite. I thought I had caught most of these cases, looks like she found one.

**Comment by jhudsonWA** [comment]
Could not duplicate, even with database she sent. The fields she had the issue with do indeed have code that formats all numbers to 0.xx. Lets close this and if reopen if it comes up again.
