### ISSUE TITLE
Export Region and Maintenance Area Attributes

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#975]
Would be helpful to allow export Region and Maintenance Area as an attribute on feature activity exports, as well as showing them in the pop up attribute boxes on web.

**Comment by jhudsonWA** [comment]
Easy enough. I'll make the changes. Also I think I'll add a dedicated export attributes checkbox instead of re-using the "filter". Seems odd to hit filter just so attributes are included on the export

**Comment by jhudsonWA** [comment]
Both are done and in QA/Prod

**Comment by kechinn** [comment]
Can we change the Maintenance Area from common name to the area number? I think that is more widely used (especially when it comes to GIS).

**Comment by jhudsonWA** [comment]
I can show both - Like Area 1 - Kent

On Apr 3, 2018, at 1:13 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we change the Maintenance Area from common name to the area number? I think that is more widely used (especially when it comes to GIS).

**Comment by jhudsonWA** [comment]
Done, Maint Area now shows Area 1 - Kent
