### ISSUE TITLE
(Data) Hide large group of Culvert Ends in database - status = Removed

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#98]
on SR 009 from MP 4.5 to 7 please hide all culvert ends, reason should be "Removed".  There is a project going through the area and all of these have been converted to the linear "Culvert" feature via iPad.

**Comment by jhudsonWA** [comment]
@joeschmit . Just seeing this. Still needed?

**Comment by joeschmit** [comment]
Nope.  I will be retiring "Culvert End" entirely as of 11/1/2015.  Setting the active published flag to false.

On Oct 23, 2015, at 09:49, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Joe. Just seeing this. Still needed?

�

**Comment by jhudsonWA** [comment]
Groovy, lets close this out then.
