### ISSUE TITLE
Activity Form Builder Predefined Parameters Caps Lock

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#986]
For whatever reason, when you add the parameters "Ton" and "Bag" in the activity form builder, after save it puts the words in all caps.

![image](https://user-images.githubusercontent.com/16247034/38527546-2b4d91ec-3c10-11e8-8780-186e4fb13f45.png)

**Comment by jhudsonWA** [comment]
@brianblood 

This is my new favorite bug.

**Comment by brianblood** [comment]
It’s a good one, isn’t it?

It’s doing an exact string match to ‘Bag’ and finding ‘BAG’ already exists in the database.    We can force it to create a new parameter if the casing doesn’t match, but it may confuse things a bit.  Or we could manually update the CAPS versions of these parameters.  Fortunately, this appears to be only in QA for these guys, but would be the same in Prod if you entered in a new parameter with wacky casing.  Once it’s in, it can’t be changed in the UI.

**Comment by jhudsonWA** [comment]
Ah, yes case sensitivity is not a thing in SQL. I think we want to keep it as it is. We can probably fix casing manually if required.


On Apr 9, 2018, at 4:37 PM, brianblood <notifications@github.com> wrote:

It’s a good one, isn’t it?

It’s doing an exact string match to ‘Bag’ and finding ‘BAG’ already exists in the database. We can force it to create a new parameter if the casing doesn’t match, but it may confuse things a bit. Or we could manually update the CAPS versions of these parameters. Fortunately, this appears to be only in QA for these guys, but would be the same in Prod if you entered in a new parameter with wacky casing. Once it’s in, it can’t be changed in the UI.

**Comment by brianblood** [comment]
Updated the two offending records manually.
