### ISSUE TITLE
AVL Raw Data Report Spelling Mistake

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#987]
Spelling mistake when you use a date range greater than 7 days in Raw AVL Data Report.  "Date interval greater than 7 days. Please use dates thare a 7 days or less apart." :)

![image](https://user-images.githubusercontent.com/16247034/38585843-41121172-3cd0-11e8-97a2-9b710bf0ea3b.png)

**Comment by jhudsonWA** [comment]
Fixed in next prod push.
