### ISSUE TITLE
(HATS Web) When clicking Attributes on Add New Feature Record, popup has bug

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#99]
When clicking Attributes on Add New Feature Record, popup has bug

See image..

![snipimage](https://cloud.githubusercontent.com/assets/884943/9392215/367c87f8-4730-11e5-9366-245ebb163406.jpeg)

**Comment by jhudsonWA** [comment]
Fixed in 4.2, verified all the other attribute popups.
