### ISSUE TITLE
Export Region and Maintenance Area With Current Records and Activity Report

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#990]
Export Region and Maintenance Area With Current Records and Activity Report, currently only shows them with Feature Inventory export.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot after #992 please work on this. Activities -> Feature -> current records. All records here are tied to features, features have Region and Maint Area. Please add to the excel export on Current Records

**Comment by jhudsonWA** [comment]
Done in Dev
