### ISSUE TITLE
HATS Web Admin/MobileFileLibraryUrls Search Option or Category Filter for Editing Purposes.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#992]
It would be reeeeeaaallly nice to find files you need to edit a little more efficient.
Pretty please?

**Comment by jhudsonWA** [comment]
@lundyc-wsdot this is under Admin File Library Urls. Please add a filter section above the grid that lets them find files in the list by name, category, region, maint area.

**Comment by jhudsonWA** [comment]
Done in dev
