### ISSUE TITLE
HATS Web: Search Inventory > Filter by Attributes > Make always active

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#993]
Users are liking the "Filter by Attributes" function within the inventory search, but feel it would be easier to just have it "activated" by default.

One more step could be to just remove the true/false altogether and have it active each time?

**Comment by brianblood** [comment]
Removing the Filter On Attributes or setting it to ‘checked’ by default are both pretty trivial changes.  I think removing it makes more sense – if someone doesn’t want to filter on attributes they can just ignore that section.  I don’t know why they would feel the need to uncheck a box to hide the inputs.

**Comment by joeschmit** [comment]
Yep – agree.
“I think removing it makes more sense – if someone doesn’t want to filter on attributes they can just ignore that section. I don’t know why they would feel the need to uncheck a box to hide the inputs.”

**Comment by brianblood** [comment]
Checked into TFS, will go out with next release.
