### ISSUE TITLE
HATS attributes available in Biest

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#994]
From Catherine LaPointe's email:

Hello Joshua, I have 417 short span bridges in the Biest that have corresponding culverts in HATS. 

The Biest Records have both the material type and the diameter in feet. Some of the corresponding HATS culverts do not. 

I have a spreadsheet that matches the Bridge Structure ID and the HATS Feature Number. 

Could/Would/should these HATS records be updated with the material type and diameter from the Biest when the corresponding HATS attribute is null? The Biest.length for this set of culverts is equal to the Atribute.diameter in HATS.

Can this be done (one time) programmatically rather than going into each HATS record and updating by hand?

Catherine LaPointe, PE
HQ Hydraulics
(360) 705-7498

[WSDOT-owned short span bridges_CBL_4-9-18.xlsx](https://github.com/WSDOT/HATS/files/1925006/WSDOT-owned.short.span.bridges_CBL_4-9-18.xlsx)

**Comment by sheppamwsdot** [comment]
Closing due to a lack of customer follow-up.
