### ISSUE TITLE
HATS Web > Search Inventory > If Pending Activity >0 then Output Pending Activity Name

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#995]
Add a column "PendingPlannedActivityName"

**Comment by jhudsonWA** [comment]
What happens if there are more than one pending activity types? Like a repair and cleaning for the same feature?

**Comment by jhudsonWA** [comment]
@joeschmit Please see comment on June 6th? Thoughts? I can assign to vince if still needed.

**Comment by joeschmit** [comment]
@jhudsonWA @VinceRanger yea so if there is multiple, add them to the column, separate with comma. This request was to help in the effort of managing the influx of Pending's...

**Comment by sheppamwsdot** [comment]
Per Josh: Technically Complicated.  Reopen if requested in the future.
